var groups = [];

groups.push(["wzaopvscxknyjtiul", "belforsgdhuvmwc"]);
groups.push(["kiocpzjhsetqnwbl", "maciywlbpodgevujnsktrz", "kpebjfchtlsonwiz", "pcezwjtsinxlobk"]);
groups.push(["lrcp", "cdlbepr", "rlqcyutp", "lcpr", "lrtcpym"]);
groups.push(["gxcqbowaelfjhpknz", "gflhackzwqxojeb", "lfwocexqbkjhgaz"]);
groups.push(["fpivaozqnkextmbrjhycdwug", "motgcrzaisqlpdwbeyhukf", "hbiqcdmkpawueyztgfor", "zrcehkqyoblmtgfiaupdw"]);
groups.push(["umjz", "jzu", "vzowkpuj", "jmzau"]);
groups.push(["unzlx", "lnzxu", "mxluzn", "nzuxli"]);
groups.push(["szkiauhyntdrbcljomqwepv", "amowcpzbyukihsjtqelnd", "lzctuqjabmsynphkewxido", "sikblhptcoqemdanywzju", "jdeiylutspabcwngfzqkhom"]);
groups.push(["zgyhwtnxjdqucbp", "ptnzhudjbcxgkqf", "zgqhjbdnutcmpx", "gjbzhpdxanqcut"]);
groups.push(["wjkcsqlu", "ucsjq"]);
groups.push(["vkzsqtunmr", "ljcexadhg"]);
groups.push(["fhtrusba", "svtk", "pgzwytn", "astb"]);
groups.push(["hvzjiwlsmnatbxgqcuke", "zeaukbgtnjxslmvwiqc", "tqsjxvznemblwkgcuai", "atwjqckzmgvnlbuxise", "mwkteqbcjasvxuizlgn"]);
groups.push(["gypubxsntl", "untylgpsb", "uynbgltps", "nylgutpsb", "unsltybpg"]);
groups.push(["qwygnalv", "rxdohlnatwy"]);
groups.push(["fcytwkqjaorm", "rqfcjokwtmay", "cjyftkaqmrwo", "tqomfrwycakj", "cjktaroqmfwy"]);
groups.push(["ygnjepucrfkxq", "ypnqjfgcuerxk", "fyghkncqpjxuer", "runfcyxgjqpek", "qxjrupnygkcfe"]);
groups.push(["rneuh", "rhneu", "rhune"]);
groups.push(["dyct", "tycd", "cdty", "ytdc", "cdty"]);
groups.push(["hoaxpnic", "zrocenxaphui", "pigyovantxch", "vanbocxdpihw"]);
groups.push(["nmadf", "cdbykfwtim", "fdms"]);
groups.push(["xrlweqhyomniupgasjb", "wxlaijmhqbopnugsery", "xmkuswchylpbeqirngojfa"]);
groups.push(["u", "yuq"]);
groups.push(["d", "d", "d", "dqf"]);
groups.push(["kfnbcvxtogwhsz", "nctfsoezgwhkvb", "kncbtvgwsozhf", "kcfsobzntgrwhv", "obnsfczkrvwhtg"]);
groups.push(["ektcsq", "tcpqesdk", "ightwqxosekj"]);
groups.push(["y", "y", "y"]);
groups.push(["oaqwmublkjz", "qhkduvibzmfx", "bomkquz", "bzpuqwmko"]);
groups.push(["uybzfemjhvnp", "amxynpve", "kyvmenxp"]);
groups.push(["vpyznetlsow", "njewpszg"]);
groups.push(["a", "a", "a", "x", "a"]);
groups.push(["ytixaokbv", "vybaoxtudi", "kaivoytbx", "oavbxity", "vytbaixo"]);
groups.push(["okdmepqj", "kqodjpe", "kpdeoqj", "yqdpkeoj"]);
groups.push(["nqtkbvrjizuyhlwmxopscga", "ojzqryxwvpkclighnmeuabts", "socwtinpyakuqljzmrxvhbg", "sruhgbvjmpwnaklioqyzctx", "pmojxvkiwztgaslbuyhqrnc"]);
groups.push(["sruqibofpetmjxacnyw", "meoxusytawnfrhqicpb"]);
groups.push(["udzjvpxcmg", "vzmpdjgxuc", "vdgcxujzpim", "gpujzcmdvx", "jcvpzxmdug"]);
groups.push(["lwke", "jqa", "jdp"]);
groups.push(["ebcnymdxhsgjoptvkluw", "mhewbjgldvutnkxocysp", "odkvwhlcupyejbsmxntg", "ylhetjbxumpwdocgvkn", "yvugktojibqwncmlpehdx"]);
groups.push(["wc", "cw", "wc", "wc"]);
groups.push(["fnatmwk", "vbqnoptm", "zldysrjuiegcmx", "fm", "vmh"]);
groups.push(["e", "e", "e"]);
groups.push(["nd", "nd", "dn", "tdn", "nd"]);
groups.push(["bswceuimx", "vfugqjk", "phrbaulzsdy"]);
groups.push(["fcmpeuxkjiwtszhgnoravb", "tjhbsovuzipmracnxf", "zfxuvbitrcnamosjph", "bafxzhonrsipvcjumt"]);
groups.push(["uopkgzec", "uogckpz", "czgkopu", "gtuopckz"]);
groups.push(["k", "k", "k", "k", "k"]);
groups.push(["bucx", "zxfu", "oluinsxk", "cupfxb", "pxuz"]);
groups.push(["gw", "wg"]);
groups.push(["nif", "qby"]);
groups.push(["kazpqyrt", "uocensfmvw"]);
groups.push(["vjy", "srdfuy", "tyz", "yt", "jyow"]);
groups.push(["wcn", "d", "m", "r"]);
groups.push(["afo", "pruao", "afo"]);
groups.push(["jiqp", "jhp", "jp", "pj"]);
groups.push(["rvxucn", "xmurvtc", "uzvmrxc", "xeykobgvjpclharfu"]);
groups.push(["bc", "cb", "bc", "bc"]);
groups.push(["hxnparv", "vtqhxapn", "apnvhx", "dvwanihpxys"]);
groups.push(["jdszlimbca", "drtmxcqlw", "cmdzloub"]);
groups.push(["podyqvae", "qyapveod", "pvqedayo"]);
groups.push(["scmbwfuldnvkxqehjgatpry", "zgltckiwjnuebahmpfqvdrsx"]);
groups.push(["hu", "fkixsu"]);
groups.push(["a", "a", "a", "a", "a"]);
groups.push(["fkmupthae", "vumpwh", "ugxwmph"]);
groups.push(["kspnwvyr"]);
groups.push(["yxaw", "xw", "hzrmxbekw", "wicx"]);
groups.push(["l", "lz", "l", "l", "l"]);
groups.push(["rwn", "wnr"]);
groups.push(["tpankiydfghwlzv", "hwnztpvbcsykgl"]);
groups.push(["hcn", "cuhq", "qc", "uq", "xsdz"]);
groups.push(["izsctumjfvyo", "iuymczbtjo", "ytprwciogjkmzx", "iyztahnjemcdo"]);
groups.push(["kmepowc", "cwmkoep", "bmopkect", "cjepnkmqo"]);
groups.push(["gqlxpwt", "qgwtplv", "lpgmwcit", "twglpx", "gwtphl"]);
groups.push(["uiyeqacdlwxpgt", "deyxtgqaulicwp", "pgawxtyiucdelq", "iaepwxugtdlqyc", "aewygpuilxctqd"]);
groups.push(["ksextofz", "zxhesk"]);
groups.push(["zxnlhrd", "hlnxdbczr", "qnxfzdlhr"]);
groups.push(["foryns", "rnofsy", "fsyonr", "rosnyf", "orsnyf"]);
groups.push(["o", "o", "t"]);
groups.push(["raktoz", "atkzo", "vtkzoaf"]);
groups.push(["yianzfpwbqsvltcuhjg", "tpjzhvwfibacusylnq", "wdctlhzbjeqavnfiuyps"]);
groups.push(["mhexryd", "yerhdmx", "ehxymdr", "bgmrehxyd", "xreyhdm"]);
groups.push(["pebtkqchsoydz", "dklqohsupwcyztxe", "ckvmsqjpdhaetzofy", "wsuohqckerltypdzn", "lkxsyowcdzteqhp"]);
groups.push(["nqbmshlg", "ebshnqla", "sqngvb", "nbwqsi"]);
groups.push(["sauebdjhpwtcgnlzorfkxqyvim", "adpvbqlnofyxmiuzjsctwkeghr"]);
groups.push(["gy", "gy"]);
groups.push(["jf", "wpy"]);
groups.push(["guztycblrhfiq", "bertlfcmguhv", "lbytrcfk", "fscbltnpxwor", "lqfbjtcrdv"]);
groups.push(["egbvoxlmpczqnafyu", "enxqbazvpmolyfcug", "kpuezgxbqnaymvflocs", "vipegmfbnocqxuzlay", "mnofzbaylcqxegvpu"]);
groups.push(["wrclt", "lfrcw", "rcwl"]);
groups.push(["zbwvmuifpjxqnlgo", "jfpwmuznqxvbgio"]);
groups.push(["baheoslg", "fygoa", "aygo", "aog", "fmoga"]);
groups.push(["ltpdcyn", "ycdlnt", "lchgtydn"]);
groups.push(["fvdgksnmphxzcboql", "zboknxmfgdvclpq", "qdlkpgcbzvmoxfnt", "ciozqlvjgkwbfxdumpne"]);
groups.push(["gmlyqkjehrp", "ojeizhlgpm", "uhgpmflje"]);
groups.push(["atzscwnb", "snahqtc"]);
groups.push(["zyjml", "jryml", "lymtxvod", "mryil"]);
groups.push(["iudskmzex", "udqkzxesmi"]);
groups.push(["qdywgafzmn", "ufobhixk"]);
groups.push(["r", "q"]);
groups.push(["alndhupswj", "npwlua", "nlueapw", "npalwu", "lawnpu"]);
groups.push(["obsxpclziwauf", "fcsjxiblwuotzp", "spcvbiwfzdxulo", "ulfwpiczosbxd"]);
groups.push(["hknftpgaey", "typoqgehn"]);
groups.push(["tyhzpoejxdl", "xoejpdztlhyk", "hreinoyjvtbdzmfqlp", "otjyedpzlh", "zdoywjeltshp"]);
groups.push(["n", "b", "b", "b", "b"]);
groups.push(["kvupfreobljsmw", "sukjromplvfwe", "rdwhpkjvqcemlosfi", "pvmblwsfkexroj", "eokvlrmsujwpgtf"]);
groups.push(["wiqs", "l", "j", "j", "h"]);
groups.push(["jx", "jxc", "jxr"]);
groups.push(["tzv", "tzv"]);
groups.push(["aqe", "qan", "avqs", "asqcm", "glpayuq"]);
groups.push(["hncexlkpjbdmoftag", "pfbxckmdantlogh"]);
groups.push(["ocsdtg", "sdgtm", "sdgt", "tdsg"]);
groups.push(["jfioeacnqv", "oqafnicjev", "veijfnocaq"]);
groups.push(["xfmnhbpljcg", "cmlfhbjxengs", "xnmbjhlgfc"]);
groups.push(["vcn", "kvc", "cv", "cv", "cvm"]);
groups.push(["wodgjfls", "owdgfq", "niogfwtd", "vcdgfwo", "mgwyfod"]);
groups.push(["ozhwa", "kotuedjcql"]);
groups.push(["kw", "kw", "kw", "kw"]);
groups.push(["sufmi", "rmsuf", "jumfpeogs", "tmfsbu"]);
groups.push(["siadk", "mijcgosk", "ski", "isk"]);
groups.push(["kplwzh", "hzpkwl", "lwzkph", "wzhkpl"]);
groups.push(["yot", "y", "sy"]);
groups.push(["lz", "fl", "lf"]);
groups.push(["kexljydcihonwtgumfsrz", "iuywlcxomsedjnhztgrf", "wtorjgfuxsmlyecdnhbzi", "tczliugorhdjsfyenamxw", "zklniaxyujdcwtrhgsmfoe"]);
groups.push(["juzqtibn", "qijvuzgtnf", "nqxziutj", "qitonjzw", "zqtnjgbis"]);
groups.push(["tuqygv", "gutvqy", "tvuqyg"]);
groups.push(["plzqmthysawexgvnr", "ptvxasryleqmgznwh", "htlgnqexsmwpvyiraz"]);
groups.push(["hizrfynjmqceg", "bplsuoydv"]);
groups.push(["bptjc", "jcbtp"]);
groups.push(["qedcultavjwizxnkob", "bokndqcuivwtxlaezfj", "qazlvsjexikwbcudont"]);
groups.push(["vgihxmquktcrywpzj", "kpujwxfrgqmzlyihct", "domjarxitczhwnqugkyp"]);
groups.push(["wilctjzq", "ouwylicgkxvsha", "npbwlric", "liwqc", "qclpidbnw"]);
groups.push(["gbvpdkxclfejtaoq", "elabncgfkjdvxop"]);
groups.push(["vfi", "vpif", "ivf", "vif"]);
groups.push(["hvjzxebtqsfwpia", "gvaxyiwfkcru"]);
groups.push(["hzrg", "lz", "fqz", "az", "qabzpyi"]);
groups.push(["redfpogvxc", "zeyh", "ainye", "tlyzeu", "alsemu"]);
groups.push(["gwph", "gpw", "ywgp", "gwp"]);
groups.push(["fjkhnmuwtxialyo", "tjuolfnkamwxy"]);
groups.push(["umrdifo", "mrfodtuix", "jkruohmfdi", "ufikzrmdo"]);
groups.push(["blioreudh", "brfiaheulndgy"]);
groups.push(["ywstjalubez", "wbsautezj", "usebjtawz"]);
groups.push(["gatfpyjoznwh", "oztwypanjghf", "nzgojwfphyta", "yjhpgfotwzna"]);
groups.push(["metqoknri", "kqmtnwerofi", "qtkohjnmeir", "qmkrefiton"]);
groups.push(["xdgrbua", "bwdukoghcrxln", "euvxgrdbi", "vusgbrxd"]);
groups.push(["rovayxgkqshzi", "olgxhutwzsikbecqdajyp", "ksrahngzyiqxo", "vosgzynxqaifkh", "soqzigyxakh"]);
groups.push(["fopjqgdmhtbv", "qbvl", "lbvqy", "buwvq", "bcuqv"]);
groups.push(["feyvazrnows", "waynzeorfs", "sorafznewy"]);
groups.push(["jpohmywkvqextsd", "ahtvoxpumsedq", "qbgtpoecsnlmxfirvh"]);
groups.push(["uic", "ij", "ixgp", "alzehimdvybf", "tkgi"]);
groups.push(["fpjubodeznsqyxkwami", "anuymqskowpedbifzjx", "oubjpwznfdxemiyqska"]);
groups.push(["uhzd", "uzhd", "dhuz", "uhdgz", "zdhu"]);
groups.push(["bsyituhq", "rbjahg"]);
groups.push(["xszkrj", "znhjrsx", "jzrptkxs", "mlzrjbxsyoq", "unjxrzsk"]);
groups.push(["rmyilhnkdqjpfceogzu", "oegpdtmkwuvfal", "budoxkfpglem"]);
groups.push(["xekshpotfzlcmuiwgj", "sauekziobrthjgxfcpwl", "eifjhkwgpcltsxozvu", "okenjhgscxqfuzwtpl", "uhcjxzowitsdlegpkf"]);
groups.push(["kzwdconulqtrvihsgp", "qwmhutnpyrsxbvgzokdeicl"]);
groups.push(["x", "x", "i"]);
groups.push(["umvbcenh", "egun", "tnue", "ktuen", "wgneu"]);
groups.push(["wysximljeua", "uiwxleymsja", "iemlyxjsawu"]);
groups.push(["r", "wt"]);
groups.push(["hcvos", "xv"]);
groups.push(["enzmuaxc", "jcdnvzam", "nltvobeaym", "mfnahipgswr"]);
groups.push(["hsnmlpkujoigaftc", "fslotjmpghacnkiu", "cbfjlkohumapsngt", "lsutoajknfpgchmi"]);
groups.push(["xisn", "insxw", "nixs"]);
groups.push(["eunflkcda", "gcnxefzlud", "lspcndufea", "onwjutcefdlm"]);
groups.push(["hrivmxpatkgd", "hdmxigtprakv", "dvpmgcrthkiax", "gkdraxithpmv", "rvmutdbixpklehga"]);
groups.push(["elmdxqwn", "mqlwedn", "mwnleqd", "qldwnem", "qemlwdn"]);
groups.push(["wpjfrlqbs", "vwqjlsfbr", "srqwbjflk", "fpjlqwsrb"]);
groups.push(["u", "j", "l", "w", "l"]);
groups.push(["kr", "rk", "kr", "rkd", "rk"]);
groups.push(["irpxjsmqgf", "bhqpendrjfc", "pmwryfjql", "mpfqjryux"]);
groups.push(["kjgheiqcox", "iklufxgcjeh", "gynvizspjhmebakxt"]);
groups.push(["udwlimhqsorbpeynctva", "qzxobjpsckyfmtr"]);
groups.push(["xqyjwueda", "juehakzxygq", "nexjlqumsyra"]);
groups.push(["mvsyaec", "xalsmwvyr", "msyuav", "awsmvy"]);
groups.push(["tyfrcibenxdvgum", "diptcfwuroegnlvx"]);
groups.push(["c", "i", "g", "arelmvpoz", "n"]);
groups.push(["q", "pq", "q", "asq"]);
groups.push(["oxrchtjsekpw", "twoesdckuhnpxml", "xkovyetpwschai", "tsjwecqzxhgfopk", "fspcxrtdoewhk"]);
groups.push(["urjh", "njd"]);
groups.push(["ygo", "syog", "gfoyr"]);
groups.push(["lrvkw", "dwarkyg", "cphkiqfjsut", "xk", "vwk"]);
groups.push(["chlog", "wughvb", "cngh", "hlgc"]);
groups.push(["hlu", "luh"]);
groups.push(["tgfsbj", "btgjf"]);
groups.push(["yflqdgp", "dqpflg", "dlgpfq", "qgdlfp", "lfgdpumq"]);
groups.push(["dybxtrizvhcksalqpungfwmeoj", "lpotsjiaydfbqwzruxhemcnvgk", "qletwyopaivjkgcbszrudmxfnh"]);
groups.push(["rowgvahemlyjkbupxct", "jrewbpmktlvxaouhcy"]);
groups.push(["soerhzknbijd", "oekgznidsrhj", "oihrkaduezsnjf"]);
groups.push(["axthin", "ojhtxa", "tnahxv"]);
groups.push(["t", "f", "cv"]);
groups.push(["yjkatqum", "eksumriab", "wksmhvuaeb"]);
groups.push(["wz", "w", "wfb"]);
groups.push(["ruvglckjpomqthy", "afjbuxevlqiwog"]);
groups.push(["zpyfolacrnqgvhksmjdeuw", "ebctoamjkusdrnpyxwih"]);
groups.push(["fxs", "sfirlxm", "swfx"]);
groups.push(["imftqohzgjcpdlsrebxuv", "agptlnyxujfzwkoqmdh"]);
groups.push(["mkbqsgaxojivpyrzwtn", "svhgocwbazkyqtxrfnlmu", "nozrjkdabxwitqmvegys"]);
groups.push(["tuzmyvqgnsekbwo", "vmqgbozknywetus", "ymsnwuqoezktgvb", "euzowmbqtskgynv", "uzesoybkngwmqtv"]);
groups.push(["khgx", "xhz", "aclrne"]);
groups.push(["kq", "qk", "qk"]);
groups.push(["i", "gmf", "dh", "owqjb"]);
groups.push(["pstycjadezlbnqwxrig", "rbhdpqysicgnlwa", "ryhibaqwdclpngs", "npdcyqsbrhawiglko", "cbsdiwpnqgylra"]);
groups.push(["quvsagtxw", "uatvcx", "vutax"]);
groups.push(["ndbrlpzxasmto", "sdbxjyrofatqlpmnz", "bolmatxdszpnr", "wplobctzsmxdnra"]);
groups.push(["boxmgljp", "xfap"]);
groups.push(["cndeqvy", "mzneys", "eyn", "sieyn", "eynm"]);
groups.push(["kbuwp", "bqpkh"]);
groups.push(["ljngohfvtpdmw", "iwctogfnmvuzlhd"]);
groups.push(["napvy", "gaczoidwybm", "ysaet"]);
groups.push(["wrnixgyv", "wnrxgvyi", "vxirywgn", "iwryxvng", "gvwinxyr"]);
groups.push(["ygtbiqfuornlx", "ieuwpgzxhbo", "vubi"]);
groups.push(["ohxbkqgsj", "qalpsfmiwtzyrdc"]);
groups.push(["fyakzqidcpswn", "qwkizfdpyacn"]);
groups.push(["lxf", "ifxl", "njuxfl"]);
groups.push(["yxqzebvsgpwl", "mnjcftohyi", "adycurkmo"]);
groups.push(["nxdfptvebg", "swjzqh", "kwyasj", "oljz"]);
groups.push(["lrzunheqgjvcs", "kiqshjmgdvuz"]);
groups.push(["feyljcgrqmsdbz", "qsgnumzhiayfbcle", "pcwfstmkvgeqloxy"]);
groups.push(["qnwcftx", "hyewofcl", "cwhfi", "clfehw"]);
groups.push(["kjuebdvpgqs", "ahpubjyske", "zksejxbuwp", "juboekswp"]);
groups.push(["u", "bcytf"]);
groups.push(["rpvshwmn", "djnshvmwr", "wrshnvm"]);
groups.push(["itpduvwechnrk", "ntirkpvdelcuhws", "vrcktepindwuqhf"]);
groups.push(["q", "q", "q"]);
groups.push(["mzhrygf", "zhfygmr", "msofhrygz", "rqfymhzg", "ygfmhqrz"]);
groups.push(["nwbpshv", "twspladobu", "hzinpwbqs"]);
groups.push(["c", "c", "xecuy", "c", "c"]);
groups.push(["y", "y", "o", "y"]);
groups.push(["qauijgxfhbztlpvecrk", "ljhcamkegxbqyptnzrfoviu", "ejibuzlprhtcxaqfgvk", "biczvdhgqlxrktjafuep", "hpsxgwujqakbrltzevcfi"]);
groups.push(["cmfryo", "froyc", "dcofgye"]);
groups.push(["dcrbjnza", "jdirzacb", "bzrdacj", "cbadrzj"]);
groups.push(["fnjryzvtxlsdioepm", "ldxfzcjtovyisepbmrn", "mtoxdilwfrvjespyzn"]);
groups.push(["omqxjypgin", "bcrdezl", "vflwkrzt"]);
groups.push(["dkabj", "ntwpy", "jb"]);
groups.push(["krjawyexhnlmcspizoufgt", "ryebdifmlhwxgasvkoqjztcn"]);
groups.push(["lrctmfu", "clzrmtfu"]);
groups.push(["ivagzecmwyl", "xgkrojtfc"]);
groups.push(["bsalmjthvwgxirpqcnyue", "ymtqgcsjrxnvaepfhwiolb"]);
groups.push(["tgwkeapzjo", "oewgpzjkati", "hejoalxzmgprkwb", "nojwgazkpet", "asoedjkzgpw"]);
groups.push(["zpjncustlhb", "nswvlbtzphcjf", "pzjlnebcmtfhs", "cljbzfinthkps", "aoplbczxrstjhyd"]);
groups.push(["ulvwcxg", "bsvqwelud", "dmxwioulv", "nuwqvlb", "ulwvpjft"]);
groups.push(["fmlvprndhxa", "hmapdxvrnfl", "npavmrgfxhdl", "mhlanxrdpvf"]);
groups.push(["vfgwzy", "yjgfzqxovu", "wzbyfgvj", "rvfkpdslzthngmyice", "qfyzxavg"]);
groups.push(["hzfjbs", "sjhzb", "nhsjmzgw"]);
groups.push(["gmtvalyn", "igtmvlyn", "ymgtvn", "gueftonmvxcy"]);
groups.push(["j", "jge", "jm", "qwbj", "j"]);
groups.push(["oftpvnykgdxrels", "nrvksolftepdxy", "xopknvbwltdeysrf", "dkexlnhprtysfov"]);
groups.push(["gwcvu", "wuec", "cuw", "wcvu", "cuw"]);
groups.push(["cndywt", "ntdwcy", "cqtyngd"]);
groups.push(["noayvkcdsu", "yaedfcjozs"]);
groups.push(["rzfhlitjvwdnp", "hzxntilvwfprjd", "ljinfmrdtpvwzh"]);
groups.push(["zylgudcfbxprwaqokmtjnsi", "bosdnqlyjxgwkmrutcifpaz", "kqwuipcfsdnzagojrxymbtl", "wbixmynrjkgoaztslupqfcd", "bnearosgumfildkjtcyxpqzw"]);
groups.push(["fherd", "dfreh", "hredf", "dfrhe"]);
groups.push(["aysber", "se", "sze", "seo"]);
groups.push(["cjofniwx", "zxieaocf", "uipxrgodcf", "bsjtveoizwfxc", "jfcoxinzt"]);
groups.push(["wzoegvhldfibmcj", "ohurkdjcvifbazew", "sxqzjwioefhbdvc"]);
groups.push(["ifrstw", "btkqyfscx", "lgvedonzjphu"]);
groups.push(["buw", "wubhop", "zrfwsbu", "ucwhb", "wbcu"]);
groups.push(["bdpn", "wdpnb", "dpbn", "bdpn", "padnb"]);
groups.push(["ukgziahpfyq", "etvsrnjilx"]);
groups.push(["w", "w", "w"]);
groups.push(["kdjrc", "kjcd", "cqpjidh", "tjdmc"]);
groups.push(["fihjqetkprmbgzl", "hgjrtqiefompbzkld", "amqipgtlebkjrfzh", "elgqwbmpkjvzfihrt", "mfjcpszthlirkbeqg"]);
groups.push(["vpfmytuob", "bftvyoup", "zobynvutpf", "uypbftov", "ubotpfyv"]);
groups.push(["t", "k", "k", "t", "po"]);
groups.push(["he", "eh", "he", "he", "he"]);
groups.push(["jwkorfnpqhlxvbziedcasm", "vzsfxlkqarmhnjpidcboe", "lpzkacexvthbfrojsinqmd", "mcnzqiekusafdpvoylxbrhj"]);
groups.push(["doqcnfpshrgwxkjubyval", "bdjuhgnlvpkcrfawqsyx", "pnasqwryjfvduhbtcklxg"]);
groups.push(["pyba", "bacs", "autxkrgm", "bwfa", "eiola"]);
groups.push(["bhfrtklucjpinqoexmdgz", "orchqmilekjbupzfgdnt", "klhbtnzuomxegdivcjqfp", "itfgdqualjokhnbspzemc"]);
groups.push(["kjz", "jkoz", "kzj", "zkj"]);
groups.push(["w", "v"]);
groups.push(["qfytlkjconpsw", "ltfpyjcskqown", "wqsfkcoyjpltn", "nckhwtpofjyslq"]);
groups.push(["bvsqmnyjkur", "qrukybsjvmn", "bnkyvusrmqj", "ykqumnrsvjb", "bjvyursmnkq"]);
groups.push(["ykmabugfjtqdwpevrzx", "maezkwtbvxdqupojfyg", "mqyvxasgkezudpwtjfb", "fumzpyxtdwqjgabveks"]);
groups.push(["wcntqs", "sntbcwq"]);
groups.push(["tywbgnf", "gbuynfcrt", "sygnrufbt", "gabfiznmhtpy", "ltbfngy"]);
groups.push(["ngkfqmv", "gnqavfm", "qgmnavf", "qgmvfn", "gvmqnf"]);
groups.push(["w", "a", "id", "uj"]);
groups.push(["zvqypkadneblrf", "vaeqpldzkfrbny", "friaqcvdsexyhbnlp", "ezflrdqkbnypva"]);
groups.push(["tlhucpwyzrex", "lcpwrhqe", "pkehrwlc", "ewcpfhrl", "chlpwerm"]);
groups.push(["wrtljgy", "ygqjlw"]);
groups.push(["jvygmx", "qxmyg", "myxgqr", "gmyx", "xmgqy"]);
groups.push(["nvmufjzsb", "amnzthf"]);
groups.push(["ujgebphztf", "hezupfjbt", "zjxfubelsphdt", "pthbzefju", "bzfuhpjte"]);
groups.push(["xhfj", "fhgdx", "uifoxqwh", "hnexaylbfk", "fphux"]);
groups.push(["jiqhofdlwkgas", "wftrvupnze", "bwfmu", "muenywfct"]);
groups.push(["mzrf", "gkxsqcwo"]);
groups.push(["uaewm", "ewmua", "muaew", "umwea", "awmue"]);
groups.push(["njduohc", "hndcjou", "chndoju"]);
groups.push(["sqrdgapl", "dqgpasrl", "gdqplsra"]);
groups.push(["aunzfm", "munah"]);
groups.push(["paqvw", "qp", "fqs", "vpq", "qwp"]);
groups.push(["gfmbcvriax", "dlcmbwvfeyp", "bixcrmvaf"]);
groups.push(["uczi", "bzi", "izwrb", "wiz", "zi"]);
groups.push(["s", "j"]);
groups.push(["khqea", "qehxka"]);
groups.push(["mj", "dj", "j"]);
groups.push(["uibwnrakt", "torn", "rtevnlh"]);
groups.push(["ghwzt", "tghz", "gzht", "zvgcuqh", "hzg"]);
groups.push(["t", "t", "t", "mt", "t"]);
groups.push(["cszjtfdulmprbawqkexv", "fbwnhigouy"]);
groups.push(["eq", "feq", "eqo"]);
groups.push(["tyvjnf", "tfnsvj", "bftngjkv"]);
groups.push(["bpxwhjcmogyq", "tnfezpk"]);
groups.push(["as", "as", "as", "as"]);
groups.push(["ybqntwcfld", "qytlfbdcwn", "wtcqdbfnyl", "ltywfcbdqn"]);
groups.push(["fzshuktvwp", "ukrbmxvyelindgq"]);
groups.push(["fjoweph", "tbvfmscxe", "aofzek"]);
groups.push(["axjyiwok", "mviqawyxutnjbd", "xawiyjc", "jhwziyxa"]);
groups.push(["xgwq", "mohv", "w", "ertbzsjk", "udf"]);
groups.push(["crozvbt", "btzvroc"]);
groups.push(["tvnqzmiouaeslxyw", "taymuelowxqsviz"]);
groups.push(["jv", "xjwv"]);
groups.push(["npohlyejtkbuvca", "ytlokvaebhucjn", "kutvyngeclaohbj"]);
groups.push(["nbvwheisoxpa", "evlntxsmowighb", "kwnaviojeshxb", "owvphiexbfns", "jwbnheyqvsxio"]);
groups.push(["fkvcteqsgd", "bzcftexmvwohp"]);
groups.push(["srwf", "frnwsj", "swafr", "rswf", "fwrs"]);
groups.push(["iovjntkewabzumpxryqdfcgh", "gskjxpotluzqycrifwbdne"]);
groups.push(["luokigf", "nuherolcyiqxam", "ugiobls", "lwtduoi", "ligwou"]);
groups.push(["gbfiqhdmpwjo", "fwdqmbpjhig", "bwjdrqhmfpaig"]);
groups.push(["ulzyiqamhxvpgbj", "ftdrcnewhgszp"]);
groups.push(["oakzwdjupviqn", "rgdelufhymik"]);
groups.push(["clxpqaryjkt", "qycujtlpxa", "xulpctqjya", "ucjlatypqx"]);
groups.push(["zckf", "fvek"]);
groups.push(["zncuxhaeli", "nalhizkcuex", "xaceinzulh", "acuixzelhn", "aczqnxhulie"]);
groups.push(["wrzuljei", "lnremi", "hrikyacgf"]);
groups.push(["odnqfwpugy", "ptlwnydoqhmf", "fyovwdpqn", "oznwbfpykdqecs"]);
groups.push(["gchqvjlypom", "kcwtvxdoiu", "cvwzfkoe"]);
groups.push(["xw", "wmzx"]);
groups.push(["mfihkroznydqp", "kfpzqdinhrovym", "hnrzqpyfdmiok", "rtqdphyfonizmk", "fimnyphzdrkqo"]);
groups.push(["nsbiyukormjhdclvaptw", "bcrsitpxdklunmajvhwyo", "dktbwvmfyrlhisjnacuop", "ztcdupvhgjaboqinsylrmkw", "clovapfbyhsukwmdtrjni"]);
groups.push(["bgq", "gq", "egqk", "qxg", "wfjulqgzo"]);
groups.push(["foc", "ocf", "fco", "vofc", "fco"]);
groups.push(["oitbdfympxjw", "jfbowrptimh", "ftoimpbwj", "ktufiojpwbm", "yiwbjpmfout"]);
groups.push(["adznvugpirxyfwkeml", "uyefgikmdxrznvwap", "gwxdmkyiavrpfnzeu"]);
groups.push(["mi", "mi", "mi", "im", "mi"]);
groups.push(["redwqtcgofk", "apuhyrsdkbf", "kfsrnuvmhbxd", "rijdfk"]);
groups.push(["ekxfaqmhbptj", "efayqhb", "wqfuhabecy", "qbfheac", "eafbuhoq"]);
groups.push(["yxzarums", "yzqforucaxs"]);
groups.push(["cwlqfxdrmp", "dxipzcambwoveglk", "twhmqspdcxl", "cjwxpdsumnrfly"]);
groups.push(["zxdgqawjntukphsfbievrloc", "twslhaqxoenmzrfybckdijv"]);
groups.push(["abzlckqrnsgfijdtvy", "cgdteqlkbzinyrvasjf", "dikaynsgrflzjcqbvt"]);
groups.push(["kptwqavin", "wkviqxptn", "swpvmgnqbiktl", "qpvdtkuiwn", "vrjikpytnqewo"]);
groups.push(["evjqxlktmroh", "tjmelkoxrq", "jlekomtqxr", "molerxtkjq", "njxkltqermo"]);
groups.push(["wkacmijsrponf", "rwvpcsu", "wzyplbstrc", "cdhwylserpx"]);
groups.push(["jocqfpgmy", "qjfpgmc", "cfpqjmg", "zcqjhfpgme", "gjcmfqp"]);
groups.push(["evchkgpdqourmtlzbs", "plvdteqmjzurk"]);
groups.push(["fgwbxpihnrz", "cdktfvmljbeiwr"]);
groups.push(["mhdcqiaswfpeyogjkbtzvxn", "xdyifpqzevknmcoathjsgwb", "ndvlyzretgkqbswmpxcjiafho", "mstqzycowgjhbnaxepvkidf", "aygkezvcxowbjfqithmnspd"]);
groups.push(["qdmetvs", "dmslt"]);
groups.push(["vaxsreikfulbohwc", "avxeiolbkhcswrfu"]);
groups.push(["wiukdyzvenogj", "nouyvkdrwagij", "yewvhtjkgndqoiu", "dnvfswojigkuey"]);
groups.push(["gnuatzydv", "amzvnutgy", "cvuengaywtz", "zmdgvpyntaohu", "oayngzstxfhvu"]);
groups.push(["jed", "jefn", "mjkch"]);
groups.push(["uojxteazifrsch", "kaurlehco", "ceuaohr", "chkauwero", "hacuekrno"]);
groups.push(["ygopsthm", "fzduxalqjk"]);
groups.push(["hkdu", "khdu", "dhpuk", "duhk", "hudk"]);
groups.push(["mtoqrcgzxuavek", "mntwviorack", "frtmkyaocv"]);
groups.push(["pstolmvrqkwxz", "rsipltjxqnmagvwuk", "kspmrxtlyqebwv", "twqmlexkprvsf"]);
groups.push(["lacfoveut", "ocafve", "acvjofbresx"]);
groups.push(["ohgclnjdz", "ejsyzdolg", "riqbwtkjfdgl", "zdgjyvxhl", "jldaug"]);
groups.push(["weqdtuvmfnygaskb", "lsugyqfvnkebmj"]);
groups.push(["zdcpefjvaly", "azcjfvdelpy", "tayfqbdzlcepjvk", "jedazcvfply", "zdplceafyjv"]);
groups.push(["jw", "j", "chj"]);
groups.push(["cda", "ja", "yaxn", "ja"]);
groups.push(["cfrqx", "vlju", "v", "untv", "uy"]);
groups.push(["cowiekfanus", "wjgdupicnsfr"]);
groups.push(["sh", "foywprquj"]);
groups.push(["b", "u"]);
groups.push(["dhezbkx", "nwyvlisjpr", "jqcotumgfa"]);
groups.push(["eoh", "oe", "oe", "xoe"]);
groups.push(["cjdhmxuyg", "gjmxhdyuc", "huedcxymgj", "dugjxyhcm"]);
groups.push(["srctb", "crstb", "bvlezstprc", "trbcs", "rctsbj"]);
groups.push(["fbdvkeltq", "lotm", "nojtl", "tl", "rtl"]);
groups.push(["nryhkvetf", "xkhrtnfycv", "rhtvfynk", "rfnvhtky"]);
groups.push(["qabfkzotdyjieghumplxs", "sqtuhaxjgdkfliymeozbpv", "lqgpjmeofdkaxuhtsyizb", "usbyhegwtzlpkxidjqfmoa", "pyjdkigtbafqohmsxuelz"]);
groups.push(["zolurkepnsm", "ymplgvtrond"]);
groups.push(["skgedcfiqz", "gfqzsckdei", "ckgsdeqzif"]);
groups.push(["uazvbnlgtiscdmfjreq", "iszgbjrnqfdtveauclm", "nsilqzuamtgjcbrdfev", "zmquiblfsgrvjetdcan"]);
groups.push(["faghxbimzvkcqsy", "ikzagfmxbqvycsh", "fbsxakqcghymviz"]);
groups.push(["ztvufgy", "vzftgey"]);
groups.push(["g", "g", "g", "kg", "g"]);
groups.push(["cdihy", "tsb"]);
groups.push(["ibl", "l"]);
groups.push(["cpdatberqxhugms", "rgaxceqptsmhdbu", "emcrsdbhtxqapgu", "drechgxtmapbqus", "xqdpcmshbgeatru"]);
groups.push(["f", "poj", "f", "z", "u"]);
groups.push(["ezagw", "usolp"]);
groups.push(["jagq", "qgajs", "gjasqk", "jqagm"]);
groups.push(["josgetlqimcdxruyazvf", "riclqagoskmwuyxdetpfjz", "surlmyegxdnactoqzifj", "lcydfrxusmvqjagzbeiot", "lcrsoyavzubgimfeqxtdj"]);
groups.push(["qevptljankmhs", "qmjukehpsatvo", "vzmsaqgwetjphkr"]);
groups.push(["e", "s", "m", "iaxgyd"]);
groups.push(["isn", "nis", "uisn", "nis", "sni"]);
groups.push(["bvjza", "bv", "bdv", "dvb"]);
groups.push(["betqjy", "nqbetj", "tjvqe", "hqkraxcp"]);
groups.push(["dbhzkpt", "pzdhtk", "thdkzp", "pzthkd"]);
groups.push(["gyrfsaox", "xafgkysh", "sgxfapy", "gmjuitsbcafyxq", "xsgafy"]);
groups.push(["mvenpfxkwc", "wpstxfev"]);
groups.push(["rftiyogqvue", "gucfjnskpxzqoba"]);
groups.push(["htoyrpesdvnbg", "rohysvgpetn"]);
groups.push(["yxntbv", "vbxynt", "vbyuxqn", "ynbfxtav", "myxnbdv"]);
groups.push(["v", "v", "vs", "fv"]);
groups.push(["exodvrya", "vomacygxduis", "wajloydxvp", "fyxokvadj"]);
groups.push(["qxipfbwly", "wpxtlfcibyq", "pylqfibwx", "lxpyqbifw"]);
groups.push(["bydioqrcftehkaznlvgsx", "ypklfesavizqxgohmtnbcrd", "dagnriqsexyvflcbtkohz"]);
groups.push(["uhsjxyfniqbvw", "auzbviynqgsjxwf", "vfjsbqxurwadinlyt", "yevixlqfnsbojwu"]);
groups.push(["y", "y", "y", "zh", "d"]);
groups.push(["etyjmxdwkfosbqzhigrpacuvn", "uktqciyfbnrosaedlzgpwhjvmx"]);
groups.push(["w", "wim", "w", "w"]);
groups.push(["zlkgwbseno", "zqngksb", "zgnbsk", "gobztsnqkp", "kcainfghdxzyubmvsjr"]);
groups.push(["qywhjzxlarbutdnvimc", "vrbyjhtqlxmcnzui", "tljuhyrnqbpzvxcm", "tezubhyjxnqlfrvmc", "quhxlzrvbmnctjy"]);
groups.push(["mwqlo", "xqonftwmacj", "gwrodqum", "imwoqre"]);
groups.push(["q", "q", "zq"]);
groups.push(["tgnvlhc", "nhcvtgl", "clvhgtn", "chvlntg", "cnhvdgmbftlq"]);
groups.push(["pmfreuoyzdlhsgvcwb", "exahjnytqcgk"]);
groups.push(["ayglbtwcxiopqh", "ifxvqhtpbyowa", "uqyhwaimtfkbxvpjdo"]);
groups.push(["mcwt", "tdrckp", "ct"]);
groups.push(["hskjp", "fihpjksl"]);
groups.push(["rlvixasmotuqcye", "tcyvolauqxsmeri", "tpsvmceoailuyxrq"]);
groups.push(["ckvego", "ecgokv"]);
groups.push(["bu", "b", "mjb", "by", "b"]);
groups.push(["odsbf", "odbfs", "fsdbo", "bsdfo", "obsfd"]);
groups.push(["tofgjlhuvmyzcnd", "uyljsxtdpbewoqnvg"]);
groups.push(["bcfgaorvwqnmdup", "rcvxaunwmdpszjfqgyob", "fcrmabgqdwonpvue"]);
groups.push(["z", "h"]);
groups.push(["cgbpk", "uyzbop"]);
groups.push(["ptzqufrekvilxwmgn", "qigueptylvckrnxzfhmd", "nrxlezgmqoivkfupt", "bpexuzmltqifgvrkns", "aeglzqrbotpkvximfjnu"]);
groups.push(["cradozehb", "dhslfoqrezca"]);
groups.push(["mpzkgcnbot", "cemogtbpzn", "lozwngjtbpcm", "znlwpbgtmco"]);
groups.push(["lodrywvcxjgp", "jxgyclpwrvdo", "xrcpljogyvdw", "pygvwrodcjxl"]);
groups.push(["bfrmhpiuwxznslcdqke", "wikulxhrfdnbsmeqzc", "dnhurewbcxsqzifkml", "mibcendxwshkulrzqf", "frnkcszlqmwbxiudeh"]);
groups.push(["pny", "ypd", "pyg"]);
groups.push(["msgwzuoydtaxkpqhbj", "aknbtivsjgupozme"]);
groups.push(["uizgp", "gpizau", "gpzxu", "aupzgi"]);
groups.push(["zkohbpscea", "losacbgm", "bogytalcs", "owtysabnc"]);
groups.push(["swjkz", "kszjw", "zksqwj"]);
groups.push(["m", "mdtqyw", "bsnlkfjprv", "demi", "itdao"]);
groups.push(["gkwqdnaosmvyrbz", "brpomnqgk", "qotikclbrnemg", "rkgqomnpb"]);
groups.push(["pyoclwjxrmibhgaqu", "laymqhioubrpgcwxj", "qbhuypxogwrjlamci", "muicbghjwoyplqarx"]);
groups.push(["xfut", "utfx", "vfztuhxd", "tuyxf", "uxtf"]);
groups.push(["foabejk", "wugejvkoca", "qjazoxli", "ahojt"]);
groups.push(["pqzk", "zrkp", "adihs"]);
groups.push(["xqcigryhkevpfmutwanlds", "ecdqztaxonbiprugfmk", "rqnpatukmefgoxdic"]);
groups.push(["ewtfcyagsizj", "wyfgtviej", "stejyfigrw", "ctgajeyfwki", "jdbeoyqhitufglpnxw"]);
groups.push(["krmsglcbi", "kgbmilc", "blkgicm", "inxkcqglohwmb", "kiblcmg"]);
groups.push(["tubipv", "ejwrgfqci", "nishoxzp"]);
groups.push(["hoqxjktugmrclzywedi", "utgiceynvphszkmodrl", "cdbihmzolufgea"]);
groups.push(["ichtmwx", "cwmuvixtb"]);
groups.push(["qihgfsxnydtwcrkoeamupzvb", "goizemfwhaxcdtknubypqsrv", "ovshacfrekugzbwipymtxqnd", "rqgntzkwxihovbedpsfumacy", "oryitqesazgnckxhdvfpwmub"]);
groups.push(["qafihpdwy", "saikmrbxecjgnvoy"]);
groups.push(["devizumtxonjhrkpq", "zidmnptujoqhkvxre", "gqjmkuohnrtxziedvp", "pqoixumtdvrzjkhnbe"]);
groups.push(["fmtbrhsynpkxu", "npsmubhyktfrx", "sbhyxkumnprft", "nhpusmfkbrxty"]);
groups.push(["je", "x"]);
groups.push(["dagmxqbfvz", "sxkur", "xkptl", "jixu"]);
groups.push(["e", "e", "hits", "q"]);
groups.push(["tko", "qtkhoy", "topk", "otk"]);
groups.push(["r", "erh", "r", "r", "r"]);
groups.push(["agrkjyfcw", "ktryaw", "whyirak"]);
groups.push(["pgzhswrvxumqlai", "skgvdxwp", "pgvjxdnws", "wpnkgjxvs"]);
groups.push(["risotwzapm", "eytfvlx"]);
groups.push(["ocdw", "dowlc"]);
groups.push(["mlspy", "ylpsmn"]);
groups.push(["rxf", "xfr"]);
groups.push(["jaecdxiptnzrlomgwuqyhvf", "mexsutcqaviywjzhgnropdl", "imeufcjtvwyonxpzardlgqh"]);
groups.push(["dxqtwsvaernygbu", "unceigjraxzbqwkvd"]);
groups.push(["skogcitreyx", "xewqysmchvikduzj", "ycxebsrlki"]);
groups.push(["gqdyaw", "skxclpvq"]);
groups.push(["uja", "kaju", "jau"]);
groups.push(["xnjhqlyvgod", "odlvnyxf", "yndolkxv", "vnldxyo"]);
groups.push(["ksmuqpily", "oanrztfwjxvu"]);
groups.push(["gulobnahfmjdpkrqvecsz", "lnymgsxrcpheqobjdavkf"]);
groups.push(["mgtdqzrebiswvcfnlopaukh", "nbomqafeulrtvigdcpwszk", "ginlmsraopdukxftbewqzcv", "iamtqzvowldfnuscpkrgeb"]);
groups.push(["ipkonymxsvhjcu", "iypevgxdhcnl", "xhcinvply"]);
groups.push(["d", "qbwhp", "r", "r"]);
groups.push(["hrdmq", "qxld", "hcqd", "dqfc"]);
groups.push(["pqrgvxtzcbmws", "xomdqytbiwzr"]);
groups.push(["eo", "eo", "oe", "oe", "oe"]);
groups.push(["dwgmk", "mrwjdgk", "gwmdk"]);
groups.push(["nspfzvdhocirwyebma", "bfdcnzoswyermahivp", "minwdycaephzsbvrfo"]);
groups.push(["iydcwfzaxlnret", "qlusgcyk", "lgcyjs"]);
groups.push(["tmjsecngzxfiq", "vhzbyoedfu"]);
groups.push(["o", "s", "s"]);
groups.push(["ubfrgyp", "vybfpkrg", "erfybg", "nbgyrf", "zfwrgby"]);
groups.push(["gjnbfartdoiem", "ajbtgermdqnfio", "mfijcthadgnobuew"]);


var i, j = groups.length;
var total=0;

for(i=0;i<j;i++) {
  var gr=groups[i];
  var n, k=gr.length;
  var dd={}, sttl=0;
  for(n=0; n<k; n++) {
    var line=gr[n];
    var x, y=line.length;
    for(x=0; x<y; x++) {
      dd[line.substr(x,1)]=line.substr(x,1);
    }
  }
  var count=Object.keys(dd).length;
  // console.log(i,count,dd);
  total+=count;
}
console.log("Total:", total);
