var lines = [];
lines.push("pale turquoise bags contain 3 muted cyan bags, 5 striped teal bags.");
lines.push("light tan bags contain 5 posh tomato bags.");
lines.push("shiny coral bags contain 2 muted bronze bags.");
lines.push("wavy orange bags contain 4 faded tomato bags.");
lines.push("light plum bags contain 3 drab orange bags, 4 faded coral bags.");
lines.push("pale purple bags contain 5 bright crimson bags.");
lines.push("bright blue bags contain 1 pale beige bag, 1 light teal bag.");
lines.push("pale bronze bags contain 1 dotted salmon bag, 1 striped blue bag, 2 clear tan bags.");
lines.push("muted maroon bags contain 5 pale crimson bags.");
lines.push("clear lavender bags contain 4 vibrant black bags, 2 posh red bags.");
lines.push("pale cyan bags contain 4 light olive bags, 2 dull lime bags, 4 faded black bags, 4 plaid red bags.");
lines.push("faded blue bags contain 1 posh tan bag, 1 dotted violet bag, 3 posh gold bags.");
lines.push("wavy teal bags contain 3 pale brown bags.");
lines.push("striped red bags contain 2 light bronze bags, 3 dark cyan bags.");
lines.push("drab brown bags contain 3 striped magenta bags, 3 clear silver bags.");
lines.push("posh salmon bags contain 4 bright purple bags, 5 mirrored green bags, 3 pale gold bags, 5 dull crimson bags.");
lines.push("light black bags contain 2 wavy coral bags.");
lines.push("striped tan bags contain 3 clear blue bags, 3 mirrored teal bags, 5 striped red bags.");
lines.push("posh plum bags contain 3 drab orange bags.");
lines.push("striped blue bags contain 4 bright violet bags, 5 dotted gray bags, 3 dotted violet bags, 1 dotted blue bag.");
lines.push("shiny white bags contain 4 dotted orange bags, 1 faded silver bag, 1 drab coral bag.");
lines.push("plaid maroon bags contain 3 light gold bags.");
lines.push("shiny fuchsia bags contain 2 dotted olive bags, 3 vibrant white bags, 3 dark salmon bags, 4 pale white bags.");
lines.push("muted bronze bags contain 4 vibrant bronze bags, 2 posh yellow bags, 1 shiny turquoise bag.");
lines.push("wavy cyan bags contain 2 striped crimson bags, 4 plaid tan bags.");
lines.push("vibrant indigo bags contain 4 pale gold bags, 3 posh gold bags, 1 drab red bag, 4 dull crimson bags.");
lines.push("drab tan bags contain 3 dark indigo bags, 3 striped black bags.");
lines.push("dull tan bags contain 3 drab blue bags, 3 pale green bags, 3 dotted red bags, 3 striped maroon bags.");
lines.push("dark red bags contain 4 bright chartreuse bags.");
lines.push("drab beige bags contain 5 bright teal bags, 1 faded cyan bag, 2 muted yellow bags, 1 dim lime bag.");
lines.push("dim black bags contain 5 wavy fuchsia bags, 3 muted tomato bags, 4 faded blue bags.");
lines.push("pale red bags contain 2 drab gray bags, 5 dull coral bags, 4 striped purple bags.");
lines.push("light cyan bags contain 4 mirrored gold bags, 3 vibrant bronze bags.");
lines.push("posh orange bags contain 2 dark silver bags, 3 striped chartreuse bags.");
lines.push("shiny cyan bags contain 5 dark turquoise bags.");
lines.push("vibrant cyan bags contain 2 light turquoise bags, 2 clear cyan bags, 4 dark cyan bags, 4 dotted orange bags.");
lines.push("vibrant gray bags contain 5 dark purple bags, 5 dark lime bags.");
lines.push("posh green bags contain 4 bright salmon bags, 2 muted tan bags.");
lines.push("posh tan bags contain 2 dotted indigo bags, 1 dull purple bag.");
lines.push("clear blue bags contain 5 dull purple bags.");
lines.push("wavy gray bags contain 4 pale cyan bags, 2 pale tomato bags.");
lines.push("posh red bags contain 4 dim green bags, 2 pale teal bags.");
lines.push("light tomato bags contain 5 dotted chartreuse bags.");
lines.push("faded yellow bags contain 3 plaid orange bags, 4 mirrored maroon bags.");
lines.push("dark black bags contain 1 faded gold bag, 3 striped purple bags, 2 dim teal bags.");
lines.push("light red bags contain 5 dark magenta bags, 3 striped purple bags.");
lines.push("dotted violet bags contain no other bags.");
lines.push("faded gold bags contain 1 dotted aqua bag, 2 light turquoise bags, 5 wavy violet bags.");
lines.push("dotted beige bags contain 5 vibrant turquoise bags, 5 clear maroon bags, 3 dim tomato bags, 4 pale maroon bags.");
lines.push("pale lavender bags contain 5 muted red bags, 3 dark teal bags, 3 faded black bags, 1 dim fuchsia bag.");
lines.push("clear tomato bags contain 3 dull white bags, 3 mirrored gold bags, 1 dark black bag.");
lines.push("vibrant silver bags contain 4 plaid orange bags, 2 shiny chartreuse bags, 3 dark salmon bags, 4 light silver bags.");
lines.push("plaid cyan bags contain 1 dark black bag.");
lines.push("drab green bags contain 1 plaid white bag.");
lines.push("posh turquoise bags contain 3 posh plum bags, 3 light gold bags, 1 bright crimson bag.");
lines.push("pale lime bags contain 3 pale olive bags, 3 vibrant chartreuse bags, 1 dotted tan bag, 5 striped cyan bags.");
lines.push("wavy fuchsia bags contain 3 shiny chartreuse bags, 3 vibrant tomato bags, 3 posh salmon bags, 1 light cyan bag.");
lines.push("shiny beige bags contain 1 muted orange bag, 3 clear olive bags.");
lines.push("posh tomato bags contain 5 muted tomato bags, 5 drab coral bags, 4 pale gold bags.");
lines.push("dark fuchsia bags contain 3 wavy blue bags, 5 faded indigo bags.");
lines.push("dotted green bags contain 5 dull plum bags, 5 muted lavender bags, 3 faded magenta bags, 4 clear white bags.");
lines.push("light salmon bags contain 2 muted purple bags, 5 shiny turquoise bags, 4 muted red bags, 5 posh red bags.");
lines.push("plaid purple bags contain 1 muted indigo bag, 4 pale silver bags, 4 dull crimson bags, 1 posh cyan bag.");
lines.push("light chartreuse bags contain 2 posh brown bags.");
lines.push("dotted black bags contain 3 dull gray bags, 5 muted gray bags, 5 pale maroon bags, 1 vibrant green bag.");
lines.push("mirrored teal bags contain 4 light gold bags, 5 striped maroon bags, 2 pale maroon bags.");
lines.push("dotted coral bags contain 3 dull teal bags.");
lines.push("shiny lime bags contain 3 mirrored gray bags.");
lines.push("shiny chartreuse bags contain no other bags.");
lines.push("clear red bags contain 4 dim tan bags, 4 dotted brown bags, 2 striped orange bags.");
lines.push("clear magenta bags contain 3 pale blue bags, 2 pale crimson bags.");
lines.push("faded black bags contain 5 dark turquoise bags.");
lines.push("wavy violet bags contain 5 light purple bags.");
lines.push("vibrant crimson bags contain 1 shiny gold bag, 1 dotted tomato bag, 1 plaid black bag, 1 drab olive bag.");
lines.push("plaid violet bags contain 1 shiny tan bag, 3 muted gray bags, 4 drab chartreuse bags.");
lines.push("vibrant lime bags contain 3 dark magenta bags, 2 dotted white bags, 4 muted tan bags.");
lines.push("faded violet bags contain 2 drab red bags.");
lines.push("plaid black bags contain 2 clear aqua bags, 2 wavy silver bags, 4 dim violet bags, 2 plaid red bags.");
lines.push("dull orange bags contain 1 clear tan bag, 1 plaid crimson bag, 1 pale chartreuse bag.");
lines.push("vibrant magenta bags contain 4 striped blue bags.");
lines.push("plaid fuchsia bags contain 1 vibrant lime bag, 4 faded indigo bags, 2 wavy fuchsia bags, 1 dim purple bag.");
lines.push("mirrored olive bags contain 1 dark teal bag, 1 pale brown bag, 1 light violet bag, 1 shiny yellow bag.");
lines.push("wavy plum bags contain 5 vibrant cyan bags, 1 pale gold bag, 2 wavy gray bags, 5 pale gray bags.");
lines.push("striped magenta bags contain 5 faded silver bags, 1 mirrored teal bag.");
lines.push("light indigo bags contain 1 light olive bag.");
lines.push("mirrored crimson bags contain 2 vibrant crimson bags.");
lines.push("muted crimson bags contain 2 plaid olive bags.");
lines.push("muted yellow bags contain 1 muted brown bag, 4 striped lavender bags, 1 bright violet bag.");
lines.push("posh lavender bags contain 2 wavy coral bags, 3 light tan bags.");
lines.push("striped indigo bags contain 4 dark brown bags.");
lines.push("dotted red bags contain 4 pale olive bags, 3 dark teal bags, 1 posh fuchsia bag.");
lines.push("plaid indigo bags contain 5 faded gold bags, 4 clear coral bags, 3 dull purple bags, 5 pale brown bags.");
lines.push("plaid magenta bags contain 5 faded black bags, 3 drab aqua bags, 5 vibrant green bags.");
lines.push("light coral bags contain 1 bright gray bag, 4 wavy orange bags, 2 drab coral bags, 1 dark coral bag.");
lines.push("clear brown bags contain 4 plaid aqua bags, 4 plaid coral bags, 5 drab red bags.");
lines.push("drab black bags contain 2 dotted white bags, 1 muted purple bag, 3 posh gold bags.");
lines.push("dull magenta bags contain 1 dull tomato bag, 4 posh gray bags, 4 wavy white bags, 1 pale cyan bag.");
lines.push("muted violet bags contain 3 posh chartreuse bags, 1 dotted magenta bag.");
lines.push("vibrant turquoise bags contain 4 plaid brown bags, 5 drab indigo bags, 4 mirrored green bags.");
lines.push("striped aqua bags contain 2 posh violet bags, 5 shiny blue bags, 3 pale tomato bags.");
lines.push("light teal bags contain 4 faded cyan bags, 2 clear turquoise bags.");
lines.push("clear turquoise bags contain 3 shiny aqua bags, 5 posh tomato bags.");
lines.push("dark maroon bags contain 2 shiny gold bags, 5 faded green bags.");
lines.push("vibrant beige bags contain 5 plaid turquoise bags, 2 shiny gold bags, 2 clear tan bags, 1 wavy black bag.");
lines.push("muted chartreuse bags contain 2 muted white bags, 2 striped tan bags, 1 muted brown bag, 5 posh lime bags.");
lines.push("pale maroon bags contain 5 pale teal bags, 4 dim violet bags, 5 posh teal bags.");
lines.push("vibrant white bags contain 5 light bronze bags, 1 wavy silver bag.");
lines.push("plaid olive bags contain 5 mirrored teal bags, 5 faded gray bags, 4 light olive bags.");
lines.push("dull silver bags contain 5 clear cyan bags, 1 dim tan bag, 5 dim black bags.");
lines.push("bright crimson bags contain 5 dotted indigo bags.");
lines.push("muted teal bags contain 3 striped aqua bags, 4 dotted gray bags, 2 bright salmon bags.");
lines.push("wavy salmon bags contain 5 posh tomato bags.");
lines.push("bright purple bags contain 4 light maroon bags, 2 dotted violet bags.");
lines.push("plaid green bags contain 3 faded black bags, 2 plaid red bags, 4 clear turquoise bags.");
lines.push("wavy gold bags contain 1 bright white bag.");
lines.push("drab violet bags contain 4 vibrant tomato bags.");
lines.push("posh maroon bags contain 3 clear tan bags, 3 light gold bags, 1 dim lime bag.");
lines.push("muted beige bags contain 4 clear white bags, 5 light maroon bags, 2 clear orange bags.");
lines.push("dull turquoise bags contain 4 posh blue bags, 1 mirrored green bag, 5 dotted orange bags, 5 wavy fuchsia bags.");
lines.push("shiny red bags contain 4 dark magenta bags.");
lines.push("light turquoise bags contain 3 dark cyan bags.");
lines.push("posh olive bags contain 3 clear green bags, 5 bright bronze bags, 5 light olive bags.");
lines.push("dim chartreuse bags contain 5 vibrant plum bags.");
lines.push("dark salmon bags contain 1 dotted orange bag, 3 light brown bags, 3 dotted chartreuse bags.");
lines.push("dull teal bags contain 4 wavy gold bags, 5 faded red bags, 4 light turquoise bags.");
lines.push("dark green bags contain 3 pale silver bags, 5 clear tan bags.");
lines.push("bright cyan bags contain 2 striped maroon bags, 1 clear silver bag, 1 dark maroon bag.");
lines.push("wavy crimson bags contain 3 wavy tan bags.");
lines.push("mirrored white bags contain 4 mirrored teal bags, 2 muted silver bags.");
lines.push("dark magenta bags contain 1 drab blue bag, 4 light white bags, 3 dark black bags.");
lines.push("light gold bags contain 4 posh red bags, 1 striped maroon bag, 5 bright purple bags, 4 dotted violet bags.");
lines.push("pale tomato bags contain 5 drab coral bags, 3 posh teal bags, 4 dotted blue bags.");
lines.push("dull purple bags contain 4 posh gold bags.");
lines.push("mirrored gold bags contain 3 mirrored teal bags, 1 striped maroon bag, 2 dotted indigo bags.");
lines.push("dotted turquoise bags contain 2 dim violet bags.");
lines.push("muted magenta bags contain 1 muted red bag.");
lines.push("bright maroon bags contain 3 wavy fuchsia bags, 2 dark magenta bags, 2 dim maroon bags, 1 dotted teal bag.");
lines.push("bright aqua bags contain 5 dim green bags, 2 striped tan bags, 1 faded olive bag.");
lines.push("striped silver bags contain 5 striped aqua bags, 2 striped purple bags, 3 dim blue bags, 3 faded olive bags.");
lines.push("light brown bags contain 4 posh red bags, 3 clear gold bags.");
lines.push("dark brown bags contain 4 clear olive bags.");
lines.push("dim crimson bags contain 4 dotted teal bags, 3 dark salmon bags.");
lines.push("wavy black bags contain 3 drab coral bags, 1 striped purple bag, 2 light brown bags, 4 plaid red bags.");
lines.push("striped coral bags contain 2 plaid blue bags, 5 drab tan bags, 5 light violet bags.");
lines.push("dull blue bags contain 3 pale gold bags, 1 posh crimson bag.");
lines.push("pale blue bags contain 4 dotted blue bags, 3 muted beige bags, 1 faded red bag.");
lines.push("mirrored yellow bags contain 4 muted cyan bags, 2 mirrored tan bags.");
lines.push("dim maroon bags contain 1 muted aqua bag.");
lines.push("drab plum bags contain 2 shiny magenta bags.");
lines.push("clear maroon bags contain 2 drab orange bags, 3 shiny red bags, 1 clear brown bag.");
lines.push("muted red bags contain 5 pale teal bags, 3 dim fuchsia bags, 1 light maroon bag.");
lines.push("dark plum bags contain 5 light salmon bags, 4 dim olive bags.");
lines.push("faded indigo bags contain 1 mirrored red bag, 3 faded lime bags.");
lines.push("bright coral bags contain 3 posh gold bags, 3 vibrant crimson bags.");
lines.push("dark indigo bags contain 5 faded silver bags, 2 dull tomato bags.");
lines.push("drab white bags contain 5 light silver bags.");
lines.push("vibrant violet bags contain 2 pale gray bags, 4 bright white bags, 3 light aqua bags.");
lines.push("mirrored maroon bags contain 1 pale cyan bag, 4 clear bronze bags.");
lines.push("wavy chartreuse bags contain 1 bright brown bag, 4 dim lime bags.");
lines.push("dull brown bags contain 3 bright olive bags.");
lines.push("vibrant yellow bags contain 3 shiny white bags, 2 clear blue bags.");
lines.push("posh bronze bags contain 1 light bronze bag.");
lines.push("dim aqua bags contain 5 wavy yellow bags, 3 muted purple bags, 3 pale crimson bags.");
lines.push("clear gray bags contain 4 faded coral bags, 1 striped violet bag, 5 pale crimson bags, 4 muted lavender bags.");
lines.push("muted plum bags contain 4 mirrored cyan bags.");
lines.push("dim lime bags contain 2 clear plum bags, 2 dim green bags, 5 posh tan bags.");
lines.push("dim red bags contain 2 plaid brown bags.");
lines.push("drab bronze bags contain 4 faded plum bags, 4 clear plum bags, 1 posh cyan bag, 1 dark cyan bag.");
lines.push("shiny purple bags contain 5 posh beige bags, 4 pale fuchsia bags, 2 wavy brown bags, 2 shiny maroon bags.");
lines.push("dull beige bags contain 1 mirrored indigo bag, 2 drab cyan bags, 1 dim fuchsia bag.");
lines.push("wavy blue bags contain 4 dotted maroon bags, 3 light maroon bags.");
lines.push("faded white bags contain 2 vibrant purple bags, 1 muted purple bag.");
lines.push("pale teal bags contain no other bags.");
lines.push("bright tan bags contain 3 clear indigo bags, 2 pale orange bags.");
lines.push("dull crimson bags contain 3 pale maroon bags, 3 vibrant bronze bags.");
lines.push("posh black bags contain 1 muted tomato bag.");
lines.push("vibrant maroon bags contain 5 mirrored crimson bags, 4 wavy beige bags.");
lines.push("dark lime bags contain 4 dim yellow bags, 1 pale beige bag, 1 vibrant beige bag.");
lines.push("bright white bags contain 2 dark turquoise bags.");
lines.push("faded plum bags contain 1 vibrant indigo bag, 5 dotted maroon bags, 1 vibrant bronze bag.");
lines.push("pale violet bags contain 2 pale lavender bags, 4 light brown bags, 5 vibrant tomato bags.");
lines.push("wavy purple bags contain 2 shiny tomato bags, 2 clear maroon bags, 3 posh bronze bags, 4 dull aqua bags.");
lines.push("plaid yellow bags contain 4 pale tomato bags, 2 dotted magenta bags, 5 wavy violet bags.");
lines.push("bright silver bags contain 5 light gold bags, 2 posh tan bags, 4 faded gray bags.");
lines.push("dark orange bags contain 4 dull yellow bags, 5 dull salmon bags.");
lines.push("wavy coral bags contain 5 dim lavender bags, 2 mirrored teal bags, 1 shiny chartreuse bag, 2 light gold bags.");
lines.push("pale aqua bags contain 1 faded plum bag, 5 vibrant plum bags.");
lines.push("dotted brown bags contain 2 light purple bags, 4 dim beige bags, 5 pale white bags.");
lines.push("plaid blue bags contain 1 shiny red bag, 5 light silver bags, 5 clear orange bags.");
lines.push("dim violet bags contain 3 posh teal bags.");
lines.push("dull yellow bags contain 5 muted aqua bags.");
lines.push("shiny yellow bags contain 5 muted aqua bags, 2 drab white bags, 5 muted purple bags.");
lines.push("dotted maroon bags contain 4 dim green bags, 2 faded silver bags.");
lines.push("bright brown bags contain 4 striped bronze bags.");
lines.push("posh crimson bags contain 2 posh red bags, 1 dotted indigo bag, 4 muted red bags.");
lines.push("dim orange bags contain 2 light tan bags, 4 dotted salmon bags.");
lines.push("mirrored beige bags contain 4 dim bronze bags, 5 vibrant salmon bags, 4 dim maroon bags.");
lines.push("shiny olive bags contain 5 dotted orange bags.");
lines.push("wavy tan bags contain 1 wavy brown bag, 1 faded silver bag.");
lines.push("mirrored magenta bags contain 5 drab teal bags, 3 striped bronze bags, 3 striped magenta bags, 5 dark tan bags.");
lines.push("muted brown bags contain 1 light indigo bag, 4 dotted blue bags.");
lines.push("vibrant aqua bags contain 1 shiny red bag, 5 wavy gold bags.");
lines.push("dark violet bags contain 2 dim orange bags, 5 dark purple bags, 2 pale yellow bags.");
lines.push("plaid teal bags contain 3 vibrant bronze bags.");
lines.push("shiny gold bags contain 5 drab red bags, 2 mirrored green bags, 2 muted tomato bags, 1 striped magenta bag.");
lines.push("wavy bronze bags contain 2 vibrant green bags, 2 plaid orange bags, 2 vibrant orange bags.");
lines.push("dark tomato bags contain 4 posh indigo bags.");
lines.push("drab red bags contain no other bags.");
lines.push("clear silver bags contain 1 plaid olive bag.");
lines.push("striped cyan bags contain 3 wavy silver bags, 2 faded indigo bags.");
lines.push("dark purple bags contain 1 wavy violet bag, 5 clear olive bags, 3 drab indigo bags, 5 striped purple bags.");
lines.push("dotted plum bags contain 4 vibrant purple bags, 3 muted lavender bags, 1 wavy coral bag.");
lines.push("posh yellow bags contain 5 light salmon bags, 2 light bronze bags.");
lines.push("dim tomato bags contain 3 pale white bags.");
lines.push("drab lime bags contain 3 drab chartreuse bags, 4 clear silver bags, 4 drab aqua bags.");
lines.push("plaid coral bags contain 2 bright olive bags.");
lines.push("mirrored salmon bags contain 3 plaid green bags.");
lines.push("faded chartreuse bags contain 2 light cyan bags, 5 pale tomato bags.");
lines.push("pale crimson bags contain 5 bright white bags, 3 shiny turquoise bags.");
lines.push("pale brown bags contain 4 bright silver bags.");
lines.push("shiny bronze bags contain 5 dull chartreuse bags, 4 dotted gray bags, 3 shiny blue bags, 1 dull blue bag.");
lines.push("faded red bags contain 2 muted gray bags.");
lines.push("dark lavender bags contain 5 dim coral bags, 4 muted gray bags, 1 shiny yellow bag.");
lines.push("faded purple bags contain 2 dotted white bags.");
lines.push("mirrored silver bags contain 3 pale maroon bags, 2 pale cyan bags, 4 dark chartreuse bags, 3 bright plum bags.");
lines.push("dull violet bags contain 1 dim coral bag, 3 wavy lavender bags.");
lines.push("faded beige bags contain 4 plaid bronze bags, 1 light salmon bag, 2 light brown bags.");
lines.push("vibrant orange bags contain 1 faded cyan bag, 2 vibrant olive bags, 2 bright plum bags.");
lines.push("vibrant purple bags contain 5 dotted orange bags, 1 striped aqua bag, 4 clear white bags, 3 dim olive bags.");
lines.push("faded crimson bags contain 1 clear lavender bag, 3 dim lavender bags, 3 dim cyan bags, 2 wavy tan bags.");
lines.push("dark yellow bags contain 1 plaid silver bag, 3 wavy maroon bags.");
lines.push("vibrant brown bags contain 5 dotted chartreuse bags, 4 clear silver bags, 4 dull lavender bags.");
lines.push("wavy lavender bags contain 4 dull gray bags.");
lines.push("bright green bags contain 5 striped gold bags.");
lines.push("faded magenta bags contain 5 dull beige bags.");
lines.push("posh white bags contain 2 dark coral bags.");
lines.push("muted green bags contain 1 wavy lavender bag, 1 striped aqua bag.");
lines.push("plaid turquoise bags contain 1 striped brown bag, 4 mirrored maroon bags.");
lines.push("plaid lavender bags contain 4 striped tan bags, 2 posh brown bags, 5 shiny brown bags.");
lines.push("pale fuchsia bags contain 5 light brown bags, 3 vibrant lime bags.");
lines.push("light gray bags contain 3 drab violet bags.");
lines.push("dim green bags contain no other bags.");
lines.push("light olive bags contain 4 vibrant bronze bags.");
lines.push("dotted aqua bags contain 5 muted red bags.");
lines.push("vibrant fuchsia bags contain 5 dull crimson bags, 5 dotted violet bags.");
lines.push("clear crimson bags contain 5 dotted tomato bags, 3 posh crimson bags, 5 vibrant magenta bags.");
lines.push("pale orange bags contain 5 mirrored indigo bags, 5 muted purple bags, 4 plaid orange bags.");
lines.push("mirrored lavender bags contain 4 dotted orange bags, 3 posh violet bags.");
lines.push("dotted tan bags contain 5 mirrored gray bags.");
lines.push("dim bronze bags contain 3 mirrored olive bags, 3 plaid magenta bags, 5 dim black bags, 2 drab blue bags.");
lines.push("clear olive bags contain 3 bright purple bags, 4 dim lime bags, 5 dim fuchsia bags.");
lines.push("dotted blue bags contain 1 dim green bag, 3 drab red bags, 2 posh gold bags.");
lines.push("shiny gray bags contain 3 pale lavender bags, 1 clear gold bag, 2 drab violet bags, 2 clear bronze bags.");
lines.push("bright plum bags contain 3 muted yellow bags, 4 posh chartreuse bags, 3 posh brown bags, 3 dim orange bags.");
lines.push("shiny violet bags contain 5 dim coral bags.");
lines.push("posh lime bags contain 3 plaid silver bags.");
lines.push("light beige bags contain 5 pale yellow bags, 3 light bronze bags, 5 pale turquoise bags.");
lines.push("drab gray bags contain 4 bright purple bags, 5 faded gold bags, 2 dim green bags.");
lines.push("muted aqua bags contain 4 clear white bags.");
lines.push("mirrored blue bags contain 2 vibrant green bags, 2 drab gray bags.");
lines.push("posh magenta bags contain 2 striped magenta bags, 5 dim cyan bags, 5 plaid orange bags, 1 wavy black bag.");
lines.push("dim yellow bags contain 2 muted purple bags, 1 striped black bag, 3 wavy coral bags.");
lines.push("dull indigo bags contain 3 posh fuchsia bags, 1 dotted beige bag.");
lines.push("posh gray bags contain 5 drab black bags.");
lines.push("dark blue bags contain 4 dim gold bags, 3 drab olive bags, 1 light cyan bag, 2 light tomato bags.");
lines.push("mirrored red bags contain 5 shiny white bags, 1 mirrored green bag, 4 wavy black bags, 1 dark brown bag.");
lines.push("mirrored violet bags contain 3 dim tan bags, 4 dark fuchsia bags, 4 pale turquoise bags.");
lines.push("shiny black bags contain 5 clear orange bags, 2 vibrant silver bags, 2 plaid maroon bags, 3 light olive bags.");
lines.push("vibrant chartreuse bags contain 4 dull salmon bags, 3 bright beige bags, 1 faded blue bag, 2 plaid brown bags.");
lines.push("dull cyan bags contain 3 faded green bags.");
lines.push("bright gold bags contain 3 posh plum bags.");
lines.push("vibrant olive bags contain 5 mirrored coral bags, 3 dotted lime bags, 5 drab blue bags, 2 dotted green bags.");
lines.push("faded maroon bags contain 4 mirrored green bags, 2 light lime bags, 3 light bronze bags.");
lines.push("vibrant red bags contain 2 posh lime bags, 1 dull maroon bag.");
lines.push("dull bronze bags contain 5 vibrant chartreuse bags.");
lines.push("vibrant bronze bags contain 2 vibrant tomato bags, 3 mirrored teal bags.");
lines.push("pale black bags contain 1 muted silver bag, 5 mirrored teal bags, 2 shiny blue bags.");
lines.push("dull maroon bags contain 1 clear cyan bag.");
lines.push("dotted crimson bags contain 5 posh black bags, 1 dotted teal bag, 4 vibrant salmon bags, 4 shiny silver bags.");
lines.push("striped tomato bags contain 5 drab tomato bags, 2 faded coral bags, 2 dim salmon bags.");
lines.push("bright bronze bags contain 5 plaid red bags, 4 striped yellow bags.");
lines.push("dark aqua bags contain 4 bright purple bags, 1 striped gold bag.");
lines.push("striped teal bags contain 4 striped black bags, 3 clear indigo bags.");
lines.push("dark olive bags contain 2 pale cyan bags, 5 mirrored tan bags.");
lines.push("dark teal bags contain 1 posh gold bag, 1 plaid orange bag, 1 vibrant bronze bag, 1 mirrored teal bag.");
lines.push("faded green bags contain 5 vibrant fuchsia bags, 3 dim olive bags.");
lines.push("posh brown bags contain 4 drab lime bags, 2 mirrored fuchsia bags, 3 shiny lime bags, 2 dim violet bags.");
lines.push("striped lavender bags contain 2 plaid red bags, 5 dark brown bags, 3 clear turquoise bags.");
lines.push("shiny indigo bags contain 2 striped lavender bags, 1 light gray bag.");
lines.push("plaid orange bags contain 1 pale teal bag, 5 dim violet bags, 5 vibrant bronze bags, 3 light maroon bags.");
lines.push("dull salmon bags contain 1 striped bronze bag, 4 shiny aqua bags, 4 dark brown bags.");
lines.push("plaid white bags contain 1 dim green bag.");
lines.push("drab lavender bags contain 2 dotted maroon bags, 3 pale aqua bags, 1 light olive bag.");
lines.push("striped olive bags contain 5 striped magenta bags.");
lines.push("mirrored gray bags contain 2 dim lavender bags, 2 shiny chartreuse bags.");
lines.push("dull coral bags contain 1 mirrored gold bag, 5 clear gold bags, 5 clear olive bags, 2 posh tomato bags.");
lines.push("pale beige bags contain 2 dark indigo bags, 4 dim beige bags.");
lines.push("posh teal bags contain 1 dim green bag, 3 dim fuchsia bags, 1 pale teal bag, 2 dotted indigo bags.");
lines.push("mirrored turquoise bags contain 4 dim olive bags, 2 plaid tomato bags.");
lines.push("dim turquoise bags contain 2 bright yellow bags, 1 striped lavender bag.");
lines.push("light violet bags contain 4 faded gold bags, 3 clear plum bags, 1 dark teal bag.");
lines.push("dark cyan bags contain 3 drab red bags, 4 pale maroon bags.");
lines.push("shiny crimson bags contain 5 dotted turquoise bags, 1 vibrant fuchsia bag, 5 dotted lime bags, 2 wavy green bags.");
lines.push("muted lime bags contain 2 light brown bags, 5 plaid tomato bags, 4 plaid aqua bags.");
lines.push("vibrant tan bags contain 4 wavy fuchsia bags.");
lines.push("wavy maroon bags contain 4 dull white bags, 5 dark crimson bags, 5 mirrored salmon bags, 4 vibrant purple bags.");
lines.push("muted indigo bags contain 5 shiny red bags.");
lines.push("clear violet bags contain 2 plaid green bags.");
lines.push("drab teal bags contain 2 pale cyan bags, 1 shiny turquoise bag.");
lines.push("wavy green bags contain 5 plaid indigo bags, 3 muted silver bags, 5 light brown bags.");
lines.push("striped crimson bags contain 3 shiny aqua bags.");
lines.push("drab purple bags contain 3 drab orange bags, 3 dark aqua bags, 1 bright lavender bag.");
lines.push("plaid aqua bags contain 1 plaid tomato bag.");
lines.push("striped green bags contain 2 vibrant tomato bags, 2 faded plum bags.");
lines.push("drab tomato bags contain 4 posh black bags, 3 dull brown bags, 1 drab cyan bag.");
lines.push("dotted bronze bags contain 1 clear indigo bag.");
lines.push("pale white bags contain 5 mirrored green bags, 2 dark turquoise bags, 3 dull olive bags, 4 drab indigo bags.");
lines.push("drab yellow bags contain 2 dotted orange bags, 4 light turquoise bags, 4 light salmon bags, 2 dotted tomato bags.");
lines.push("pale green bags contain 3 muted gold bags, 3 shiny turquoise bags.");
lines.push("dark tan bags contain 4 muted cyan bags, 5 dotted tomato bags, 2 dark indigo bags.");
lines.push("plaid tan bags contain 4 vibrant olive bags, 1 plaid aqua bag, 3 dotted coral bags, 4 bright violet bags.");
lines.push("shiny aqua bags contain 2 dull brown bags, 1 vibrant cyan bag, 2 dim lime bags, 5 light bronze bags.");
lines.push("bright turquoise bags contain 2 plaid yellow bags, 3 posh lavender bags, 1 pale yellow bag.");
lines.push("vibrant gold bags contain 1 clear tomato bag, 4 clear turquoise bags, 4 dark bronze bags.");
lines.push("posh cyan bags contain 3 dotted green bags, 5 plaid tomato bags, 3 wavy crimson bags, 2 striped olive bags.");
lines.push("clear salmon bags contain 3 plaid fuchsia bags, 5 muted bronze bags, 5 dull green bags, 2 pale brown bags.");
lines.push("drab maroon bags contain 5 dull crimson bags, 2 shiny white bags, 5 light purple bags.");
lines.push("clear tan bags contain 5 dull lime bags, 5 muted red bags, 2 clear cyan bags.");
lines.push("pale gray bags contain 3 shiny white bags.");
lines.push("vibrant teal bags contain 1 clear green bag, 1 dull beige bag.");
lines.push("vibrant plum bags contain 4 muted red bags, 2 faded blue bags, 5 vibrant tomato bags.");
lines.push("dark coral bags contain 2 plaid tomato bags, 1 bright yellow bag, 2 mirrored gray bags.");
lines.push("wavy indigo bags contain 1 mirrored tan bag, 1 wavy lavender bag.");
lines.push("dotted fuchsia bags contain 2 vibrant silver bags, 3 mirrored tan bags.");
lines.push("muted gold bags contain 3 muted red bags, 1 clear olive bag.");
lines.push("striped fuchsia bags contain 2 clear aqua bags, 4 mirrored coral bags, 3 muted gray bags, 2 dark beige bags.");
lines.push("striped maroon bags contain no other bags.");
lines.push("bright lavender bags contain 2 faded indigo bags, 1 dotted violet bag, 5 posh tomato bags, 3 clear indigo bags.");
lines.push("posh gold bags contain 1 dim violet bag, 2 shiny chartreuse bags.");
lines.push("drab olive bags contain 4 faded silver bags.");
lines.push("pale chartreuse bags contain 4 striped teal bags.");
lines.push("mirrored lime bags contain 5 dotted plum bags, 1 light yellow bag, 3 pale fuchsia bags.");
lines.push("clear bronze bags contain 4 plaid brown bags.");
lines.push("wavy tomato bags contain 4 faded lavender bags, 3 dull aqua bags, 1 drab green bag, 3 vibrant gray bags.");
lines.push("dim brown bags contain 4 dull teal bags, 2 vibrant black bags, 1 mirrored gold bag.");
lines.push("bright fuchsia bags contain 4 faded lavender bags, 1 dull crimson bag, 1 mirrored brown bag, 5 dark indigo bags.");
lines.push("muted gray bags contain 1 dull olive bag.");
lines.push("dull white bags contain 1 light maroon bag, 4 dark lavender bags, 2 posh red bags.");
lines.push("dull black bags contain 5 dark green bags, 4 bright lime bags, 4 mirrored gray bags.");
lines.push("dull tomato bags contain 4 dotted tomato bags.");
lines.push("pale coral bags contain 1 mirrored white bag, 5 clear aqua bags, 4 dim blue bags.");
lines.push("posh indigo bags contain 2 bright bronze bags.");
lines.push("plaid gold bags contain 4 dark maroon bags, 4 shiny lavender bags, 1 plaid tomato bag, 3 bright yellow bags.");
lines.push("plaid gray bags contain 4 muted bronze bags, 2 posh chartreuse bags, 5 pale tomato bags, 3 drab coral bags.");
lines.push("dim beige bags contain 4 dim blue bags, 4 dark lavender bags.");
lines.push("bright olive bags contain no other bags.");
lines.push("clear aqua bags contain 4 wavy fuchsia bags, 5 dim green bags.");
lines.push("posh violet bags contain 2 vibrant indigo bags, 3 posh tomato bags, 4 clear gold bags, 5 dim green bags.");
lines.push("faded coral bags contain 4 light purple bags, 4 mirrored salmon bags, 5 pale maroon bags.");
lines.push("dotted chartreuse bags contain 2 clear aqua bags, 4 plaid coral bags.");
lines.push("striped orange bags contain 5 bright tan bags, 5 pale white bags, 5 mirrored lavender bags.");
lines.push("bright tomato bags contain 5 muted white bags.");
lines.push("shiny silver bags contain 1 dotted orange bag, 2 light olive bags, 1 striped gold bag.");
lines.push("striped yellow bags contain 1 shiny turquoise bag.");
lines.push("faded aqua bags contain 5 shiny cyan bags, 3 dotted indigo bags, 4 faded fuchsia bags.");
lines.push("striped beige bags contain 1 bright white bag, 5 dim lavender bags, 5 striped black bags, 1 wavy black bag.");
lines.push("shiny orange bags contain 4 dark aqua bags.");
lines.push("striped white bags contain 3 vibrant fuchsia bags, 1 dotted teal bag, 5 dotted green bags, 2 shiny white bags.");
lines.push("bright black bags contain 5 pale blue bags, 2 drab teal bags, 1 dull gray bag.");
lines.push("shiny lavender bags contain 1 pale gold bag, 2 bright crimson bags, 2 pale maroon bags.");
lines.push("shiny maroon bags contain 2 wavy white bags, 2 muted aqua bags, 3 plaid gold bags.");
lines.push("drab cyan bags contain 4 posh crimson bags, 5 drab red bags, 5 bright purple bags.");
lines.push("dark bronze bags contain 5 posh teal bags.");
lines.push("shiny turquoise bags contain 2 shiny gold bags, 5 mirrored teal bags, 5 mirrored gray bags, 1 drab cyan bag.");
lines.push("dark turquoise bags contain 1 dim violet bag, 5 mirrored teal bags.");
lines.push("light lime bags contain 4 drab chartreuse bags.");
lines.push("light yellow bags contain 5 wavy olive bags, 2 wavy gray bags, 4 bright red bags, 5 shiny violet bags.");
lines.push("posh aqua bags contain 3 vibrant salmon bags.");
lines.push("drab silver bags contain 3 pale tan bags.");
lines.push("pale tan bags contain 3 wavy white bags.");
lines.push("light white bags contain 4 wavy black bags, 2 dark teal bags, 2 faded blue bags.");
lines.push("shiny teal bags contain 5 wavy gold bags.");
lines.push("shiny tomato bags contain 3 faded violet bags.");
lines.push("wavy brown bags contain 1 dim black bag, 1 bright yellow bag.");
lines.push("dim tan bags contain 2 clear teal bags, 5 drab teal bags, 4 posh lime bags.");
lines.push("faded cyan bags contain 1 pale plum bag, 4 posh gold bags, 4 posh yellow bags.");
lines.push("dotted magenta bags contain 4 drab tomato bags, 5 drab yellow bags, 2 clear maroon bags.");
lines.push("clear green bags contain 5 striped maroon bags, 4 shiny aqua bags.");
lines.push("clear fuchsia bags contain 5 dotted chartreuse bags, 5 pale plum bags, 2 muted red bags.");
lines.push("bright lime bags contain 3 dark salmon bags, 3 bright cyan bags, 4 striped black bags, 4 posh violet bags.");
lines.push("bright violet bags contain 1 light olive bag, 2 dark coral bags, 1 dull beige bag, 5 plaid maroon bags.");
lines.push("vibrant lavender bags contain 5 dim green bags, 1 plaid violet bag, 4 dotted coral bags.");
lines.push("wavy silver bags contain 2 mirrored green bags, 4 clear olive bags, 5 dark beige bags, 5 plaid orange bags.");
lines.push("clear orange bags contain 4 dotted orange bags, 3 bright silver bags, 5 dotted tomato bags, 4 striped purple bags.");
lines.push("light crimson bags contain 5 striped teal bags, 1 striped coral bag, 1 pale tomato bag, 2 dark crimson bags.");
lines.push("bright gray bags contain 3 posh tan bags.");
lines.push("mirrored indigo bags contain 1 mirrored green bag.");
lines.push("dull chartreuse bags contain 4 pale gold bags, 2 drab lavender bags, 3 shiny cyan bags.");
lines.push("pale salmon bags contain 5 drab purple bags, 2 dark olive bags, 4 mirrored silver bags.");
lines.push("bright indigo bags contain 5 striped beige bags, 5 shiny lime bags.");
lines.push("dim lavender bags contain 5 striped maroon bags.");
lines.push("bright magenta bags contain 2 plaid coral bags, 5 shiny aqua bags, 1 light purple bag.");
lines.push("muted purple bags contain 4 shiny turquoise bags, 1 shiny chartreuse bag, 3 muted tomato bags, 1 dotted aqua bag.");
lines.push("muted cyan bags contain 4 wavy black bags, 2 faded plum bags, 1 dull coral bag, 3 light tomato bags.");
lines.push("shiny plum bags contain 5 pale gray bags, 3 vibrant aqua bags.");
lines.push("dull lime bags contain 4 drab cyan bags, 1 posh gold bag, 4 bright purple bags, 3 posh tan bags.");
lines.push("faded teal bags contain 3 bright purple bags, 4 dotted magenta bags, 4 plaid olive bags.");
lines.push("clear chartreuse bags contain 2 dark brown bags, 1 pale lavender bag, 2 dark coral bags.");
lines.push("dotted tomato bags contain 1 dim green bag, 2 posh tomato bags.");
lines.push("pale silver bags contain 2 pale teal bags, 4 light purple bags, 4 bright yellow bags, 4 clear plum bags.");
lines.push("posh purple bags contain 2 faded tan bags, 3 clear aqua bags, 4 striped lavender bags, 3 dark teal bags.");
lines.push("striped bronze bags contain 4 drab red bags, 5 mirrored gray bags.");
lines.push("striped black bags contain 3 wavy coral bags, 3 faded blue bags, 5 bright olive bags, 2 dark bronze bags.");
lines.push("dark chartreuse bags contain 5 posh tomato bags.");
lines.push("muted white bags contain 2 mirrored gray bags, 5 dark cyan bags, 3 dotted indigo bags.");
lines.push("clear indigo bags contain 3 dark coral bags, 1 pale green bag, 2 plaid orange bags, 4 dim lime bags.");
lines.push("faded tan bags contain 3 dull purple bags, 2 dim orange bags.");
lines.push("clear yellow bags contain 1 vibrant fuchsia bag, 5 faded silver bags, 5 faded black bags.");
lines.push("dark gray bags contain 5 striped cyan bags.");
lines.push("clear plum bags contain 2 drab indigo bags, 5 pale maroon bags.");
lines.push("posh fuchsia bags contain 2 muted lavender bags, 5 posh red bags.");
lines.push("vibrant black bags contain 1 posh gold bag, 1 shiny white bag.");
lines.push("dim salmon bags contain 5 muted tan bags, 2 muted green bags, 2 pale bronze bags.");
lines.push("faded brown bags contain 3 dim tan bags.");
lines.push("mirrored brown bags contain 1 drab bronze bag, 3 wavy coral bags, 4 posh fuchsia bags.");
lines.push("dim gold bags contain 2 mirrored lavender bags, 5 pale gray bags.");
lines.push("faded fuchsia bags contain 3 wavy lavender bags, 5 shiny blue bags, 4 muted tomato bags.");
lines.push("mirrored chartreuse bags contain 2 faded aqua bags, 4 dark coral bags, 4 wavy beige bags, 5 dark orange bags.");
lines.push("muted fuchsia bags contain 3 light olive bags.");
lines.push("dotted silver bags contain 5 dotted turquoise bags, 3 dark cyan bags, 2 plaid red bags.");
lines.push("plaid lime bags contain 5 dull blue bags.");
lines.push("dim gray bags contain 4 striped magenta bags, 3 dotted indigo bags, 2 dim violet bags, 3 light olive bags.");
lines.push("wavy lime bags contain 2 bright salmon bags, 3 shiny cyan bags, 4 light gray bags, 4 shiny plum bags.");
lines.push("striped lime bags contain 5 posh teal bags.");
lines.push("dull red bags contain 3 mirrored tan bags, 3 dim tomato bags, 5 striped crimson bags.");
lines.push("faded lavender bags contain 1 bright indigo bag, 1 dim purple bag, 5 mirrored gray bags, 4 clear cyan bags.");
lines.push("wavy aqua bags contain 1 wavy gray bag, 3 dark crimson bags.");
lines.push("faded turquoise bags contain 1 drab plum bag, 5 dull gray bags, 4 plaid black bags, 1 wavy crimson bag.");
lines.push("dotted salmon bags contain 4 posh teal bags.");
lines.push("clear coral bags contain 5 drab tomato bags.");
lines.push("vibrant blue bags contain 4 dim lavender bags, 4 dark cyan bags.");
lines.push("muted coral bags contain 5 vibrant olive bags, 1 clear plum bag, 1 clear blue bag.");
lines.push("vibrant coral bags contain 5 vibrant silver bags, 2 plaid brown bags, 4 wavy brown bags.");
lines.push("mirrored aqua bags contain 4 bright lavender bags, 4 striped lavender bags, 1 posh fuchsia bag.");
lines.push("clear gold bags contain 1 posh tan bag, 1 dark beige bag, 5 striped gold bags.");
lines.push("dull aqua bags contain 4 dull plum bags, 2 light indigo bags.");
lines.push("clear cyan bags contain 5 light maroon bags, 5 posh tan bags, 3 dim lavender bags.");
lines.push("dotted olive bags contain 1 mirrored maroon bag, 2 dotted red bags, 4 drab lime bags.");
lines.push("wavy yellow bags contain 4 light silver bags, 4 dotted orange bags.");
lines.push("faded salmon bags contain 1 shiny lavender bag, 4 muted tomato bags, 3 plaid coral bags, 3 pale green bags.");
lines.push("dim blue bags contain 2 dim black bags.");
lines.push("faded tomato bags contain 3 shiny magenta bags.");
lines.push("light magenta bags contain 5 dim olive bags, 3 muted lavender bags.");
lines.push("muted turquoise bags contain 4 posh gold bags, 2 wavy beige bags, 3 posh magenta bags.");
lines.push("light purple bags contain 3 light maroon bags.");
lines.push("pale indigo bags contain 2 light green bags, 5 plaid bronze bags.");
lines.push("dim fuchsia bags contain no other bags.");
lines.push("plaid chartreuse bags contain 3 shiny silver bags, 1 posh teal bag.");
lines.push("plaid salmon bags contain 5 drab lime bags, 4 light aqua bags, 2 striped tan bags.");
lines.push("drab coral bags contain no other bags.");
lines.push("dotted gold bags contain 2 clear teal bags, 2 posh salmon bags, 1 plaid green bag, 5 muted tomato bags.");
lines.push("dull olive bags contain 2 dim lavender bags.");
lines.push("dotted purple bags contain 5 vibrant white bags, 5 wavy black bags.");
lines.push("dark crimson bags contain 4 posh chartreuse bags, 3 muted green bags, 3 dull plum bags, 5 muted beige bags.");
lines.push("mirrored tomato bags contain 2 clear crimson bags, 4 mirrored indigo bags, 2 muted black bags, 2 dark gray bags.");
lines.push("muted blue bags contain 5 pale brown bags.");
lines.push("wavy beige bags contain 5 plaid red bags.");
lines.push("muted black bags contain 3 muted magenta bags, 2 clear tomato bags, 1 pale red bag.");
lines.push("mirrored bronze bags contain 5 bright olive bags, 5 vibrant cyan bags, 2 drab cyan bags.");
lines.push("vibrant green bags contain 2 dull brown bags, 4 wavy white bags, 3 pale teal bags, 4 dark bronze bags.");
lines.push("dotted orange bags contain 5 light gold bags, 5 vibrant tomato bags, 3 light silver bags, 4 drab cyan bags.");
lines.push("clear purple bags contain 4 dull fuchsia bags.");
lines.push("mirrored green bags contain 2 muted red bags, 2 dim lavender bags.");
lines.push("wavy red bags contain 1 posh yellow bag, 2 shiny coral bags.");
lines.push("drab chartreuse bags contain 5 dull purple bags, 2 bright purple bags, 3 faded silver bags, 4 muted lavender bags.");
lines.push("dim indigo bags contain 1 light red bag, 4 wavy olive bags.");
lines.push("drab crimson bags contain 5 muted indigo bags, 5 vibrant crimson bags.");
lines.push("wavy olive bags contain 3 light black bags, 2 wavy plum bags.");
lines.push("dark silver bags contain 4 dull fuchsia bags, 3 dotted chartreuse bags.");
lines.push("pale olive bags contain 1 dark purple bag, 1 drab yellow bag, 1 vibrant coral bag.");
lines.push("posh silver bags contain 4 faded magenta bags, 5 muted coral bags, 4 posh cyan bags, 2 faded gray bags.");
lines.push("clear white bags contain 4 shiny blue bags.");
lines.push("light silver bags contain 3 mirrored green bags, 2 muted red bags, 1 muted tomato bag, 3 clear olive bags.");
lines.push("faded gray bags contain 5 dim green bags, 5 pale teal bags, 4 posh crimson bags, 3 dotted indigo bags.");
lines.push("clear teal bags contain 2 posh chartreuse bags, 2 posh blue bags.");
lines.push("dull green bags contain 5 muted tan bags, 3 faded gray bags, 2 dark tan bags.");
lines.push("dotted yellow bags contain 1 dim aqua bag, 5 dotted blue bags, 1 plaid teal bag, 2 dim salmon bags.");
lines.push("dotted indigo bags contain 1 muted red bag.");
lines.push("pale gold bags contain 1 mirrored green bag, 2 faded gray bags, 4 drab olive bags.");
lines.push("pale magenta bags contain 1 pale gray bag.");
lines.push("drab orange bags contain 4 dull beige bags, 1 dim gray bag.");
lines.push("light maroon bags contain no other bags.");
lines.push("dim silver bags contain 2 dull olive bags, 2 muted lavender bags, 5 dark fuchsia bags, 5 dotted tan bags.");
lines.push("shiny magenta bags contain 5 light purple bags.");
lines.push("shiny green bags contain 2 dim green bags, 1 pale plum bag, 2 striped teal bags.");
lines.push("drab magenta bags contain 1 plaid yellow bag, 3 bright crimson bags, 4 shiny salmon bags.");
lines.push("shiny salmon bags contain 4 dark bronze bags, 1 pale aqua bag, 5 posh red bags, 2 light gold bags.");
lines.push("mirrored cyan bags contain 2 bright olive bags, 2 bright aqua bags, 4 shiny turquoise bags.");
lines.push("drab aqua bags contain 1 drab olive bag, 5 shiny white bags, 2 dim gray bags.");
lines.push("wavy white bags contain 1 plaid red bag.");
lines.push("clear black bags contain 1 dim fuchsia bag, 5 pale white bags, 3 drab fuchsia bags.");
lines.push("dotted cyan bags contain 3 wavy aqua bags, 4 shiny brown bags, 4 faded tan bags.");
lines.push("dim magenta bags contain 4 striped orange bags, 2 mirrored turquoise bags, 3 vibrant turquoise bags, 3 pale chartreuse bags.");
lines.push("faded silver bags contain 5 dim fuchsia bags, 2 bright purple bags.");
lines.push("faded olive bags contain 3 dull lavender bags, 2 striped salmon bags, 1 bright yellow bag.");
lines.push("faded lime bags contain 4 posh tan bags, 4 dotted lavender bags, 3 striped magenta bags.");
lines.push("dark white bags contain 2 bright beige bags, 3 shiny chartreuse bags.");
lines.push("striped brown bags contain 5 muted lavender bags.");
lines.push("dotted lime bags contain 1 mirrored green bag, 4 dotted chartreuse bags, 2 shiny cyan bags, 1 bright purple bag.");
lines.push("bright beige bags contain 4 dull gray bags, 3 wavy violet bags, 5 light silver bags, 5 drab white bags.");
lines.push("dark beige bags contain 3 light gold bags, 1 muted tomato bag, 4 pale teal bags, 4 posh crimson bags.");
lines.push("dim olive bags contain 4 dark cyan bags.");
lines.push("plaid plum bags contain 1 clear tan bag, 4 posh brown bags.");
lines.push("wavy magenta bags contain 4 dotted plum bags, 2 dull tan bags.");
lines.push("drab gold bags contain 4 dark cyan bags, 2 clear yellow bags.");
lines.push("muted orange bags contain 2 faded tan bags, 5 vibrant salmon bags.");
lines.push("pale yellow bags contain 3 light turquoise bags, 3 plaid maroon bags, 2 dull salmon bags.");
lines.push("plaid tomato bags contain 2 dark beige bags.");
lines.push("dim purple bags contain 5 posh salmon bags, 2 dim lime bags, 2 dotted white bags.");
lines.push("bright red bags contain 4 dark teal bags, 3 shiny cyan bags.");
lines.push("bright salmon bags contain 4 pale aqua bags, 3 clear orange bags, 3 plaid black bags, 5 faded aqua bags.");
lines.push("plaid crimson bags contain 4 plaid tan bags, 4 dim aqua bags.");
lines.push("striped violet bags contain 2 dotted olive bags, 2 dotted red bags, 4 shiny gold bags.");
lines.push("vibrant tomato bags contain 3 dim lime bags.");
lines.push("drab turquoise bags contain 5 shiny purple bags, 1 light green bag, 1 pale chartreuse bag.");
lines.push("wavy turquoise bags contain 1 dark teal bag, 5 shiny fuchsia bags, 4 muted brown bags, 4 bright green bags.");
lines.push("striped plum bags contain 3 bright chartreuse bags, 1 dotted violet bag, 1 posh maroon bag.");
lines.push("mirrored plum bags contain 4 plaid indigo bags, 5 dotted white bags.");
lines.push("muted salmon bags contain 5 faded magenta bags, 3 plaid blue bags.");
lines.push("shiny brown bags contain 3 drab salmon bags.");
lines.push("drab blue bags contain 3 drab olive bags, 5 muted red bags, 2 bright purple bags.");
lines.push("striped gray bags contain 3 clear olive bags, 2 muted coral bags.");
lines.push("bright yellow bags contain 2 dull olive bags, 5 dark turquoise bags, 5 posh teal bags.");
lines.push("dim plum bags contain 2 dim cyan bags, 5 vibrant crimson bags.");
lines.push("muted lavender bags contain 2 clear bronze bags.");
lines.push("muted silver bags contain 3 vibrant salmon bags, 5 muted cyan bags, 1 dotted black bag.");
lines.push("mirrored orange bags contain 2 dull olive bags, 4 striped beige bags, 3 shiny aqua bags, 2 striped salmon bags.");
lines.push("dim teal bags contain 2 drab blue bags.");
lines.push("plaid brown bags contain 1 pale maroon bag, 4 light salmon bags, 1 vibrant indigo bag, 5 clear cyan bags.");
lines.push("bright chartreuse bags contain 4 plaid coral bags, 2 dull crimson bags, 3 plaid aqua bags, 2 faded blue bags.");
lines.push("dotted gray bags contain 1 dotted indigo bag, 2 posh crimson bags.");
lines.push("drab indigo bags contain 1 dotted violet bag, 1 dim fuchsia bag, 4 muted red bags, 4 striped maroon bags.");
lines.push("plaid bronze bags contain 3 drab plum bags, 1 posh violet bag, 2 dark tan bags, 3 plaid white bags.");
lines.push("striped salmon bags contain 3 clear brown bags.");
lines.push("dull lavender bags contain 4 pale green bags.");
lines.push("dull gray bags contain 4 drab indigo bags, 4 light salmon bags, 2 plaid coral bags, 3 striped magenta bags.");
lines.push("mirrored purple bags contain 2 vibrant brown bags, 1 plaid teal bag, 4 drab red bags, 4 plaid turquoise bags.");
lines.push("dull gold bags contain 3 drab teal bags.");
lines.push("light fuchsia bags contain 2 clear tan bags, 1 posh tan bag.");
lines.push("dim white bags contain 1 bright beige bag.");
lines.push("light green bags contain 1 dotted red bag, 4 muted gray bags, 5 dotted orange bags, 3 dim chartreuse bags.");
lines.push("bright teal bags contain 5 bright bronze bags, 2 pale green bags.");
lines.push("striped purple bags contain 1 dark beige bag.");
lines.push("muted tan bags contain 4 pale silver bags, 2 bright lavender bags, 4 drab cyan bags.");
lines.push("light blue bags contain 5 drab white bags, 1 pale olive bag.");
lines.push("dim cyan bags contain 1 wavy fuchsia bag, 5 posh teal bags.");
lines.push("striped chartreuse bags contain 4 bright beige bags, 1 muted lavender bag.");
lines.push("light lavender bags contain 2 posh lavender bags, 1 dim lavender bag.");
lines.push("striped gold bags contain 1 posh salmon bag, 3 mirrored gray bags, 1 faded silver bag.");
lines.push("light orange bags contain 4 dark black bags.");
lines.push("plaid silver bags contain 5 posh salmon bags, 3 vibrant tomato bags.");
lines.push("dotted white bags contain 3 dim fuchsia bags, 4 shiny gold bags, 2 bright olive bags, 4 muted purple bags.");
lines.push("faded bronze bags contain 3 pale green bags, 3 light yellow bags, 1 clear teal bag.");
lines.push("striped turquoise bags contain 4 mirrored aqua bags, 2 wavy orange bags, 1 pale lavender bag, 4 drab aqua bags.");
lines.push("clear lime bags contain 1 plaid green bag, 3 pale gold bags, 2 bright gray bags.");
lines.push("drab salmon bags contain 3 dull tomato bags.");
lines.push("plaid red bags contain 5 pale brown bags.");
lines.push("posh coral bags contain 2 dim violet bags, 4 dotted teal bags, 2 plaid red bags, 4 muted green bags.");
lines.push("light bronze bags contain 4 light purple bags.");
lines.push("faded orange bags contain 2 light teal bags.");
lines.push("dotted lavender bags contain 2 light olive bags, 3 muted tomato bags.");
lines.push("bright orange bags contain 3 light gray bags, 4 striped purple bags, 5 dull tomato bags.");
lines.push("mirrored coral bags contain 3 faded gray bags, 5 pale green bags, 4 pale aqua bags, 4 muted bronze bags.");
lines.push("dull plum bags contain 4 posh crimson bags, 4 clear cyan bags, 4 shiny white bags, 2 dotted maroon bags.");
lines.push("shiny blue bags contain 5 dim lime bags, 2 dim gray bags, 5 dark cyan bags, 3 posh teal bags.");
lines.push("mirrored fuchsia bags contain 4 muted tomato bags, 5 dotted chartreuse bags, 1 light red bag, 2 bright yellow bags.");
lines.push("dotted teal bags contain 1 dotted gray bag, 1 muted brown bag.");
lines.push("mirrored tan bags contain 2 clear aqua bags, 4 dim violet bags, 1 wavy gray bag.");
lines.push("posh chartreuse bags contain 2 faded blue bags, 4 dark coral bags, 2 light maroon bags, 5 dark purple bags.");
lines.push("shiny tan bags contain 1 wavy salmon bag, 2 shiny red bags, 5 clear coral bags, 3 wavy gold bags.");
lines.push("vibrant salmon bags contain 3 clear brown bags, 3 pale gold bags, 5 clear blue bags.");
lines.push("plaid beige bags contain 5 vibrant lavender bags, 2 dim brown bags, 4 dull yellow bags.");
lines.push("muted olive bags contain 3 vibrant blue bags, 5 shiny crimson bags, 5 pale beige bags, 2 dotted chartreuse bags.");
lines.push("clear beige bags contain 4 drab coral bags, 4 dark maroon bags, 1 light indigo bag.");
lines.push("dull fuchsia bags contain 2 pale magenta bags, 1 dotted indigo bag.");
lines.push("dark gold bags contain 3 posh crimson bags, 3 mirrored lavender bags.");
lines.push("pale plum bags contain 1 light bronze bag, 5 dotted violet bags, 2 dark salmon bags.");
lines.push("drab fuchsia bags contain 4 dull brown bags, 5 muted bronze bags.");
lines.push("mirrored black bags contain 1 muted silver bag, 3 plaid gray bags, 4 bright purple bags.");
lines.push("posh blue bags contain 3 dull beige bags, 5 dull olive bags.");
lines.push("posh beige bags contain 3 vibrant turquoise bags, 3 dotted lime bags.");
lines.push("light aqua bags contain 2 mirrored teal bags, 1 vibrant lime bag, 1 dim olive bag.");
lines.push("muted tomato bags contain 5 dim lavender bags.");
lines.push("dim coral bags contain 4 shiny magenta bags, 4 drab violet bags, 5 clear brown bags.");

var i, j = lines.length, rslt;
const r = RegExp(/(\w+ \w+) bags contain (.+)/);

var containers={};
console.log("var graph = new DepGraph();");
for (i = 0; i < j; i++) {
  var line=lines[i];
  var rslt = line.match(r);
  if(rslt!=null) {
    var who=rslt[1];
    console.log("graph.addNode('"+who+"')");
    var what=rslt[2];
    var dd={};
    var t=what.split(", ");
    for (x in t) {
      t[x]=t[x].replace(/\d+ (\w+ \w+) .+/,"$1");
      console.log("graph.addDependency('"+who+"', '"+t[x]+"')");
      dd[t[x]]=t[x];
    }
  }
  containers[who]=dd;
}

// This code generates JS code.
// It needs to be sorted alphabetically with
// graph.addNode() lines first.
// --> Day07Part1.js