/*

Input was converted to JS code via regex and JS,
producing 2 lines, a graph.addNode() instruction
and a graph.addDependency() instruction.

Since all nodes need to be added first, I then sorted the
lines alphabetically, putting all the graph.addDependency
at the bottom. The code is in Day07Prep.js.

The only code that matters then is:

var t=graph.dependenciesOf('shiny gold');
console.log(t.length, t);

> node Day07Part1.js
is all that's required.

*/
var DepGraph = require('dependency-graph').DepGraph;
var graph = new DepGraph();
graph.addNode('bright aqua');
graph.addNode('bright beige');
graph.addNode('bright black');
graph.addNode('bright blue');
graph.addNode('bright bronze');
graph.addNode('bright brown');
graph.addNode('bright chartreuse');
graph.addNode('bright coral');
graph.addNode('bright crimson');
graph.addNode('bright cyan');
graph.addNode('bright fuchsia');
graph.addNode('bright gold');
graph.addNode('bright gray');
graph.addNode('bright green');
graph.addNode('bright indigo');
graph.addNode('bright lavender');
graph.addNode('bright lime');
graph.addNode('bright magenta');
graph.addNode('bright maroon');
graph.addNode('bright olive');
graph.addNode('bright orange');
graph.addNode('bright plum');
graph.addNode('bright purple');
graph.addNode('bright red');
graph.addNode('bright salmon');
graph.addNode('bright silver');
graph.addNode('bright tan');
graph.addNode('bright teal');
graph.addNode('bright tomato');
graph.addNode('bright turquoise');
graph.addNode('bright violet');
graph.addNode('bright white');
graph.addNode('bright yellow');
graph.addNode('clear aqua');
graph.addNode('clear beige');
graph.addNode('clear black');
graph.addNode('clear blue');
graph.addNode('clear bronze');
graph.addNode('clear brown');
graph.addNode('clear chartreuse');
graph.addNode('clear coral');
graph.addNode('clear crimson');
graph.addNode('clear cyan');
graph.addNode('clear fuchsia');
graph.addNode('clear gold');
graph.addNode('clear gray');
graph.addNode('clear green');
graph.addNode('clear indigo');
graph.addNode('clear lavender');
graph.addNode('clear lime');
graph.addNode('clear magenta');
graph.addNode('clear maroon');
graph.addNode('clear olive');
graph.addNode('clear orange');
graph.addNode('clear plum');
graph.addNode('clear purple');
graph.addNode('clear red');
graph.addNode('clear salmon');
graph.addNode('clear silver');
graph.addNode('clear tan');
graph.addNode('clear teal');
graph.addNode('clear tomato');
graph.addNode('clear turquoise');
graph.addNode('clear violet');
graph.addNode('clear white');
graph.addNode('clear yellow');
graph.addNode('dark aqua');
graph.addNode('dark beige');
graph.addNode('dark black');
graph.addNode('dark blue');
graph.addNode('dark bronze');
graph.addNode('dark brown');
graph.addNode('dark chartreuse');
graph.addNode('dark coral');
graph.addNode('dark crimson');
graph.addNode('dark cyan');
graph.addNode('dark fuchsia');
graph.addNode('dark gold');
graph.addNode('dark gray');
graph.addNode('dark green');
graph.addNode('dark indigo');
graph.addNode('dark lavender');
graph.addNode('dark lime');
graph.addNode('dark magenta');
graph.addNode('dark maroon');
graph.addNode('dark olive');
graph.addNode('dark orange');
graph.addNode('dark plum');
graph.addNode('dark purple');
graph.addNode('dark red');
graph.addNode('dark salmon');
graph.addNode('dark silver');
graph.addNode('dark tan');
graph.addNode('dark teal');
graph.addNode('dark tomato');
graph.addNode('dark turquoise');
graph.addNode('dark violet');
graph.addNode('dark white');
graph.addNode('dark yellow');
graph.addNode('dim aqua');
graph.addNode('dim beige');
graph.addNode('dim black');
graph.addNode('dim blue');
graph.addNode('dim bronze');
graph.addNode('dim brown');
graph.addNode('dim chartreuse');
graph.addNode('dim coral');
graph.addNode('dim crimson');
graph.addNode('dim cyan');
graph.addNode('dim fuchsia');
graph.addNode('dim gold');
graph.addNode('dim gray');
graph.addNode('dim green');
graph.addNode('dim indigo');
graph.addNode('dim lavender');
graph.addNode('dim lime');
graph.addNode('dim magenta');
graph.addNode('dim maroon');
graph.addNode('dim olive');
graph.addNode('dim orange');
graph.addNode('dim plum');
graph.addNode('dim purple');
graph.addNode('dim red');
graph.addNode('dim salmon');
graph.addNode('dim silver');
graph.addNode('dim tan');
graph.addNode('dim teal');
graph.addNode('dim tomato');
graph.addNode('dim turquoise');
graph.addNode('dim violet');
graph.addNode('dim white');
graph.addNode('dim yellow');
graph.addNode('dotted aqua');
graph.addNode('dotted beige');
graph.addNode('dotted black');
graph.addNode('dotted blue');
graph.addNode('dotted bronze');
graph.addNode('dotted brown');
graph.addNode('dotted chartreuse');
graph.addNode('dotted coral');
graph.addNode('dotted crimson');
graph.addNode('dotted cyan');
graph.addNode('dotted fuchsia');
graph.addNode('dotted gold');
graph.addNode('dotted gray');
graph.addNode('dotted green');
graph.addNode('dotted indigo');
graph.addNode('dotted lavender');
graph.addNode('dotted lime');
graph.addNode('dotted magenta');
graph.addNode('dotted maroon');
graph.addNode('dotted olive');
graph.addNode('dotted orange');
graph.addNode('dotted plum');
graph.addNode('dotted purple');
graph.addNode('dotted red');
graph.addNode('dotted salmon');
graph.addNode('dotted silver');
graph.addNode('dotted tan');
graph.addNode('dotted teal');
graph.addNode('dotted tomato');
graph.addNode('dotted turquoise');
graph.addNode('dotted violet');
graph.addNode('dotted white');
graph.addNode('dotted yellow');
graph.addNode('drab aqua');
graph.addNode('drab beige');
graph.addNode('drab black');
graph.addNode('drab blue');
graph.addNode('drab bronze');
graph.addNode('drab brown');
graph.addNode('drab chartreuse');
graph.addNode('drab coral');
graph.addNode('drab crimson');
graph.addNode('drab cyan');
graph.addNode('drab fuchsia');
graph.addNode('drab gold');
graph.addNode('drab gray');
graph.addNode('drab green');
graph.addNode('drab indigo');
graph.addNode('drab lavender');
graph.addNode('drab lime');
graph.addNode('drab magenta');
graph.addNode('drab maroon');
graph.addNode('drab olive');
graph.addNode('drab orange');
graph.addNode('drab plum');
graph.addNode('drab purple');
graph.addNode('drab red');
graph.addNode('drab salmon');
graph.addNode('drab silver');
graph.addNode('drab tan');
graph.addNode('drab teal');
graph.addNode('drab tomato');
graph.addNode('drab turquoise');
graph.addNode('drab violet');
graph.addNode('drab white');
graph.addNode('drab yellow');
graph.addNode('dull aqua');
graph.addNode('dull beige');
graph.addNode('dull black');
graph.addNode('dull blue');
graph.addNode('dull bronze');
graph.addNode('dull brown');
graph.addNode('dull chartreuse');
graph.addNode('dull coral');
graph.addNode('dull crimson');
graph.addNode('dull cyan');
graph.addNode('dull fuchsia');
graph.addNode('dull gold');
graph.addNode('dull gray');
graph.addNode('dull green');
graph.addNode('dull indigo');
graph.addNode('dull lavender');
graph.addNode('dull lime');
graph.addNode('dull magenta');
graph.addNode('dull maroon');
graph.addNode('dull olive');
graph.addNode('dull orange');
graph.addNode('dull plum');
graph.addNode('dull purple');
graph.addNode('dull red');
graph.addNode('dull salmon');
graph.addNode('dull silver');
graph.addNode('dull tan');
graph.addNode('dull teal');
graph.addNode('dull tomato');
graph.addNode('dull turquoise');
graph.addNode('dull violet');
graph.addNode('dull white');
graph.addNode('dull yellow');
graph.addNode('faded aqua');
graph.addNode('faded beige');
graph.addNode('faded black');
graph.addNode('faded blue');
graph.addNode('faded bronze');
graph.addNode('faded brown');
graph.addNode('faded chartreuse');
graph.addNode('faded coral');
graph.addNode('faded crimson');
graph.addNode('faded cyan');
graph.addNode('faded fuchsia');
graph.addNode('faded gold');
graph.addNode('faded gray');
graph.addNode('faded green');
graph.addNode('faded indigo');
graph.addNode('faded lavender');
graph.addNode('faded lime');
graph.addNode('faded magenta');
graph.addNode('faded maroon');
graph.addNode('faded olive');
graph.addNode('faded orange');
graph.addNode('faded plum');
graph.addNode('faded purple');
graph.addNode('faded red');
graph.addNode('faded salmon');
graph.addNode('faded silver');
graph.addNode('faded tan');
graph.addNode('faded teal');
graph.addNode('faded tomato');
graph.addNode('faded turquoise');
graph.addNode('faded violet');
graph.addNode('faded white');
graph.addNode('faded yellow');
graph.addNode('light aqua');
graph.addNode('light beige');
graph.addNode('light black');
graph.addNode('light blue');
graph.addNode('light bronze');
graph.addNode('light brown');
graph.addNode('light chartreuse');
graph.addNode('light coral');
graph.addNode('light crimson');
graph.addNode('light cyan');
graph.addNode('light fuchsia');
graph.addNode('light gold');
graph.addNode('light gray');
graph.addNode('light green');
graph.addNode('light indigo');
graph.addNode('light lavender');
graph.addNode('light lime');
graph.addNode('light magenta');
graph.addNode('light maroon');
graph.addNode('light olive');
graph.addNode('light orange');
graph.addNode('light plum');
graph.addNode('light purple');
graph.addNode('light red');
graph.addNode('light salmon');
graph.addNode('light silver');
graph.addNode('light tan');
graph.addNode('light teal');
graph.addNode('light tomato');
graph.addNode('light turquoise');
graph.addNode('light violet');
graph.addNode('light white');
graph.addNode('light yellow');
graph.addNode('mirrored aqua');
graph.addNode('mirrored beige');
graph.addNode('mirrored black');
graph.addNode('mirrored blue');
graph.addNode('mirrored bronze');
graph.addNode('mirrored brown');
graph.addNode('mirrored chartreuse');
graph.addNode('mirrored coral');
graph.addNode('mirrored crimson');
graph.addNode('mirrored cyan');
graph.addNode('mirrored fuchsia');
graph.addNode('mirrored gold');
graph.addNode('mirrored gray');
graph.addNode('mirrored green');
graph.addNode('mirrored indigo');
graph.addNode('mirrored lavender');
graph.addNode('mirrored lime');
graph.addNode('mirrored magenta');
graph.addNode('mirrored maroon');
graph.addNode('mirrored olive');
graph.addNode('mirrored orange');
graph.addNode('mirrored plum');
graph.addNode('mirrored purple');
graph.addNode('mirrored red');
graph.addNode('mirrored salmon');
graph.addNode('mirrored silver');
graph.addNode('mirrored tan');
graph.addNode('mirrored teal');
graph.addNode('mirrored tomato');
graph.addNode('mirrored turquoise');
graph.addNode('mirrored violet');
graph.addNode('mirrored white');
graph.addNode('mirrored yellow');
graph.addNode('muted aqua');
graph.addNode('muted beige');
graph.addNode('muted black');
graph.addNode('muted blue');
graph.addNode('muted bronze');
graph.addNode('muted brown');
graph.addNode('muted chartreuse');
graph.addNode('muted coral');
graph.addNode('muted crimson');
graph.addNode('muted cyan');
graph.addNode('muted fuchsia');
graph.addNode('muted gold');
graph.addNode('muted gray');
graph.addNode('muted green');
graph.addNode('muted indigo');
graph.addNode('muted lavender');
graph.addNode('muted lime');
graph.addNode('muted magenta');
graph.addNode('muted maroon');
graph.addNode('muted olive');
graph.addNode('muted orange');
graph.addNode('muted plum');
graph.addNode('muted purple');
graph.addNode('muted red');
graph.addNode('muted salmon');
graph.addNode('muted silver');
graph.addNode('muted tan');
graph.addNode('muted teal');
graph.addNode('muted tomato');
graph.addNode('muted turquoise');
graph.addNode('muted violet');
graph.addNode('muted white');
graph.addNode('muted yellow');
graph.addNode('pale aqua');
graph.addNode('pale beige');
graph.addNode('pale black');
graph.addNode('pale blue');
graph.addNode('pale bronze');
graph.addNode('pale brown');
graph.addNode('pale chartreuse');
graph.addNode('pale coral');
graph.addNode('pale crimson');
graph.addNode('pale cyan');
graph.addNode('pale fuchsia');
graph.addNode('pale gold');
graph.addNode('pale gray');
graph.addNode('pale green');
graph.addNode('pale indigo');
graph.addNode('pale lavender');
graph.addNode('pale lime');
graph.addNode('pale magenta');
graph.addNode('pale maroon');
graph.addNode('pale olive');
graph.addNode('pale orange');
graph.addNode('pale plum');
graph.addNode('pale purple');
graph.addNode('pale red');
graph.addNode('pale salmon');
graph.addNode('pale silver');
graph.addNode('pale tan');
graph.addNode('pale teal');
graph.addNode('pale tomato');
graph.addNode('pale turquoise');
graph.addNode('pale violet');
graph.addNode('pale white');
graph.addNode('pale yellow');
graph.addNode('plaid aqua');
graph.addNode('plaid beige');
graph.addNode('plaid black');
graph.addNode('plaid blue');
graph.addNode('plaid bronze');
graph.addNode('plaid brown');
graph.addNode('plaid chartreuse');
graph.addNode('plaid coral');
graph.addNode('plaid crimson');
graph.addNode('plaid cyan');
graph.addNode('plaid fuchsia');
graph.addNode('plaid gold');
graph.addNode('plaid gray');
graph.addNode('plaid green');
graph.addNode('plaid indigo');
graph.addNode('plaid lavender');
graph.addNode('plaid lime');
graph.addNode('plaid magenta');
graph.addNode('plaid maroon');
graph.addNode('plaid olive');
graph.addNode('plaid orange');
graph.addNode('plaid plum');
graph.addNode('plaid purple');
graph.addNode('plaid red');
graph.addNode('plaid salmon');
graph.addNode('plaid silver');
graph.addNode('plaid tan');
graph.addNode('plaid teal');
graph.addNode('plaid tomato');
graph.addNode('plaid turquoise');
graph.addNode('plaid violet');
graph.addNode('plaid white');
graph.addNode('plaid yellow');
graph.addNode('posh aqua');
graph.addNode('posh beige');
graph.addNode('posh black');
graph.addNode('posh blue');
graph.addNode('posh bronze');
graph.addNode('posh brown');
graph.addNode('posh chartreuse');
graph.addNode('posh coral');
graph.addNode('posh crimson');
graph.addNode('posh cyan');
graph.addNode('posh fuchsia');
graph.addNode('posh gold');
graph.addNode('posh gray');
graph.addNode('posh green');
graph.addNode('posh indigo');
graph.addNode('posh lavender');
graph.addNode('posh lime');
graph.addNode('posh magenta');
graph.addNode('posh maroon');
graph.addNode('posh olive');
graph.addNode('posh orange');
graph.addNode('posh plum');
graph.addNode('posh purple');
graph.addNode('posh red');
graph.addNode('posh salmon');
graph.addNode('posh silver');
graph.addNode('posh tan');
graph.addNode('posh teal');
graph.addNode('posh tomato');
graph.addNode('posh turquoise');
graph.addNode('posh violet');
graph.addNode('posh white');
graph.addNode('posh yellow');
graph.addNode('shiny aqua');
graph.addNode('shiny beige');
graph.addNode('shiny black');
graph.addNode('shiny blue');
graph.addNode('shiny bronze');
graph.addNode('shiny brown');
graph.addNode('shiny chartreuse');
graph.addNode('shiny coral');
graph.addNode('shiny crimson');
graph.addNode('shiny cyan');
graph.addNode('shiny fuchsia');
graph.addNode('shiny gold');
graph.addNode('shiny gray');
graph.addNode('shiny green');
graph.addNode('shiny indigo');
graph.addNode('shiny lavender');
graph.addNode('shiny lime');
graph.addNode('shiny magenta');
graph.addNode('shiny maroon');
graph.addNode('shiny olive');
graph.addNode('shiny orange');
graph.addNode('shiny plum');
graph.addNode('shiny purple');
graph.addNode('shiny red');
graph.addNode('shiny salmon');
graph.addNode('shiny silver');
graph.addNode('shiny tan');
graph.addNode('shiny teal');
graph.addNode('shiny tomato');
graph.addNode('shiny turquoise');
graph.addNode('shiny violet');
graph.addNode('shiny white');
graph.addNode('shiny yellow');
graph.addNode('striped aqua');
graph.addNode('striped beige');
graph.addNode('striped black');
graph.addNode('striped blue');
graph.addNode('striped bronze');
graph.addNode('striped brown');
graph.addNode('striped chartreuse');
graph.addNode('striped coral');
graph.addNode('striped crimson');
graph.addNode('striped cyan');
graph.addNode('striped fuchsia');
graph.addNode('striped gold');
graph.addNode('striped gray');
graph.addNode('striped green');
graph.addNode('striped indigo');
graph.addNode('striped lavender');
graph.addNode('striped lime');
graph.addNode('striped magenta');
graph.addNode('striped maroon');
graph.addNode('striped olive');
graph.addNode('striped orange');
graph.addNode('striped plum');
graph.addNode('striped purple');
graph.addNode('striped red');
graph.addNode('striped salmon');
graph.addNode('striped silver');
graph.addNode('striped tan');
graph.addNode('striped teal');
graph.addNode('striped tomato');
graph.addNode('striped turquoise');
graph.addNode('striped violet');
graph.addNode('striped white');
graph.addNode('striped yellow');
graph.addNode('vibrant aqua');
graph.addNode('vibrant beige');
graph.addNode('vibrant black');
graph.addNode('vibrant blue');
graph.addNode('vibrant bronze');
graph.addNode('vibrant brown');
graph.addNode('vibrant chartreuse');
graph.addNode('vibrant coral');
graph.addNode('vibrant crimson');
graph.addNode('vibrant cyan');
graph.addNode('vibrant fuchsia');
graph.addNode('vibrant gold');
graph.addNode('vibrant gray');
graph.addNode('vibrant green');
graph.addNode('vibrant indigo');
graph.addNode('vibrant lavender');
graph.addNode('vibrant lime');
graph.addNode('vibrant magenta');
graph.addNode('vibrant maroon');
graph.addNode('vibrant olive');
graph.addNode('vibrant orange');
graph.addNode('vibrant plum');
graph.addNode('vibrant purple');
graph.addNode('vibrant red');
graph.addNode('vibrant salmon');
graph.addNode('vibrant silver');
graph.addNode('vibrant tan');
graph.addNode('vibrant teal');
graph.addNode('vibrant tomato');
graph.addNode('vibrant turquoise');
graph.addNode('vibrant violet');
graph.addNode('vibrant white');
graph.addNode('vibrant yellow');
graph.addNode('wavy aqua');
graph.addNode('wavy beige');
graph.addNode('wavy black');
graph.addNode('wavy blue');
graph.addNode('wavy bronze');
graph.addNode('wavy brown');
graph.addNode('wavy chartreuse');
graph.addNode('wavy coral');
graph.addNode('wavy crimson');
graph.addNode('wavy cyan');
graph.addNode('wavy fuchsia');
graph.addNode('wavy gold');
graph.addNode('wavy gray');
graph.addNode('wavy green');
graph.addNode('wavy indigo');
graph.addNode('wavy lavender');
graph.addNode('wavy lime');
graph.addNode('wavy magenta');
graph.addNode('wavy maroon');
graph.addNode('wavy olive');
graph.addNode('wavy orange');
graph.addNode('wavy plum');
graph.addNode('wavy purple');
graph.addNode('wavy red');
graph.addNode('wavy salmon');
graph.addNode('wavy silver');
graph.addNode('wavy tan');
graph.addNode('wavy teal');
graph.addNode('wavy tomato');
graph.addNode('wavy turquoise');
graph.addNode('wavy violet');
graph.addNode('wavy white');
graph.addNode('wavy yellow');
graph.addDependency('dim green', 'bright aqua');
graph.addDependency('faded olive', 'bright aqua');
graph.addDependency('striped tan', 'bright aqua');
graph.addDependency('drab white', 'bright beige');
graph.addDependency('dull gray', 'bright beige');
graph.addDependency('light silver', 'bright beige');
graph.addDependency('wavy violet', 'bright beige');
graph.addDependency('drab teal', 'bright black');
graph.addDependency('dull gray', 'bright black');
graph.addDependency('pale blue', 'bright black');
graph.addDependency('light teal', 'bright blue');
graph.addDependency('pale beige', 'bright blue');
graph.addDependency('plaid red', 'bright bronze');
graph.addDependency('striped yellow', 'bright bronze');
graph.addDependency('striped bronze', 'bright brown');
graph.addDependency('dull crimson', 'bright chartreuse');
graph.addDependency('faded blue', 'bright chartreuse');
graph.addDependency('plaid aqua', 'bright chartreuse');
graph.addDependency('plaid coral', 'bright chartreuse');
graph.addDependency('posh gold', 'bright coral');
graph.addDependency('vibrant crimson', 'bright coral');
graph.addDependency('dotted indigo', 'bright crimson');
graph.addDependency('clear silver', 'bright cyan');
graph.addDependency('dark maroon', 'bright cyan');
graph.addDependency('striped maroon', 'bright cyan');
graph.addDependency('dark indigo', 'bright fuchsia');
graph.addDependency('dull crimson', 'bright fuchsia');
graph.addDependency('faded lavender', 'bright fuchsia');
graph.addDependency('mirrored brown', 'bright fuchsia');
graph.addDependency('posh plum', 'bright gold');
graph.addDependency('posh tan', 'bright gray');
graph.addDependency('striped gold', 'bright green');
graph.addDependency('shiny lime', 'bright indigo');
graph.addDependency('striped beige', 'bright indigo');
graph.addDependency('clear indigo', 'bright lavender');
graph.addDependency('dotted violet', 'bright lavender');
graph.addDependency('faded indigo', 'bright lavender');
graph.addDependency('posh tomato', 'bright lavender');
graph.addDependency('bright cyan', 'bright lime');
graph.addDependency('dark salmon', 'bright lime');
graph.addDependency('posh violet', 'bright lime');
graph.addDependency('striped black', 'bright lime');
graph.addDependency('light purple', 'bright magenta');
graph.addDependency('plaid coral', 'bright magenta');
graph.addDependency('shiny aqua', 'bright magenta');
graph.addDependency('dark magenta', 'bright maroon');
graph.addDependency('dim maroon', 'bright maroon');
graph.addDependency('dotted teal', 'bright maroon');
graph.addDependency('wavy fuchsia', 'bright maroon');
graph.addDependency('dull tomato', 'bright orange');
graph.addDependency('light gray', 'bright orange');
graph.addDependency('striped purple', 'bright orange');
graph.addDependency('dim orange', 'bright plum');
graph.addDependency('muted yellow', 'bright plum');
graph.addDependency('posh brown', 'bright plum');
graph.addDependency('posh chartreuse', 'bright plum');
graph.addDependency('dotted violet', 'bright purple');
graph.addDependency('light maroon', 'bright purple');
graph.addDependency('dark teal', 'bright red');
graph.addDependency('shiny cyan', 'bright red');
graph.addDependency('clear orange', 'bright salmon');
graph.addDependency('faded aqua', 'bright salmon');
graph.addDependency('pale aqua', 'bright salmon');
graph.addDependency('plaid black', 'bright salmon');
graph.addDependency('faded gray', 'bright silver');
graph.addDependency('light gold', 'bright silver');
graph.addDependency('posh tan', 'bright silver');
graph.addDependency('clear indigo', 'bright tan');
graph.addDependency('pale orange', 'bright tan');
graph.addDependency('bright bronze', 'bright teal');
graph.addDependency('pale green', 'bright teal');
graph.addDependency('muted white', 'bright tomato');
graph.addDependency('pale yellow', 'bright turquoise');
graph.addDependency('plaid yellow', 'bright turquoise');
graph.addDependency('posh lavender', 'bright turquoise');
graph.addDependency('dark coral', 'bright violet');
graph.addDependency('dull beige', 'bright violet');
graph.addDependency('light olive', 'bright violet');
graph.addDependency('plaid maroon', 'bright violet');
graph.addDependency('dark turquoise', 'bright white');
graph.addDependency('dark turquoise', 'bright yellow');
graph.addDependency('dull olive', 'bright yellow');
graph.addDependency('posh teal', 'bright yellow');
graph.addDependency('dim green', 'clear aqua');
graph.addDependency('wavy fuchsia', 'clear aqua');
graph.addDependency('dark maroon', 'clear beige');
graph.addDependency('drab coral', 'clear beige');
graph.addDependency('light indigo', 'clear beige');
graph.addDependency('dim fuchsia', 'clear black');
graph.addDependency('drab fuchsia', 'clear black');
graph.addDependency('pale white', 'clear black');
graph.addDependency('dull purple', 'clear blue');
graph.addDependency('plaid brown', 'clear bronze');
graph.addDependency('drab red', 'clear brown');
graph.addDependency('plaid aqua', 'clear brown');
graph.addDependency('plaid coral', 'clear brown');
graph.addDependency('dark brown', 'clear chartreuse');
graph.addDependency('dark coral', 'clear chartreuse');
graph.addDependency('pale lavender', 'clear chartreuse');
graph.addDependency('drab tomato', 'clear coral');
graph.addDependency('dotted tomato', 'clear crimson');
graph.addDependency('posh crimson', 'clear crimson');
graph.addDependency('vibrant magenta', 'clear crimson');
graph.addDependency('dim lavender', 'clear cyan');
graph.addDependency('light maroon', 'clear cyan');
graph.addDependency('posh tan', 'clear cyan');
graph.addDependency('dotted chartreuse', 'clear fuchsia');
graph.addDependency('muted red', 'clear fuchsia');
graph.addDependency('pale plum', 'clear fuchsia');
graph.addDependency('dark beige', 'clear gold');
graph.addDependency('posh tan', 'clear gold');
graph.addDependency('striped gold', 'clear gold');
graph.addDependency('faded coral', 'clear gray');
graph.addDependency('muted lavender', 'clear gray');
graph.addDependency('pale crimson', 'clear gray');
graph.addDependency('striped violet', 'clear gray');
graph.addDependency('shiny aqua', 'clear green');
graph.addDependency('striped maroon', 'clear green');
graph.addDependency('dark coral', 'clear indigo');
graph.addDependency('dim lime', 'clear indigo');
graph.addDependency('pale green', 'clear indigo');
graph.addDependency('plaid orange', 'clear indigo');
graph.addDependency('posh red', 'clear lavender');
graph.addDependency('vibrant black', 'clear lavender');
graph.addDependency('bright gray', 'clear lime');
graph.addDependency('pale gold', 'clear lime');
graph.addDependency('plaid green', 'clear lime');
graph.addDependency('pale blue', 'clear magenta');
graph.addDependency('pale crimson', 'clear magenta');
graph.addDependency('clear brown', 'clear maroon');
graph.addDependency('drab orange', 'clear maroon');
graph.addDependency('shiny red', 'clear maroon');
graph.addDependency('bright purple', 'clear olive');
graph.addDependency('dim fuchsia', 'clear olive');
graph.addDependency('dim lime', 'clear olive');
graph.addDependency('bright silver', 'clear orange');
graph.addDependency('dotted orange', 'clear orange');
graph.addDependency('dotted tomato', 'clear orange');
graph.addDependency('striped purple', 'clear orange');
graph.addDependency('drab indigo', 'clear plum');
graph.addDependency('pale maroon', 'clear plum');
graph.addDependency('dull fuchsia', 'clear purple');
graph.addDependency('dim tan', 'clear red');
graph.addDependency('dotted brown', 'clear red');
graph.addDependency('striped orange', 'clear red');
graph.addDependency('dull green', 'clear salmon');
graph.addDependency('muted bronze', 'clear salmon');
graph.addDependency('pale brown', 'clear salmon');
graph.addDependency('plaid fuchsia', 'clear salmon');
graph.addDependency('plaid olive', 'clear silver');
graph.addDependency('clear cyan', 'clear tan');
graph.addDependency('dull lime', 'clear tan');
graph.addDependency('muted red', 'clear tan');
graph.addDependency('posh blue', 'clear teal');
graph.addDependency('posh chartreuse', 'clear teal');
graph.addDependency('dark black', 'clear tomato');
graph.addDependency('dull white', 'clear tomato');
graph.addDependency('mirrored gold', 'clear tomato');
graph.addDependency('posh tomato', 'clear turquoise');
graph.addDependency('shiny aqua', 'clear turquoise');
graph.addDependency('plaid green', 'clear violet');
graph.addDependency('shiny blue', 'clear white');
graph.addDependency('faded black', 'clear yellow');
graph.addDependency('faded silver', 'clear yellow');
graph.addDependency('vibrant fuchsia', 'clear yellow');
graph.addDependency('bright purple', 'dark aqua');
graph.addDependency('striped gold', 'dark aqua');
graph.addDependency('light gold', 'dark beige');
graph.addDependency('muted tomato', 'dark beige');
graph.addDependency('pale teal', 'dark beige');
graph.addDependency('posh crimson', 'dark beige');
graph.addDependency('dim teal', 'dark black');
graph.addDependency('faded gold', 'dark black');
graph.addDependency('striped purple', 'dark black');
graph.addDependency('dim gold', 'dark blue');
graph.addDependency('drab olive', 'dark blue');
graph.addDependency('light cyan', 'dark blue');
graph.addDependency('light tomato', 'dark blue');
graph.addDependency('posh teal', 'dark bronze');
graph.addDependency('clear olive', 'dark brown');
graph.addDependency('posh tomato', 'dark chartreuse');
graph.addDependency('bright yellow', 'dark coral');
graph.addDependency('mirrored gray', 'dark coral');
graph.addDependency('plaid tomato', 'dark coral');
graph.addDependency('dull plum', 'dark crimson');
graph.addDependency('muted beige', 'dark crimson');
graph.addDependency('muted green', 'dark crimson');
graph.addDependency('posh chartreuse', 'dark crimson');
graph.addDependency('drab red', 'dark cyan');
graph.addDependency('pale maroon', 'dark cyan');
graph.addDependency('faded indigo', 'dark fuchsia');
graph.addDependency('wavy blue', 'dark fuchsia');
graph.addDependency('mirrored lavender', 'dark gold');
graph.addDependency('posh crimson', 'dark gold');
graph.addDependency('striped cyan', 'dark gray');
graph.addDependency('clear tan', 'dark green');
graph.addDependency('pale silver', 'dark green');
graph.addDependency('dull tomato', 'dark indigo');
graph.addDependency('faded silver', 'dark indigo');
graph.addDependency('dim coral', 'dark lavender');
graph.addDependency('muted gray', 'dark lavender');
graph.addDependency('shiny yellow', 'dark lavender');
graph.addDependency('dim yellow', 'dark lime');
graph.addDependency('pale beige', 'dark lime');
graph.addDependency('vibrant beige', 'dark lime');
graph.addDependency('dark black', 'dark magenta');
graph.addDependency('drab blue', 'dark magenta');
graph.addDependency('light white', 'dark magenta');
graph.addDependency('faded green', 'dark maroon');
graph.addDependency('shiny gold', 'dark maroon');
graph.addDependency('mirrored tan', 'dark olive');
graph.addDependency('pale cyan', 'dark olive');
graph.addDependency('dull salmon', 'dark orange');
graph.addDependency('dull yellow', 'dark orange');
graph.addDependency('dim olive', 'dark plum');
graph.addDependency('light salmon', 'dark plum');
graph.addDependency('clear olive', 'dark purple');
graph.addDependency('drab indigo', 'dark purple');
graph.addDependency('striped purple', 'dark purple');
graph.addDependency('wavy violet', 'dark purple');
graph.addDependency('bright chartreuse', 'dark red');
graph.addDependency('dotted chartreuse', 'dark salmon');
graph.addDependency('dotted orange', 'dark salmon');
graph.addDependency('light brown', 'dark salmon');
graph.addDependency('dotted chartreuse', 'dark silver');
graph.addDependency('dull fuchsia', 'dark silver');
graph.addDependency('dark indigo', 'dark tan');
graph.addDependency('dotted tomato', 'dark tan');
graph.addDependency('muted cyan', 'dark tan');
graph.addDependency('mirrored teal', 'dark teal');
graph.addDependency('plaid orange', 'dark teal');
graph.addDependency('posh gold', 'dark teal');
graph.addDependency('vibrant bronze', 'dark teal');
graph.addDependency('posh indigo', 'dark tomato');
graph.addDependency('dim violet', 'dark turquoise');
graph.addDependency('mirrored teal', 'dark turquoise');
graph.addDependency('dark purple', 'dark violet');
graph.addDependency('dim orange', 'dark violet');
graph.addDependency('pale yellow', 'dark violet');
graph.addDependency('bright beige', 'dark white');
graph.addDependency('shiny chartreuse', 'dark white');
graph.addDependency('plaid silver', 'dark yellow');
graph.addDependency('wavy maroon', 'dark yellow');
graph.addDependency('muted purple', 'dim aqua');
graph.addDependency('pale crimson', 'dim aqua');
graph.addDependency('wavy yellow', 'dim aqua');
graph.addDependency('dark lavender', 'dim beige');
graph.addDependency('dim blue', 'dim beige');
graph.addDependency('faded blue', 'dim black');
graph.addDependency('muted tomato', 'dim black');
graph.addDependency('wavy fuchsia', 'dim black');
graph.addDependency('dim black', 'dim blue');
graph.addDependency('dim black', 'dim bronze');
graph.addDependency('drab blue', 'dim bronze');
graph.addDependency('mirrored olive', 'dim bronze');
graph.addDependency('plaid magenta', 'dim bronze');
graph.addDependency('dull teal', 'dim brown');
graph.addDependency('mirrored gold', 'dim brown');
graph.addDependency('vibrant black', 'dim brown');
graph.addDependency('vibrant plum', 'dim chartreuse');
graph.addDependency('clear brown', 'dim coral');
graph.addDependency('drab violet', 'dim coral');
graph.addDependency('shiny magenta', 'dim coral');
graph.addDependency('dark salmon', 'dim crimson');
graph.addDependency('dotted teal', 'dim crimson');
graph.addDependency('posh teal', 'dim cyan');
graph.addDependency('wavy fuchsia', 'dim cyan');
graph.addDependency('mirrored lavender', 'dim gold');
graph.addDependency('pale gray', 'dim gold');
graph.addDependency('dim violet', 'dim gray');
graph.addDependency('dotted indigo', 'dim gray');
graph.addDependency('light olive', 'dim gray');
graph.addDependency('striped magenta', 'dim gray');
graph.addDependency('light red', 'dim indigo');
graph.addDependency('wavy olive', 'dim indigo');
graph.addDependency('striped maroon', 'dim lavender');
graph.addDependency('clear plum', 'dim lime');
graph.addDependency('dim green', 'dim lime');
graph.addDependency('posh tan', 'dim lime');
graph.addDependency('mirrored turquoise', 'dim magenta');
graph.addDependency('pale chartreuse', 'dim magenta');
graph.addDependency('striped orange', 'dim magenta');
graph.addDependency('vibrant turquoise', 'dim magenta');
graph.addDependency('muted aqua', 'dim maroon');
graph.addDependency('dark cyan', 'dim olive');
graph.addDependency('dotted salmon', 'dim orange');
graph.addDependency('light tan', 'dim orange');
graph.addDependency('dim cyan', 'dim plum');
graph.addDependency('vibrant crimson', 'dim plum');
graph.addDependency('dim lime', 'dim purple');
graph.addDependency('dotted white', 'dim purple');
graph.addDependency('posh salmon', 'dim purple');
graph.addDependency('plaid brown', 'dim red');
graph.addDependency('muted green', 'dim salmon');
graph.addDependency('muted tan', 'dim salmon');
graph.addDependency('pale bronze', 'dim salmon');
graph.addDependency('dark fuchsia', 'dim silver');
graph.addDependency('dotted tan', 'dim silver');
graph.addDependency('dull olive', 'dim silver');
graph.addDependency('muted lavender', 'dim silver');
graph.addDependency('clear teal', 'dim tan');
graph.addDependency('drab teal', 'dim tan');
graph.addDependency('posh lime', 'dim tan');
graph.addDependency('drab blue', 'dim teal');
graph.addDependency('pale white', 'dim tomato');
graph.addDependency('bright yellow', 'dim turquoise');
graph.addDependency('striped lavender', 'dim turquoise');
graph.addDependency('posh teal', 'dim violet');
graph.addDependency('bright beige', 'dim white');
graph.addDependency('muted purple', 'dim yellow');
graph.addDependency('striped black', 'dim yellow');
graph.addDependency('wavy coral', 'dim yellow');
graph.addDependency('muted red', 'dotted aqua');
graph.addDependency('clear maroon', 'dotted beige');
graph.addDependency('dim tomato', 'dotted beige');
graph.addDependency('pale maroon', 'dotted beige');
graph.addDependency('vibrant turquoise', 'dotted beige');
graph.addDependency('dull gray', 'dotted black');
graph.addDependency('muted gray', 'dotted black');
graph.addDependency('pale maroon', 'dotted black');
graph.addDependency('vibrant green', 'dotted black');
graph.addDependency('dim green', 'dotted blue');
graph.addDependency('drab red', 'dotted blue');
graph.addDependency('posh gold', 'dotted blue');
graph.addDependency('clear indigo', 'dotted bronze');
graph.addDependency('dim beige', 'dotted brown');
graph.addDependency('light purple', 'dotted brown');
graph.addDependency('pale white', 'dotted brown');
graph.addDependency('clear aqua', 'dotted chartreuse');
graph.addDependency('plaid coral', 'dotted chartreuse');
graph.addDependency('dull teal', 'dotted coral');
graph.addDependency('dotted teal', 'dotted crimson');
graph.addDependency('posh black', 'dotted crimson');
graph.addDependency('shiny silver', 'dotted crimson');
graph.addDependency('vibrant salmon', 'dotted crimson');
graph.addDependency('faded tan', 'dotted cyan');
graph.addDependency('shiny brown', 'dotted cyan');
graph.addDependency('wavy aqua', 'dotted cyan');
graph.addDependency('mirrored tan', 'dotted fuchsia');
graph.addDependency('vibrant silver', 'dotted fuchsia');
graph.addDependency('clear teal', 'dotted gold');
graph.addDependency('muted tomato', 'dotted gold');
graph.addDependency('plaid green', 'dotted gold');
graph.addDependency('posh salmon', 'dotted gold');
graph.addDependency('dotted indigo', 'dotted gray');
graph.addDependency('posh crimson', 'dotted gray');
graph.addDependency('clear white', 'dotted green');
graph.addDependency('dull plum', 'dotted green');
graph.addDependency('faded magenta', 'dotted green');
graph.addDependency('muted lavender', 'dotted green');
graph.addDependency('muted red', 'dotted indigo');
graph.addDependency('light olive', 'dotted lavender');
graph.addDependency('muted tomato', 'dotted lavender');
graph.addDependency('bright purple', 'dotted lime');
graph.addDependency('dotted chartreuse', 'dotted lime');
graph.addDependency('mirrored green', 'dotted lime');
graph.addDependency('shiny cyan', 'dotted lime');
graph.addDependency('clear maroon', 'dotted magenta');
graph.addDependency('drab tomato', 'dotted magenta');
graph.addDependency('drab yellow', 'dotted magenta');
graph.addDependency('dim green', 'dotted maroon');
graph.addDependency('faded silver', 'dotted maroon');
graph.addDependency('dotted red', 'dotted olive');
graph.addDependency('drab lime', 'dotted olive');
graph.addDependency('mirrored maroon', 'dotted olive');
graph.addDependency('drab cyan', 'dotted orange');
graph.addDependency('light gold', 'dotted orange');
graph.addDependency('light silver', 'dotted orange');
graph.addDependency('vibrant tomato', 'dotted orange');
graph.addDependency('muted lavender', 'dotted plum');
graph.addDependency('vibrant purple', 'dotted plum');
graph.addDependency('wavy coral', 'dotted plum');
graph.addDependency('vibrant white', 'dotted purple');
graph.addDependency('wavy black', 'dotted purple');
graph.addDependency('dark teal', 'dotted red');
graph.addDependency('pale olive', 'dotted red');
graph.addDependency('posh fuchsia', 'dotted red');
graph.addDependency('posh teal', 'dotted salmon');
graph.addDependency('dark cyan', 'dotted silver');
graph.addDependency('dotted turquoise', 'dotted silver');
graph.addDependency('plaid red', 'dotted silver');
graph.addDependency('mirrored gray', 'dotted tan');
graph.addDependency('dotted gray', 'dotted teal');
graph.addDependency('muted brown', 'dotted teal');
graph.addDependency('dim green', 'dotted tomato');
graph.addDependency('posh tomato', 'dotted tomato');
graph.addDependency('dim violet', 'dotted turquoise');
graph.addDependency('bright olive', 'dotted white');
graph.addDependency('dim fuchsia', 'dotted white');
graph.addDependency('muted purple', 'dotted white');
graph.addDependency('shiny gold', 'dotted white');
graph.addDependency('dim aqua', 'dotted yellow');
graph.addDependency('dim salmon', 'dotted yellow');
graph.addDependency('dotted blue', 'dotted yellow');
graph.addDependency('plaid teal', 'dotted yellow');
graph.addDependency('dim gray', 'drab aqua');
graph.addDependency('drab olive', 'drab aqua');
graph.addDependency('shiny white', 'drab aqua');
graph.addDependency('bright teal', 'drab beige');
graph.addDependency('dim lime', 'drab beige');
graph.addDependency('faded cyan', 'drab beige');
graph.addDependency('muted yellow', 'drab beige');
graph.addDependency('dotted white', 'drab black');
graph.addDependency('muted purple', 'drab black');
graph.addDependency('posh gold', 'drab black');
graph.addDependency('bright purple', 'drab blue');
graph.addDependency('drab olive', 'drab blue');
graph.addDependency('muted red', 'drab blue');
graph.addDependency('clear plum', 'drab bronze');
graph.addDependency('dark cyan', 'drab bronze');
graph.addDependency('faded plum', 'drab bronze');
graph.addDependency('posh cyan', 'drab bronze');
graph.addDependency('clear silver', 'drab brown');
graph.addDependency('striped magenta', 'drab brown');
graph.addDependency('bright purple', 'drab chartreuse');
graph.addDependency('dull purple', 'drab chartreuse');
graph.addDependency('faded silver', 'drab chartreuse');
graph.addDependency('muted lavender', 'drab chartreuse');
graph.addDependency('muted indigo', 'drab crimson');
graph.addDependency('vibrant crimson', 'drab crimson');
graph.addDependency('bright purple', 'drab cyan');
graph.addDependency('drab red', 'drab cyan');
graph.addDependency('posh crimson', 'drab cyan');
graph.addDependency('dull brown', 'drab fuchsia');
graph.addDependency('muted bronze', 'drab fuchsia');
graph.addDependency('clear yellow', 'drab gold');
graph.addDependency('dark cyan', 'drab gold');
graph.addDependency('bright purple', 'drab gray');
graph.addDependency('dim green', 'drab gray');
graph.addDependency('faded gold', 'drab gray');
graph.addDependency('plaid white', 'drab green');
graph.addDependency('dim fuchsia', 'drab indigo');
graph.addDependency('dotted violet', 'drab indigo');
graph.addDependency('muted red', 'drab indigo');
graph.addDependency('striped maroon', 'drab indigo');
graph.addDependency('dotted maroon', 'drab lavender');
graph.addDependency('light olive', 'drab lavender');
graph.addDependency('pale aqua', 'drab lavender');
graph.addDependency('clear silver', 'drab lime');
graph.addDependency('drab aqua', 'drab lime');
graph.addDependency('drab chartreuse', 'drab lime');
graph.addDependency('bright crimson', 'drab magenta');
graph.addDependency('plaid yellow', 'drab magenta');
graph.addDependency('shiny salmon', 'drab magenta');
graph.addDependency('dull crimson', 'drab maroon');
graph.addDependency('light purple', 'drab maroon');
graph.addDependency('shiny white', 'drab maroon');
graph.addDependency('faded silver', 'drab olive');
graph.addDependency('dim gray', 'drab orange');
graph.addDependency('dull beige', 'drab orange');
graph.addDependency('shiny magenta', 'drab plum');
graph.addDependency('bright lavender', 'drab purple');
graph.addDependency('dark aqua', 'drab purple');
graph.addDependency('drab orange', 'drab purple');
graph.addDependency('dull tomato', 'drab salmon');
graph.addDependency('pale tan', 'drab silver');
graph.addDependency('dark indigo', 'drab tan');
graph.addDependency('striped black', 'drab tan');
graph.addDependency('pale cyan', 'drab teal');
graph.addDependency('shiny turquoise', 'drab teal');
graph.addDependency('drab cyan', 'drab tomato');
graph.addDependency('dull brown', 'drab tomato');
graph.addDependency('posh black', 'drab tomato');
graph.addDependency('light green', 'drab turquoise');
graph.addDependency('pale chartreuse', 'drab turquoise');
graph.addDependency('shiny purple', 'drab turquoise');
graph.addDependency('vibrant tomato', 'drab violet');
graph.addDependency('light silver', 'drab white');
graph.addDependency('dotted orange', 'drab yellow');
graph.addDependency('dotted tomato', 'drab yellow');
graph.addDependency('light salmon', 'drab yellow');
graph.addDependency('light turquoise', 'drab yellow');
graph.addDependency('dull plum', 'dull aqua');
graph.addDependency('light indigo', 'dull aqua');
graph.addDependency('dim fuchsia', 'dull beige');
graph.addDependency('drab cyan', 'dull beige');
graph.addDependency('mirrored indigo', 'dull beige');
graph.addDependency('bright lime', 'dull black');
graph.addDependency('dark green', 'dull black');
graph.addDependency('mirrored gray', 'dull black');
graph.addDependency('pale gold', 'dull blue');
graph.addDependency('posh crimson', 'dull blue');
graph.addDependency('vibrant chartreuse', 'dull bronze');
graph.addDependency('bright olive', 'dull brown');
graph.addDependency('drab lavender', 'dull chartreuse');
graph.addDependency('pale gold', 'dull chartreuse');
graph.addDependency('shiny cyan', 'dull chartreuse');
graph.addDependency('clear gold', 'dull coral');
graph.addDependency('clear olive', 'dull coral');
graph.addDependency('mirrored gold', 'dull coral');
graph.addDependency('posh tomato', 'dull coral');
graph.addDependency('pale maroon', 'dull crimson');
graph.addDependency('vibrant bronze', 'dull crimson');
graph.addDependency('faded green', 'dull cyan');
graph.addDependency('dotted indigo', 'dull fuchsia');
graph.addDependency('pale magenta', 'dull fuchsia');
graph.addDependency('drab teal', 'dull gold');
graph.addDependency('drab indigo', 'dull gray');
graph.addDependency('light salmon', 'dull gray');
graph.addDependency('plaid coral', 'dull gray');
graph.addDependency('striped magenta', 'dull gray');
graph.addDependency('dark tan', 'dull green');
graph.addDependency('faded gray', 'dull green');
graph.addDependency('muted tan', 'dull green');
graph.addDependency('dotted beige', 'dull indigo');
graph.addDependency('posh fuchsia', 'dull indigo');
graph.addDependency('pale green', 'dull lavender');
graph.addDependency('bright purple', 'dull lime');
graph.addDependency('drab cyan', 'dull lime');
graph.addDependency('posh gold', 'dull lime');
graph.addDependency('posh tan', 'dull lime');
graph.addDependency('dull tomato', 'dull magenta');
graph.addDependency('pale cyan', 'dull magenta');
graph.addDependency('posh gray', 'dull magenta');
graph.addDependency('wavy white', 'dull magenta');
graph.addDependency('clear cyan', 'dull maroon');
graph.addDependency('dim lavender', 'dull olive');
graph.addDependency('clear tan', 'dull orange');
graph.addDependency('pale chartreuse', 'dull orange');
graph.addDependency('plaid crimson', 'dull orange');
graph.addDependency('clear cyan', 'dull plum');
graph.addDependency('dotted maroon', 'dull plum');
graph.addDependency('posh crimson', 'dull plum');
graph.addDependency('shiny white', 'dull plum');
graph.addDependency('posh gold', 'dull purple');
graph.addDependency('dim tomato', 'dull red');
graph.addDependency('mirrored tan', 'dull red');
graph.addDependency('striped crimson', 'dull red');
graph.addDependency('dark brown', 'dull salmon');
graph.addDependency('shiny aqua', 'dull salmon');
graph.addDependency('striped bronze', 'dull salmon');
graph.addDependency('clear cyan', 'dull silver');
graph.addDependency('dim black', 'dull silver');
graph.addDependency('dim tan', 'dull silver');
graph.addDependency('dotted red', 'dull tan');
graph.addDependency('drab blue', 'dull tan');
graph.addDependency('pale green', 'dull tan');
graph.addDependency('striped maroon', 'dull tan');
graph.addDependency('faded red', 'dull teal');
graph.addDependency('light turquoise', 'dull teal');
graph.addDependency('wavy gold', 'dull teal');
graph.addDependency('dotted tomato', 'dull tomato');
graph.addDependency('dotted orange', 'dull turquoise');
graph.addDependency('mirrored green', 'dull turquoise');
graph.addDependency('posh blue', 'dull turquoise');
graph.addDependency('wavy fuchsia', 'dull turquoise');
graph.addDependency('dim coral', 'dull violet');
graph.addDependency('wavy lavender', 'dull violet');
graph.addDependency('dark lavender', 'dull white');
graph.addDependency('light maroon', 'dull white');
graph.addDependency('posh red', 'dull white');
graph.addDependency('muted aqua', 'dull yellow');
graph.addDependency('dotted indigo', 'faded aqua');
graph.addDependency('faded fuchsia', 'faded aqua');
graph.addDependency('shiny cyan', 'faded aqua');
graph.addDependency('light brown', 'faded beige');
graph.addDependency('light salmon', 'faded beige');
graph.addDependency('plaid bronze', 'faded beige');
graph.addDependency('dark turquoise', 'faded black');
graph.addDependency('dotted violet', 'faded blue');
graph.addDependency('posh gold', 'faded blue');
graph.addDependency('posh tan', 'faded blue');
graph.addDependency('clear teal', 'faded bronze');
graph.addDependency('light yellow', 'faded bronze');
graph.addDependency('pale green', 'faded bronze');
graph.addDependency('dim tan', 'faded brown');
graph.addDependency('light cyan', 'faded chartreuse');
graph.addDependency('pale tomato', 'faded chartreuse');
graph.addDependency('light purple', 'faded coral');
graph.addDependency('mirrored salmon', 'faded coral');
graph.addDependency('pale maroon', 'faded coral');
graph.addDependency('clear lavender', 'faded crimson');
graph.addDependency('dim cyan', 'faded crimson');
graph.addDependency('dim lavender', 'faded crimson');
graph.addDependency('wavy tan', 'faded crimson');
graph.addDependency('pale plum', 'faded cyan');
graph.addDependency('posh gold', 'faded cyan');
graph.addDependency('posh yellow', 'faded cyan');
graph.addDependency('muted tomato', 'faded fuchsia');
graph.addDependency('shiny blue', 'faded fuchsia');
graph.addDependency('wavy lavender', 'faded fuchsia');
graph.addDependency('dotted aqua', 'faded gold');
graph.addDependency('light turquoise', 'faded gold');
graph.addDependency('wavy violet', 'faded gold');
graph.addDependency('dim green', 'faded gray');
graph.addDependency('dotted indigo', 'faded gray');
graph.addDependency('pale teal', 'faded gray');
graph.addDependency('posh crimson', 'faded gray');
graph.addDependency('dim olive', 'faded green');
graph.addDependency('vibrant fuchsia', 'faded green');
graph.addDependency('faded lime', 'faded indigo');
graph.addDependency('mirrored red', 'faded indigo');
graph.addDependency('bright indigo', 'faded lavender');
graph.addDependency('clear cyan', 'faded lavender');
graph.addDependency('dim purple', 'faded lavender');
graph.addDependency('mirrored gray', 'faded lavender');
graph.addDependency('dotted lavender', 'faded lime');
graph.addDependency('posh tan', 'faded lime');
graph.addDependency('striped magenta', 'faded lime');
graph.addDependency('dull beige', 'faded magenta');
graph.addDependency('light bronze', 'faded maroon');
graph.addDependency('light lime', 'faded maroon');
graph.addDependency('mirrored green', 'faded maroon');
graph.addDependency('bright yellow', 'faded olive');
graph.addDependency('dull lavender', 'faded olive');
graph.addDependency('striped salmon', 'faded olive');
graph.addDependency('light teal', 'faded orange');
graph.addDependency('dotted maroon', 'faded plum');
graph.addDependency('vibrant bronze', 'faded plum');
graph.addDependency('vibrant indigo', 'faded plum');
graph.addDependency('dotted white', 'faded purple');
graph.addDependency('muted gray', 'faded red');
graph.addDependency('muted tomato', 'faded salmon');
graph.addDependency('pale green', 'faded salmon');
graph.addDependency('plaid coral', 'faded salmon');
graph.addDependency('shiny lavender', 'faded salmon');
graph.addDependency('bright purple', 'faded silver');
graph.addDependency('dim fuchsia', 'faded silver');
graph.addDependency('dim orange', 'faded tan');
graph.addDependency('dull purple', 'faded tan');
graph.addDependency('bright purple', 'faded teal');
graph.addDependency('dotted magenta', 'faded teal');
graph.addDependency('plaid olive', 'faded teal');
graph.addDependency('shiny magenta', 'faded tomato');
graph.addDependency('drab plum', 'faded turquoise');
graph.addDependency('dull gray', 'faded turquoise');
graph.addDependency('plaid black', 'faded turquoise');
graph.addDependency('wavy crimson', 'faded turquoise');
graph.addDependency('drab red', 'faded violet');
graph.addDependency('muted purple', 'faded white');
graph.addDependency('vibrant purple', 'faded white');
graph.addDependency('mirrored maroon', 'faded yellow');
graph.addDependency('plaid orange', 'faded yellow');
graph.addDependency('dim olive', 'light aqua');
graph.addDependency('mirrored teal', 'light aqua');
graph.addDependency('vibrant lime', 'light aqua');
graph.addDependency('light bronze', 'light beige');
graph.addDependency('pale turquoise', 'light beige');
graph.addDependency('pale yellow', 'light beige');
graph.addDependency('wavy coral', 'light black');
graph.addDependency('drab white', 'light blue');
graph.addDependency('pale olive', 'light blue');
graph.addDependency('light purple', 'light bronze');
graph.addDependency('clear gold', 'light brown');
graph.addDependency('posh red', 'light brown');
graph.addDependency('posh brown', 'light chartreuse');
graph.addDependency('bright gray', 'light coral');
graph.addDependency('dark coral', 'light coral');
graph.addDependency('drab coral', 'light coral');
graph.addDependency('wavy orange', 'light coral');
graph.addDependency('dark crimson', 'light crimson');
graph.addDependency('pale tomato', 'light crimson');
graph.addDependency('striped coral', 'light crimson');
graph.addDependency('striped teal', 'light crimson');
graph.addDependency('mirrored gold', 'light cyan');
graph.addDependency('vibrant bronze', 'light cyan');
graph.addDependency('clear tan', 'light fuchsia');
graph.addDependency('posh tan', 'light fuchsia');
graph.addDependency('bright purple', 'light gold');
graph.addDependency('dotted violet', 'light gold');
graph.addDependency('posh red', 'light gold');
graph.addDependency('striped maroon', 'light gold');
graph.addDependency('drab violet', 'light gray');
graph.addDependency('dim chartreuse', 'light green');
graph.addDependency('dotted orange', 'light green');
graph.addDependency('dotted red', 'light green');
graph.addDependency('muted gray', 'light green');
graph.addDependency('light olive', 'light indigo');
graph.addDependency('dim lavender', 'light lavender');
graph.addDependency('posh lavender', 'light lavender');
graph.addDependency('drab chartreuse', 'light lime');
graph.addDependency('dim olive', 'light magenta');
graph.addDependency('muted lavender', 'light magenta');
graph.addDependency('vibrant bronze', 'light olive');
graph.addDependency('dark black', 'light orange');
graph.addDependency('drab orange', 'light plum');
graph.addDependency('faded coral', 'light plum');
graph.addDependency('light maroon', 'light purple');
graph.addDependency('dark magenta', 'light red');
graph.addDependency('striped purple', 'light red');
graph.addDependency('muted purple', 'light salmon');
graph.addDependency('muted red', 'light salmon');
graph.addDependency('posh red', 'light salmon');
graph.addDependency('shiny turquoise', 'light salmon');
graph.addDependency('clear olive', 'light silver');
graph.addDependency('mirrored green', 'light silver');
graph.addDependency('muted red', 'light silver');
graph.addDependency('muted tomato', 'light silver');
graph.addDependency('posh tomato', 'light tan');
graph.addDependency('clear turquoise', 'light teal');
graph.addDependency('faded cyan', 'light teal');
graph.addDependency('dotted chartreuse', 'light tomato');
graph.addDependency('dark cyan', 'light turquoise');
graph.addDependency('clear plum', 'light violet');
graph.addDependency('dark teal', 'light violet');
graph.addDependency('faded gold', 'light violet');
graph.addDependency('dark teal', 'light white');
graph.addDependency('faded blue', 'light white');
graph.addDependency('wavy black', 'light white');
graph.addDependency('bright red', 'light yellow');
graph.addDependency('shiny violet', 'light yellow');
graph.addDependency('wavy gray', 'light yellow');
graph.addDependency('wavy olive', 'light yellow');
graph.addDependency('bright lavender', 'mirrored aqua');
graph.addDependency('posh fuchsia', 'mirrored aqua');
graph.addDependency('striped lavender', 'mirrored aqua');
graph.addDependency('dim bronze', 'mirrored beige');
graph.addDependency('dim maroon', 'mirrored beige');
graph.addDependency('vibrant salmon', 'mirrored beige');
graph.addDependency('bright purple', 'mirrored black');
graph.addDependency('muted silver', 'mirrored black');
graph.addDependency('plaid gray', 'mirrored black');
graph.addDependency('drab gray', 'mirrored blue');
graph.addDependency('vibrant green', 'mirrored blue');
graph.addDependency('bright olive', 'mirrored bronze');
graph.addDependency('drab cyan', 'mirrored bronze');
graph.addDependency('vibrant cyan', 'mirrored bronze');
graph.addDependency('drab bronze', 'mirrored brown');
graph.addDependency('posh fuchsia', 'mirrored brown');
graph.addDependency('wavy coral', 'mirrored brown');
graph.addDependency('dark coral', 'mirrored chartreuse');
graph.addDependency('dark orange', 'mirrored chartreuse');
graph.addDependency('faded aqua', 'mirrored chartreuse');
graph.addDependency('wavy beige', 'mirrored chartreuse');
graph.addDependency('faded gray', 'mirrored coral');
graph.addDependency('muted bronze', 'mirrored coral');
graph.addDependency('pale aqua', 'mirrored coral');
graph.addDependency('pale green', 'mirrored coral');
graph.addDependency('vibrant crimson', 'mirrored crimson');
graph.addDependency('bright aqua', 'mirrored cyan');
graph.addDependency('bright olive', 'mirrored cyan');
graph.addDependency('shiny turquoise', 'mirrored cyan');
graph.addDependency('bright yellow', 'mirrored fuchsia');
graph.addDependency('dotted chartreuse', 'mirrored fuchsia');
graph.addDependency('light red', 'mirrored fuchsia');
graph.addDependency('muted tomato', 'mirrored fuchsia');
graph.addDependency('dotted indigo', 'mirrored gold');
graph.addDependency('mirrored teal', 'mirrored gold');
graph.addDependency('striped maroon', 'mirrored gold');
graph.addDependency('dim lavender', 'mirrored gray');
graph.addDependency('shiny chartreuse', 'mirrored gray');
graph.addDependency('dim lavender', 'mirrored green');
graph.addDependency('muted red', 'mirrored green');
graph.addDependency('mirrored green', 'mirrored indigo');
graph.addDependency('dotted orange', 'mirrored lavender');
graph.addDependency('posh violet', 'mirrored lavender');
graph.addDependency('dotted plum', 'mirrored lime');
graph.addDependency('light yellow', 'mirrored lime');
graph.addDependency('pale fuchsia', 'mirrored lime');
graph.addDependency('dark tan', 'mirrored magenta');
graph.addDependency('drab teal', 'mirrored magenta');
graph.addDependency('striped bronze', 'mirrored magenta');
graph.addDependency('striped magenta', 'mirrored magenta');
graph.addDependency('clear bronze', 'mirrored maroon');
graph.addDependency('pale cyan', 'mirrored maroon');
graph.addDependency('dark teal', 'mirrored olive');
graph.addDependency('light violet', 'mirrored olive');
graph.addDependency('pale brown', 'mirrored olive');
graph.addDependency('shiny yellow', 'mirrored olive');
graph.addDependency('dull olive', 'mirrored orange');
graph.addDependency('shiny aqua', 'mirrored orange');
graph.addDependency('striped beige', 'mirrored orange');
graph.addDependency('striped salmon', 'mirrored orange');
graph.addDependency('dotted white', 'mirrored plum');
graph.addDependency('plaid indigo', 'mirrored plum');
graph.addDependency('drab red', 'mirrored purple');
graph.addDependency('plaid teal', 'mirrored purple');
graph.addDependency('plaid turquoise', 'mirrored purple');
graph.addDependency('vibrant brown', 'mirrored purple');
graph.addDependency('dark brown', 'mirrored red');
graph.addDependency('mirrored green', 'mirrored red');
graph.addDependency('shiny white', 'mirrored red');
graph.addDependency('wavy black', 'mirrored red');
graph.addDependency('plaid green', 'mirrored salmon');
graph.addDependency('bright plum', 'mirrored silver');
graph.addDependency('dark chartreuse', 'mirrored silver');
graph.addDependency('pale cyan', 'mirrored silver');
graph.addDependency('pale maroon', 'mirrored silver');
graph.addDependency('clear aqua', 'mirrored tan');
graph.addDependency('dim violet', 'mirrored tan');
graph.addDependency('wavy gray', 'mirrored tan');
graph.addDependency('light gold', 'mirrored teal');
graph.addDependency('pale maroon', 'mirrored teal');
graph.addDependency('striped maroon', 'mirrored teal');
graph.addDependency('clear crimson', 'mirrored tomato');
graph.addDependency('dark gray', 'mirrored tomato');
graph.addDependency('mirrored indigo', 'mirrored tomato');
graph.addDependency('muted black', 'mirrored tomato');
graph.addDependency('dim olive', 'mirrored turquoise');
graph.addDependency('plaid tomato', 'mirrored turquoise');
graph.addDependency('dark fuchsia', 'mirrored violet');
graph.addDependency('dim tan', 'mirrored violet');
graph.addDependency('pale turquoise', 'mirrored violet');
graph.addDependency('mirrored teal', 'mirrored white');
graph.addDependency('muted silver', 'mirrored white');
graph.addDependency('mirrored tan', 'mirrored yellow');
graph.addDependency('muted cyan', 'mirrored yellow');
graph.addDependency('clear white', 'muted aqua');
graph.addDependency('clear orange', 'muted beige');
graph.addDependency('clear white', 'muted beige');
graph.addDependency('light maroon', 'muted beige');
graph.addDependency('clear tomato', 'muted black');
graph.addDependency('muted magenta', 'muted black');
graph.addDependency('pale red', 'muted black');
graph.addDependency('pale brown', 'muted blue');
graph.addDependency('posh yellow', 'muted bronze');
graph.addDependency('shiny turquoise', 'muted bronze');
graph.addDependency('vibrant bronze', 'muted bronze');
graph.addDependency('dotted blue', 'muted brown');
graph.addDependency('light indigo', 'muted brown');
graph.addDependency('muted brown', 'muted chartreuse');
graph.addDependency('muted white', 'muted chartreuse');
graph.addDependency('posh lime', 'muted chartreuse');
graph.addDependency('striped tan', 'muted chartreuse');
graph.addDependency('clear blue', 'muted coral');
graph.addDependency('clear plum', 'muted coral');
graph.addDependency('vibrant olive', 'muted coral');
graph.addDependency('plaid olive', 'muted crimson');
graph.addDependency('dull coral', 'muted cyan');
graph.addDependency('faded plum', 'muted cyan');
graph.addDependency('light tomato', 'muted cyan');
graph.addDependency('wavy black', 'muted cyan');
graph.addDependency('light olive', 'muted fuchsia');
graph.addDependency('clear olive', 'muted gold');
graph.addDependency('muted red', 'muted gold');
graph.addDependency('dull olive', 'muted gray');
graph.addDependency('striped aqua', 'muted green');
graph.addDependency('wavy lavender', 'muted green');
graph.addDependency('shiny red', 'muted indigo');
graph.addDependency('clear bronze', 'muted lavender');
graph.addDependency('light brown', 'muted lime');
graph.addDependency('plaid aqua', 'muted lime');
graph.addDependency('plaid tomato', 'muted lime');
graph.addDependency('muted red', 'muted magenta');
graph.addDependency('pale crimson', 'muted maroon');
graph.addDependency('dotted chartreuse', 'muted olive');
graph.addDependency('pale beige', 'muted olive');
graph.addDependency('shiny crimson', 'muted olive');
graph.addDependency('vibrant blue', 'muted olive');
graph.addDependency('faded tan', 'muted orange');
graph.addDependency('vibrant salmon', 'muted orange');
graph.addDependency('mirrored cyan', 'muted plum');
graph.addDependency('dotted aqua', 'muted purple');
graph.addDependency('muted tomato', 'muted purple');
graph.addDependency('shiny chartreuse', 'muted purple');
graph.addDependency('shiny turquoise', 'muted purple');
graph.addDependency('dim fuchsia', 'muted red');
graph.addDependency('light maroon', 'muted red');
graph.addDependency('pale teal', 'muted red');
graph.addDependency('faded magenta', 'muted salmon');
graph.addDependency('plaid blue', 'muted salmon');
graph.addDependency('dotted black', 'muted silver');
graph.addDependency('muted cyan', 'muted silver');
graph.addDependency('vibrant salmon', 'muted silver');
graph.addDependency('bright lavender', 'muted tan');
graph.addDependency('drab cyan', 'muted tan');
graph.addDependency('pale silver', 'muted tan');
graph.addDependency('bright salmon', 'muted teal');
graph.addDependency('dotted gray', 'muted teal');
graph.addDependency('striped aqua', 'muted teal');
graph.addDependency('dim lavender', 'muted tomato');
graph.addDependency('posh gold', 'muted turquoise');
graph.addDependency('posh magenta', 'muted turquoise');
graph.addDependency('wavy beige', 'muted turquoise');
graph.addDependency('dotted magenta', 'muted violet');
graph.addDependency('posh chartreuse', 'muted violet');
graph.addDependency('dark cyan', 'muted white');
graph.addDependency('dotted indigo', 'muted white');
graph.addDependency('mirrored gray', 'muted white');
graph.addDependency('bright violet', 'muted yellow');
graph.addDependency('muted brown', 'muted yellow');
graph.addDependency('striped lavender', 'muted yellow');
graph.addDependency('faded plum', 'pale aqua');
graph.addDependency('vibrant plum', 'pale aqua');
graph.addDependency('dark indigo', 'pale beige');
graph.addDependency('dim beige', 'pale beige');
graph.addDependency('mirrored teal', 'pale black');
graph.addDependency('muted silver', 'pale black');
graph.addDependency('shiny blue', 'pale black');
graph.addDependency('dotted blue', 'pale blue');
graph.addDependency('faded red', 'pale blue');
graph.addDependency('muted beige', 'pale blue');
graph.addDependency('clear tan', 'pale bronze');
graph.addDependency('dotted salmon', 'pale bronze');
graph.addDependency('striped blue', 'pale bronze');
graph.addDependency('bright silver', 'pale brown');
graph.addDependency('striped teal', 'pale chartreuse');
graph.addDependency('clear aqua', 'pale coral');
graph.addDependency('dim blue', 'pale coral');
graph.addDependency('mirrored white', 'pale coral');
graph.addDependency('bright white', 'pale crimson');
graph.addDependency('shiny turquoise', 'pale crimson');
graph.addDependency('dull lime', 'pale cyan');
graph.addDependency('faded black', 'pale cyan');
graph.addDependency('light olive', 'pale cyan');
graph.addDependency('plaid red', 'pale cyan');
graph.addDependency('light brown', 'pale fuchsia');
graph.addDependency('vibrant lime', 'pale fuchsia');
graph.addDependency('drab olive', 'pale gold');
graph.addDependency('faded gray', 'pale gold');
graph.addDependency('mirrored green', 'pale gold');
graph.addDependency('shiny white', 'pale gray');
graph.addDependency('muted gold', 'pale green');
graph.addDependency('shiny turquoise', 'pale green');
graph.addDependency('light green', 'pale indigo');
graph.addDependency('plaid bronze', 'pale indigo');
graph.addDependency('dark teal', 'pale lavender');
graph.addDependency('dim fuchsia', 'pale lavender');
graph.addDependency('faded black', 'pale lavender');
graph.addDependency('muted red', 'pale lavender');
graph.addDependency('dotted tan', 'pale lime');
graph.addDependency('pale olive', 'pale lime');
graph.addDependency('striped cyan', 'pale lime');
graph.addDependency('vibrant chartreuse', 'pale lime');
graph.addDependency('pale gray', 'pale magenta');
graph.addDependency('dim violet', 'pale maroon');
graph.addDependency('pale teal', 'pale maroon');
graph.addDependency('posh teal', 'pale maroon');
graph.addDependency('dark purple', 'pale olive');
graph.addDependency('drab yellow', 'pale olive');
graph.addDependency('vibrant coral', 'pale olive');
graph.addDependency('mirrored indigo', 'pale orange');
graph.addDependency('muted purple', 'pale orange');
graph.addDependency('plaid orange', 'pale orange');
graph.addDependency('dark salmon', 'pale plum');
graph.addDependency('dotted violet', 'pale plum');
graph.addDependency('light bronze', 'pale plum');
graph.addDependency('bright crimson', 'pale purple');
graph.addDependency('drab gray', 'pale red');
graph.addDependency('dull coral', 'pale red');
graph.addDependency('striped purple', 'pale red');
graph.addDependency('dark olive', 'pale salmon');
graph.addDependency('drab purple', 'pale salmon');
graph.addDependency('mirrored silver', 'pale salmon');
graph.addDependency('bright yellow', 'pale silver');
graph.addDependency('clear plum', 'pale silver');
graph.addDependency('light purple', 'pale silver');
graph.addDependency('pale teal', 'pale silver');
graph.addDependency('wavy white', 'pale tan');
graph.addDependency('dotted blue', 'pale tomato');
graph.addDependency('drab coral', 'pale tomato');
graph.addDependency('posh teal', 'pale tomato');
graph.addDependency('muted cyan', 'pale turquoise');
graph.addDependency('striped teal', 'pale turquoise');
graph.addDependency('light brown', 'pale violet');
graph.addDependency('pale lavender', 'pale violet');
graph.addDependency('vibrant tomato', 'pale violet');
graph.addDependency('dark turquoise', 'pale white');
graph.addDependency('drab indigo', 'pale white');
graph.addDependency('dull olive', 'pale white');
graph.addDependency('mirrored green', 'pale white');
graph.addDependency('dull salmon', 'pale yellow');
graph.addDependency('light turquoise', 'pale yellow');
graph.addDependency('plaid maroon', 'pale yellow');
graph.addDependency('plaid tomato', 'plaid aqua');
graph.addDependency('dim brown', 'plaid beige');
graph.addDependency('dull yellow', 'plaid beige');
graph.addDependency('vibrant lavender', 'plaid beige');
graph.addDependency('clear aqua', 'plaid black');
graph.addDependency('dim violet', 'plaid black');
graph.addDependency('plaid red', 'plaid black');
graph.addDependency('wavy silver', 'plaid black');
graph.addDependency('clear orange', 'plaid blue');
graph.addDependency('light silver', 'plaid blue');
graph.addDependency('shiny red', 'plaid blue');
graph.addDependency('dark tan', 'plaid bronze');
graph.addDependency('drab plum', 'plaid bronze');
graph.addDependency('plaid white', 'plaid bronze');
graph.addDependency('posh violet', 'plaid bronze');
graph.addDependency('clear cyan', 'plaid brown');
graph.addDependency('light salmon', 'plaid brown');
graph.addDependency('pale maroon', 'plaid brown');
graph.addDependency('vibrant indigo', 'plaid brown');
graph.addDependency('posh teal', 'plaid chartreuse');
graph.addDependency('shiny silver', 'plaid chartreuse');
graph.addDependency('bright olive', 'plaid coral');
graph.addDependency('dim aqua', 'plaid crimson');
graph.addDependency('plaid tan', 'plaid crimson');
graph.addDependency('dark black', 'plaid cyan');
graph.addDependency('dim purple', 'plaid fuchsia');
graph.addDependency('faded indigo', 'plaid fuchsia');
graph.addDependency('vibrant lime', 'plaid fuchsia');
graph.addDependency('wavy fuchsia', 'plaid fuchsia');
graph.addDependency('bright yellow', 'plaid gold');
graph.addDependency('dark maroon', 'plaid gold');
graph.addDependency('plaid tomato', 'plaid gold');
graph.addDependency('shiny lavender', 'plaid gold');
graph.addDependency('drab coral', 'plaid gray');
graph.addDependency('muted bronze', 'plaid gray');
graph.addDependency('pale tomato', 'plaid gray');
graph.addDependency('posh chartreuse', 'plaid gray');
graph.addDependency('clear turquoise', 'plaid green');
graph.addDependency('faded black', 'plaid green');
graph.addDependency('plaid red', 'plaid green');
graph.addDependency('clear coral', 'plaid indigo');
graph.addDependency('dull purple', 'plaid indigo');
graph.addDependency('faded gold', 'plaid indigo');
graph.addDependency('pale brown', 'plaid indigo');
graph.addDependency('posh brown', 'plaid lavender');
graph.addDependency('shiny brown', 'plaid lavender');
graph.addDependency('striped tan', 'plaid lavender');
graph.addDependency('dull blue', 'plaid lime');
graph.addDependency('drab aqua', 'plaid magenta');
graph.addDependency('faded black', 'plaid magenta');
graph.addDependency('vibrant green', 'plaid magenta');
graph.addDependency('light gold', 'plaid maroon');
graph.addDependency('faded gray', 'plaid olive');
graph.addDependency('light olive', 'plaid olive');
graph.addDependency('mirrored teal', 'plaid olive');
graph.addDependency('dim violet', 'plaid orange');
graph.addDependency('light maroon', 'plaid orange');
graph.addDependency('pale teal', 'plaid orange');
graph.addDependency('vibrant bronze', 'plaid orange');
graph.addDependency('clear tan', 'plaid plum');
graph.addDependency('posh brown', 'plaid plum');
graph.addDependency('dull crimson', 'plaid purple');
graph.addDependency('muted indigo', 'plaid purple');
graph.addDependency('pale silver', 'plaid purple');
graph.addDependency('posh cyan', 'plaid purple');
graph.addDependency('pale brown', 'plaid red');
graph.addDependency('drab lime', 'plaid salmon');
graph.addDependency('light aqua', 'plaid salmon');
graph.addDependency('striped tan', 'plaid salmon');
graph.addDependency('posh salmon', 'plaid silver');
graph.addDependency('vibrant tomato', 'plaid silver');
graph.addDependency('bright violet', 'plaid tan');
graph.addDependency('dotted coral', 'plaid tan');
graph.addDependency('plaid aqua', 'plaid tan');
graph.addDependency('vibrant olive', 'plaid tan');
graph.addDependency('vibrant bronze', 'plaid teal');
graph.addDependency('dark beige', 'plaid tomato');
graph.addDependency('mirrored maroon', 'plaid turquoise');
graph.addDependency('striped brown', 'plaid turquoise');
graph.addDependency('drab chartreuse', 'plaid violet');
graph.addDependency('muted gray', 'plaid violet');
graph.addDependency('shiny tan', 'plaid violet');
graph.addDependency('dim green', 'plaid white');
graph.addDependency('dotted magenta', 'plaid yellow');
graph.addDependency('pale tomato', 'plaid yellow');
graph.addDependency('wavy violet', 'plaid yellow');
graph.addDependency('vibrant salmon', 'posh aqua');
graph.addDependency('dotted lime', 'posh beige');
graph.addDependency('vibrant turquoise', 'posh beige');
graph.addDependency('muted tomato', 'posh black');
graph.addDependency('dull beige', 'posh blue');
graph.addDependency('dull olive', 'posh blue');
graph.addDependency('light bronze', 'posh bronze');
graph.addDependency('dim violet', 'posh brown');
graph.addDependency('drab lime', 'posh brown');
graph.addDependency('mirrored fuchsia', 'posh brown');
graph.addDependency('shiny lime', 'posh brown');
graph.addDependency('dark coral', 'posh chartreuse');
graph.addDependency('dark purple', 'posh chartreuse');
graph.addDependency('faded blue', 'posh chartreuse');
graph.addDependency('light maroon', 'posh chartreuse');
graph.addDependency('dim violet', 'posh coral');
graph.addDependency('dotted teal', 'posh coral');
graph.addDependency('muted green', 'posh coral');
graph.addDependency('plaid red', 'posh coral');
graph.addDependency('dotted indigo', 'posh crimson');
graph.addDependency('muted red', 'posh crimson');
graph.addDependency('posh red', 'posh crimson');
graph.addDependency('dotted green', 'posh cyan');
graph.addDependency('plaid tomato', 'posh cyan');
graph.addDependency('striped olive', 'posh cyan');
graph.addDependency('wavy crimson', 'posh cyan');
graph.addDependency('muted lavender', 'posh fuchsia');
graph.addDependency('posh red', 'posh fuchsia');
graph.addDependency('dim violet', 'posh gold');
graph.addDependency('shiny chartreuse', 'posh gold');
graph.addDependency('drab black', 'posh gray');
graph.addDependency('bright salmon', 'posh green');
graph.addDependency('muted tan', 'posh green');
graph.addDependency('bright bronze', 'posh indigo');
graph.addDependency('light tan', 'posh lavender');
graph.addDependency('wavy coral', 'posh lavender');
graph.addDependency('plaid silver', 'posh lime');
graph.addDependency('dim cyan', 'posh magenta');
graph.addDependency('plaid orange', 'posh magenta');
graph.addDependency('striped magenta', 'posh magenta');
graph.addDependency('wavy black', 'posh magenta');
graph.addDependency('clear tan', 'posh maroon');
graph.addDependency('dim lime', 'posh maroon');
graph.addDependency('light gold', 'posh maroon');
graph.addDependency('bright bronze', 'posh olive');
graph.addDependency('clear green', 'posh olive');
graph.addDependency('light olive', 'posh olive');
graph.addDependency('dark silver', 'posh orange');
graph.addDependency('striped chartreuse', 'posh orange');
graph.addDependency('drab orange', 'posh plum');
graph.addDependency('clear aqua', 'posh purple');
graph.addDependency('dark teal', 'posh purple');
graph.addDependency('faded tan', 'posh purple');
graph.addDependency('striped lavender', 'posh purple');
graph.addDependency('dim green', 'posh red');
graph.addDependency('pale teal', 'posh red');
graph.addDependency('bright purple', 'posh salmon');
graph.addDependency('dull crimson', 'posh salmon');
graph.addDependency('mirrored green', 'posh salmon');
graph.addDependency('pale gold', 'posh salmon');
graph.addDependency('faded gray', 'posh silver');
graph.addDependency('faded magenta', 'posh silver');
graph.addDependency('muted coral', 'posh silver');
graph.addDependency('posh cyan', 'posh silver');
graph.addDependency('dotted indigo', 'posh tan');
graph.addDependency('dull purple', 'posh tan');
graph.addDependency('dim fuchsia', 'posh teal');
graph.addDependency('dim green', 'posh teal');
graph.addDependency('dotted indigo', 'posh teal');
graph.addDependency('pale teal', 'posh teal');
graph.addDependency('drab coral', 'posh tomato');
graph.addDependency('muted tomato', 'posh tomato');
graph.addDependency('pale gold', 'posh tomato');
graph.addDependency('bright crimson', 'posh turquoise');
graph.addDependency('light gold', 'posh turquoise');
graph.addDependency('posh plum', 'posh turquoise');
graph.addDependency('clear gold', 'posh violet');
graph.addDependency('dim green', 'posh violet');
graph.addDependency('posh tomato', 'posh violet');
graph.addDependency('vibrant indigo', 'posh violet');
graph.addDependency('dark coral', 'posh white');
graph.addDependency('light bronze', 'posh yellow');
graph.addDependency('light salmon', 'posh yellow');
graph.addDependency('dim lime', 'shiny aqua');
graph.addDependency('dull brown', 'shiny aqua');
graph.addDependency('light bronze', 'shiny aqua');
graph.addDependency('vibrant cyan', 'shiny aqua');
graph.addDependency('clear olive', 'shiny beige');
graph.addDependency('muted orange', 'shiny beige');
graph.addDependency('clear orange', 'shiny black');
graph.addDependency('light olive', 'shiny black');
graph.addDependency('plaid maroon', 'shiny black');
graph.addDependency('vibrant silver', 'shiny black');
graph.addDependency('dark cyan', 'shiny blue');
graph.addDependency('dim gray', 'shiny blue');
graph.addDependency('dim lime', 'shiny blue');
graph.addDependency('posh teal', 'shiny blue');
graph.addDependency('dotted gray', 'shiny bronze');
graph.addDependency('dull blue', 'shiny bronze');
graph.addDependency('dull chartreuse', 'shiny bronze');
graph.addDependency('shiny blue', 'shiny bronze');
graph.addDependency('drab salmon', 'shiny brown');
graph.addDependency('muted bronze', 'shiny coral');
graph.addDependency('dotted lime', 'shiny crimson');
graph.addDependency('dotted turquoise', 'shiny crimson');
graph.addDependency('vibrant fuchsia', 'shiny crimson');
graph.addDependency('wavy green', 'shiny crimson');
graph.addDependency('dark turquoise', 'shiny cyan');
graph.addDependency('dark salmon', 'shiny fuchsia');
graph.addDependency('dotted olive', 'shiny fuchsia');
graph.addDependency('pale white', 'shiny fuchsia');
graph.addDependency('vibrant white', 'shiny fuchsia');
graph.addDependency('drab red', 'shiny gold');
graph.addDependency('mirrored green', 'shiny gold');
graph.addDependency('muted tomato', 'shiny gold');
graph.addDependency('striped magenta', 'shiny gold');
graph.addDependency('clear bronze', 'shiny gray');
graph.addDependency('clear gold', 'shiny gray');
graph.addDependency('drab violet', 'shiny gray');
graph.addDependency('pale lavender', 'shiny gray');
graph.addDependency('dim green', 'shiny green');
graph.addDependency('pale plum', 'shiny green');
graph.addDependency('striped teal', 'shiny green');
graph.addDependency('light gray', 'shiny indigo');
graph.addDependency('striped lavender', 'shiny indigo');
graph.addDependency('bright crimson', 'shiny lavender');
graph.addDependency('pale gold', 'shiny lavender');
graph.addDependency('pale maroon', 'shiny lavender');
graph.addDependency('mirrored gray', 'shiny lime');
graph.addDependency('light purple', 'shiny magenta');
graph.addDependency('muted aqua', 'shiny maroon');
graph.addDependency('plaid gold', 'shiny maroon');
graph.addDependency('wavy white', 'shiny maroon');
graph.addDependency('dotted orange', 'shiny olive');
graph.addDependency('dark aqua', 'shiny orange');
graph.addDependency('pale gray', 'shiny plum');
graph.addDependency('vibrant aqua', 'shiny plum');
graph.addDependency('pale fuchsia', 'shiny purple');
graph.addDependency('posh beige', 'shiny purple');
graph.addDependency('shiny maroon', 'shiny purple');
graph.addDependency('wavy brown', 'shiny purple');
graph.addDependency('dark magenta', 'shiny red');
graph.addDependency('dark bronze', 'shiny salmon');
graph.addDependency('light gold', 'shiny salmon');
graph.addDependency('pale aqua', 'shiny salmon');
graph.addDependency('posh red', 'shiny salmon');
graph.addDependency('dotted orange', 'shiny silver');
graph.addDependency('light olive', 'shiny silver');
graph.addDependency('striped gold', 'shiny silver');
graph.addDependency('clear coral', 'shiny tan');
graph.addDependency('shiny red', 'shiny tan');
graph.addDependency('wavy gold', 'shiny tan');
graph.addDependency('wavy salmon', 'shiny tan');
graph.addDependency('wavy gold', 'shiny teal');
graph.addDependency('faded violet', 'shiny tomato');
graph.addDependency('drab cyan', 'shiny turquoise');
graph.addDependency('mirrored gray', 'shiny turquoise');
graph.addDependency('mirrored teal', 'shiny turquoise');
graph.addDependency('shiny gold', 'shiny turquoise');
graph.addDependency('dim coral', 'shiny violet');
graph.addDependency('dotted orange', 'shiny white');
graph.addDependency('drab coral', 'shiny white');
graph.addDependency('faded silver', 'shiny white');
graph.addDependency('drab white', 'shiny yellow');
graph.addDependency('muted aqua', 'shiny yellow');
graph.addDependency('muted purple', 'shiny yellow');
graph.addDependency('pale tomato', 'striped aqua');
graph.addDependency('posh violet', 'striped aqua');
graph.addDependency('shiny blue', 'striped aqua');
graph.addDependency('bright white', 'striped beige');
graph.addDependency('dim lavender', 'striped beige');
graph.addDependency('striped black', 'striped beige');
graph.addDependency('wavy black', 'striped beige');
graph.addDependency('bright olive', 'striped black');
graph.addDependency('dark bronze', 'striped black');
graph.addDependency('faded blue', 'striped black');
graph.addDependency('wavy coral', 'striped black');
graph.addDependency('bright violet', 'striped blue');
graph.addDependency('dotted blue', 'striped blue');
graph.addDependency('dotted gray', 'striped blue');
graph.addDependency('dotted violet', 'striped blue');
graph.addDependency('drab red', 'striped bronze');
graph.addDependency('mirrored gray', 'striped bronze');
graph.addDependency('muted lavender', 'striped brown');
graph.addDependency('bright beige', 'striped chartreuse');
graph.addDependency('muted lavender', 'striped chartreuse');
graph.addDependency('drab tan', 'striped coral');
graph.addDependency('light violet', 'striped coral');
graph.addDependency('plaid blue', 'striped coral');
graph.addDependency('shiny aqua', 'striped crimson');
graph.addDependency('faded indigo', 'striped cyan');
graph.addDependency('wavy silver', 'striped cyan');
graph.addDependency('clear aqua', 'striped fuchsia');
graph.addDependency('dark beige', 'striped fuchsia');
graph.addDependency('mirrored coral', 'striped fuchsia');
graph.addDependency('muted gray', 'striped fuchsia');
graph.addDependency('faded silver', 'striped gold');
graph.addDependency('mirrored gray', 'striped gold');
graph.addDependency('posh salmon', 'striped gold');
graph.addDependency('clear olive', 'striped gray');
graph.addDependency('muted coral', 'striped gray');
graph.addDependency('faded plum', 'striped green');
graph.addDependency('vibrant tomato', 'striped green');
graph.addDependency('dark brown', 'striped indigo');
graph.addDependency('clear turquoise', 'striped lavender');
graph.addDependency('dark brown', 'striped lavender');
graph.addDependency('plaid red', 'striped lavender');
graph.addDependency('posh teal', 'striped lime');
graph.addDependency('faded silver', 'striped magenta');
graph.addDependency('mirrored teal', 'striped magenta');
graph.addDependency('striped magenta', 'striped olive');
graph.addDependency('bright tan', 'striped orange');
graph.addDependency('mirrored lavender', 'striped orange');
graph.addDependency('pale white', 'striped orange');
graph.addDependency('bright chartreuse', 'striped plum');
graph.addDependency('dotted violet', 'striped plum');
graph.addDependency('posh maroon', 'striped plum');
graph.addDependency('dark beige', 'striped purple');
graph.addDependency('dark cyan', 'striped red');
graph.addDependency('light bronze', 'striped red');
graph.addDependency('clear brown', 'striped salmon');
graph.addDependency('dim blue', 'striped silver');
graph.addDependency('faded olive', 'striped silver');
graph.addDependency('striped aqua', 'striped silver');
graph.addDependency('striped purple', 'striped silver');
graph.addDependency('clear blue', 'striped tan');
graph.addDependency('mirrored teal', 'striped tan');
graph.addDependency('striped red', 'striped tan');
graph.addDependency('clear indigo', 'striped teal');
graph.addDependency('striped black', 'striped teal');
graph.addDependency('dim salmon', 'striped tomato');
graph.addDependency('drab tomato', 'striped tomato');
graph.addDependency('faded coral', 'striped tomato');
graph.addDependency('drab aqua', 'striped turquoise');
graph.addDependency('mirrored aqua', 'striped turquoise');
graph.addDependency('pale lavender', 'striped turquoise');
graph.addDependency('wavy orange', 'striped turquoise');
graph.addDependency('dotted olive', 'striped violet');
graph.addDependency('dotted red', 'striped violet');
graph.addDependency('shiny gold', 'striped violet');
graph.addDependency('dotted green', 'striped white');
graph.addDependency('dotted teal', 'striped white');
graph.addDependency('shiny white', 'striped white');
graph.addDependency('vibrant fuchsia', 'striped white');
graph.addDependency('shiny turquoise', 'striped yellow');
graph.addDependency('shiny red', 'vibrant aqua');
graph.addDependency('wavy gold', 'vibrant aqua');
graph.addDependency('clear tan', 'vibrant beige');
graph.addDependency('plaid turquoise', 'vibrant beige');
graph.addDependency('shiny gold', 'vibrant beige');
graph.addDependency('wavy black', 'vibrant beige');
graph.addDependency('posh gold', 'vibrant black');
graph.addDependency('shiny white', 'vibrant black');
graph.addDependency('dark cyan', 'vibrant blue');
graph.addDependency('dim lavender', 'vibrant blue');
graph.addDependency('mirrored teal', 'vibrant bronze');
graph.addDependency('vibrant tomato', 'vibrant bronze');
graph.addDependency('clear silver', 'vibrant brown');
graph.addDependency('dotted chartreuse', 'vibrant brown');
graph.addDependency('dull lavender', 'vibrant brown');
graph.addDependency('bright beige', 'vibrant chartreuse');
graph.addDependency('dull salmon', 'vibrant chartreuse');
graph.addDependency('faded blue', 'vibrant chartreuse');
graph.addDependency('plaid brown', 'vibrant chartreuse');
graph.addDependency('plaid brown', 'vibrant coral');
graph.addDependency('vibrant silver', 'vibrant coral');
graph.addDependency('wavy brown', 'vibrant coral');
graph.addDependency('dotted tomato', 'vibrant crimson');
graph.addDependency('drab olive', 'vibrant crimson');
graph.addDependency('plaid black', 'vibrant crimson');
graph.addDependency('shiny gold', 'vibrant crimson');
graph.addDependency('clear cyan', 'vibrant cyan');
graph.addDependency('dark cyan', 'vibrant cyan');
graph.addDependency('dotted orange', 'vibrant cyan');
graph.addDependency('light turquoise', 'vibrant cyan');
graph.addDependency('dotted violet', 'vibrant fuchsia');
graph.addDependency('dull crimson', 'vibrant fuchsia');
graph.addDependency('clear tomato', 'vibrant gold');
graph.addDependency('clear turquoise', 'vibrant gold');
graph.addDependency('dark bronze', 'vibrant gold');
graph.addDependency('dark lime', 'vibrant gray');
graph.addDependency('dark purple', 'vibrant gray');
graph.addDependency('dark bronze', 'vibrant green');
graph.addDependency('dull brown', 'vibrant green');
graph.addDependency('pale teal', 'vibrant green');
graph.addDependency('wavy white', 'vibrant green');
graph.addDependency('drab red', 'vibrant indigo');
graph.addDependency('dull crimson', 'vibrant indigo');
graph.addDependency('pale gold', 'vibrant indigo');
graph.addDependency('posh gold', 'vibrant indigo');
graph.addDependency('dim green', 'vibrant lavender');
graph.addDependency('dotted coral', 'vibrant lavender');
graph.addDependency('plaid violet', 'vibrant lavender');
graph.addDependency('dark magenta', 'vibrant lime');
graph.addDependency('dotted white', 'vibrant lime');
graph.addDependency('muted tan', 'vibrant lime');
graph.addDependency('striped blue', 'vibrant magenta');
graph.addDependency('mirrored crimson', 'vibrant maroon');
graph.addDependency('wavy beige', 'vibrant maroon');
graph.addDependency('dotted green', 'vibrant olive');
graph.addDependency('dotted lime', 'vibrant olive');
graph.addDependency('drab blue', 'vibrant olive');
graph.addDependency('mirrored coral', 'vibrant olive');
graph.addDependency('bright plum', 'vibrant orange');
graph.addDependency('faded cyan', 'vibrant orange');
graph.addDependency('vibrant olive', 'vibrant orange');
graph.addDependency('faded blue', 'vibrant plum');
graph.addDependency('muted red', 'vibrant plum');
graph.addDependency('vibrant tomato', 'vibrant plum');
graph.addDependency('clear white', 'vibrant purple');
graph.addDependency('dim olive', 'vibrant purple');
graph.addDependency('dotted orange', 'vibrant purple');
graph.addDependency('striped aqua', 'vibrant purple');
graph.addDependency('dull maroon', 'vibrant red');
graph.addDependency('posh lime', 'vibrant red');
graph.addDependency('clear blue', 'vibrant salmon');
graph.addDependency('clear brown', 'vibrant salmon');
graph.addDependency('pale gold', 'vibrant salmon');
graph.addDependency('dark salmon', 'vibrant silver');
graph.addDependency('light silver', 'vibrant silver');
graph.addDependency('plaid orange', 'vibrant silver');
graph.addDependency('shiny chartreuse', 'vibrant silver');
graph.addDependency('wavy fuchsia', 'vibrant tan');
graph.addDependency('clear green', 'vibrant teal');
graph.addDependency('dull beige', 'vibrant teal');
graph.addDependency('dim lime', 'vibrant tomato');
graph.addDependency('drab indigo', 'vibrant turquoise');
graph.addDependency('mirrored green', 'vibrant turquoise');
graph.addDependency('plaid brown', 'vibrant turquoise');
graph.addDependency('bright white', 'vibrant violet');
graph.addDependency('light aqua', 'vibrant violet');
graph.addDependency('pale gray', 'vibrant violet');
graph.addDependency('light bronze', 'vibrant white');
graph.addDependency('wavy silver', 'vibrant white');
graph.addDependency('clear blue', 'vibrant yellow');
graph.addDependency('shiny white', 'vibrant yellow');
graph.addDependency('dark crimson', 'wavy aqua');
graph.addDependency('wavy gray', 'wavy aqua');
graph.addDependency('plaid red', 'wavy beige');
graph.addDependency('drab coral', 'wavy black');
graph.addDependency('light brown', 'wavy black');
graph.addDependency('plaid red', 'wavy black');
graph.addDependency('striped purple', 'wavy black');
graph.addDependency('dotted maroon', 'wavy blue');
graph.addDependency('light maroon', 'wavy blue');
graph.addDependency('plaid orange', 'wavy bronze');
graph.addDependency('vibrant green', 'wavy bronze');
graph.addDependency('vibrant orange', 'wavy bronze');
graph.addDependency('bright yellow', 'wavy brown');
graph.addDependency('dim black', 'wavy brown');
graph.addDependency('bright brown', 'wavy chartreuse');
graph.addDependency('dim lime', 'wavy chartreuse');
graph.addDependency('dim lavender', 'wavy coral');
graph.addDependency('light gold', 'wavy coral');
graph.addDependency('mirrored teal', 'wavy coral');
graph.addDependency('shiny chartreuse', 'wavy coral');
graph.addDependency('wavy tan', 'wavy crimson');
graph.addDependency('plaid tan', 'wavy cyan');
graph.addDependency('striped crimson', 'wavy cyan');
graph.addDependency('light cyan', 'wavy fuchsia');
graph.addDependency('posh salmon', 'wavy fuchsia');
graph.addDependency('shiny chartreuse', 'wavy fuchsia');
graph.addDependency('vibrant tomato', 'wavy fuchsia');
graph.addDependency('bright white', 'wavy gold');
graph.addDependency('pale cyan', 'wavy gray');
graph.addDependency('pale tomato', 'wavy gray');
graph.addDependency('light brown', 'wavy green');
graph.addDependency('muted silver', 'wavy green');
graph.addDependency('plaid indigo', 'wavy green');
graph.addDependency('mirrored tan', 'wavy indigo');
graph.addDependency('wavy lavender', 'wavy indigo');
graph.addDependency('dull gray', 'wavy lavender');
graph.addDependency('bright salmon', 'wavy lime');
graph.addDependency('light gray', 'wavy lime');
graph.addDependency('shiny cyan', 'wavy lime');
graph.addDependency('shiny plum', 'wavy lime');
graph.addDependency('dotted plum', 'wavy magenta');
graph.addDependency('dull tan', 'wavy magenta');
graph.addDependency('dark crimson', 'wavy maroon');
graph.addDependency('dull white', 'wavy maroon');
graph.addDependency('mirrored salmon', 'wavy maroon');
graph.addDependency('vibrant purple', 'wavy maroon');
graph.addDependency('light black', 'wavy olive');
graph.addDependency('wavy plum', 'wavy olive');
graph.addDependency('faded tomato', 'wavy orange');
graph.addDependency('pale gold', 'wavy plum');
graph.addDependency('pale gray', 'wavy plum');
graph.addDependency('vibrant cyan', 'wavy plum');
graph.addDependency('wavy gray', 'wavy plum');
graph.addDependency('clear maroon', 'wavy purple');
graph.addDependency('dull aqua', 'wavy purple');
graph.addDependency('posh bronze', 'wavy purple');
graph.addDependency('shiny tomato', 'wavy purple');
graph.addDependency('posh yellow', 'wavy red');
graph.addDependency('shiny coral', 'wavy red');
graph.addDependency('posh tomato', 'wavy salmon');
graph.addDependency('clear olive', 'wavy silver');
graph.addDependency('dark beige', 'wavy silver');
graph.addDependency('mirrored green', 'wavy silver');
graph.addDependency('plaid orange', 'wavy silver');
graph.addDependency('faded silver', 'wavy tan');
graph.addDependency('wavy brown', 'wavy tan');
graph.addDependency('pale brown', 'wavy teal');
graph.addDependency('drab green', 'wavy tomato');
graph.addDependency('dull aqua', 'wavy tomato');
graph.addDependency('faded lavender', 'wavy tomato');
graph.addDependency('vibrant gray', 'wavy tomato');
graph.addDependency('bright green', 'wavy turquoise');
graph.addDependency('dark teal', 'wavy turquoise');
graph.addDependency('muted brown', 'wavy turquoise');
graph.addDependency('shiny fuchsia', 'wavy turquoise');
graph.addDependency('light purple', 'wavy violet');
graph.addDependency('plaid red', 'wavy white');
graph.addDependency('dotted orange', 'wavy yellow');
graph.addDependency('light silver', 'wavy yellow');
var t=graph.dependenciesOf('shiny gold');
console.log(t.length, t);
